### PR TITLE
KOGITO-4654: Format codebase and check formatting as part of full downstream build 

### PR DESCRIPTION
**Pull request by jomarko**
The formatting changes were split into commits per 'package' to facilitate review.

### CODE REVIEW

**Comment by domhanak** [comment]
@jomarko I went throught the `Formatted packages/vscode-extension-pack-kogito-kie-editors/` and the changes seemed valid and ok. There might be some issues with tslint now, but I need to wait for the it-tests for vscode to finish :)

**Comment by manstis** [comment]
@jomarko I have no problem with the reformatting of either `pmml-editor-marshaller` or `pmml-editor`. Thank-you.

**Review by ederign — CHANGES_REQUESTED** [review]
This will require further discussion. Meanwhile, please hold down the merge.

**Comment by jomarko** [comment]
Closed as required on google chat thread.

**Comment by jomarko** [comment]
Replaced by #465

**Pull request closed without merging**
