### PR TITLE
KOGITO-7615: Bump `webdriver` to `5.2.1` and always using mirror site for `geckodriver`

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.redhat.com/browse/KOGITO-7615

We recently re-enabled selenium `it-tests` for our stunner-based assets.
Unfortunately, last builds failed:

`io.github.bonigarcia.wdm.config.WebDriverManagerException: io.github.bonigarcia.wdm.config.WebDriverManagerException: Error HTTP 403 executing https://api.github.com/repos/mozilla/geckodriver/releases`

The reason is that: `geckodriver` version repository is hosted by Github. Making many consecutive requests to GitHub with our builds, and due to its traffic rate limit, it eventually responds with an HTTP 403 error. [More info here](https://bonigarcia.dev/webdrivermanager/#known-issues)

Replacing it with the mirror https://registry.npmmirror.com/-/binary/geckodriver/ should finally solve it.

### CODE REVIEW

**Comment by tiagobento** [comment]
@yesamer One thing to keep in mind is that our Kogito Editors (BPMN, DMN, SceSim and SWF) are not compiled to run on Firefox in production. I looked at the GWT compiler configuration files and found that, for tests, `safari` and `gecko` are being used, but not for production.

Do you think it's possible to change the tests to run on Chrome?

**Comment by yesamer** [comment]
@tiagobento It's a good point, consider `safari` compilation include `chrome` based browser, so it should work with `chromedriver` too. I don't know why the `it-tests` author relied on `firefox` and not chrome. We can try.

**Comment by yesamer** [comment]
@tiagobento Tests are failing using `chromedriver`
`Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 14.989 s <<< FAILURE! - in org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerDataTypesPopOverIT
Error:  testNumberSuggestions(org.kie.workbench.common.dmn.showcase.client.selenium.DMNDesignerDataTypesPopOverIT)  Time elapsed: 14.98 s  <<< ERROR!`

`Error:  Errors: 
Error:    DMNDesignerDataTypesPopOverIT.testNumberSuggestions:41 » Timeout Expected cond...
Error:    DMNDesignerKogitoSeleniumIT.testDecisionExpressionDecisionTable:439->setDecisionTableDefaultOutput:2388 » ElementNotInteractable`

I suggest merging the original PR and analyze usage of `chromedriver` in a separate task.

**Comment by tiagobento** [comment]
@yesamer Agreed :)

**Comment by yesamer** [comment]
@tiagobento Can I have a merge here? :)

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
