### PR TITLE
.ci/Jenkins moved to .ci/jenkins

### PR DESCRIPTION
**Pull request by Ginxo**
.ci/Jenkins folder renamed to .ci/jenkins

### CODE REVIEW

**Review by radtriste — APPROVED** [review]

**Comment by Ginxo** [comment]
@ederign @radtriste @tiagobento is there any side effect? I've created https://github.com/kiegroup/kie-jenkins-scripts/pull/1106 for `Jenkinsfile.nightly`, but I'm not sure about `Jenkinsfile.vscode` job pointing to that file.

**Comment by tiagobento** [comment]
Yes, the Jenkins.vscode file is used by an external job that publishes our extensions to the VS Code and OVSX marketplaces.

cc @caponetto

**Comment by radtriste** [comment]
> @ederign @radtriste @tiagobento is there any side effect? I've created [kiegroup/kie-jenkins-scripts#1106](https://github.com/kiegroup/kie-jenkins-scripts/pull/1106) for `Jenkinsfile.nightly`, but I'm not sure about `Jenkinsfile.vscode` job pointing to that file.

I don't know which job is using it ...

**Review by caponetto — APPROVED** [review]
No problems with this change. I'll update the corresponding job once this PR is merged.

**Comment by Ginxo** [comment]
thanks guys!! @caponetto please go ahead!

**Pull request merged**
