### PR TITLE
Test stability of new files test

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Draft PR. Do not merge. Just testing the stability of some new Cypress tests.

### CODE REVIEW

**Comment by tiagobento** [comment]
@tomasdavidorg Tomas, can you please add a more descriptive title to this PR? There's a lot of ways to interpret it the way it is now.

**Comment by tomasdavidorg** [comment]
@tiagobento This is just draft PR but I think the regular Draft PR would not execute the tests. 
Basically I am trying to write cypress tests for the empty yaml and json SWF and I want to test stability in the GitHub actions.

This is not ready for review and for merging.
Sorry for confusing PR. I hope it is now more clear.

**Comment by caponetto** [comment]
@tomasdavidorg One tip when you want to make tests on CI is to open a PR targeting your own fork's `main` branch.
This way you would have more control over re-runs. When the code is good to go, you can open the final PR here.
Example https://github.com/caponetto/kie-tools/pull/40.

**Comment by tomasdavidorg** [comment]
Thanks for the tip @caponetto 😊

**Pull request closed without merging**
