### PR TITLE
KOGITO-8949: Recreate TrySample test for Serverless Logic Web Tools

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://issues.redhat.com/browse/KOGITO-8949

This PR recreates the e2e test for trying samples from the catalog.

The catalog downloads the samples from GitHub repository which causes that the API limit is exceeded and the samples are not loaded.
In this PR, the test expects GitHub token as `CYPRESS_E2E_TEST_GITHUB_TOKEN` env. variable and run the tests only if the token is present. 
GitHub action will not run the tests because currently there is no test token. It is primary focused on QE Jenkins runs but if needed we can add the token to the GitHub actions credentials.

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
Rebased with main branch because of the Cypress update.

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Comment by caponetto** [comment]
@tomasdavidorg Could you please resolve the conflict so I can merge this PR?

**Comment by tomasdavidorg** [comment]
@caponetto Rebased and the checks are green.

**Pull request merged**
