### PR TITLE
kie-tools#2504: Remove outdated bddframework from sonataflow-operator

### PR DESCRIPTION
**Pull request by wmedvede**
(cherry picked from commit 4d3feff041b5c78f609b0987d288e20011a022e9)

### CODE REVIEW

**Comment by tiagobento** [comment]
Where is this commit from originally @wmedvede ?

**Review by ricardozanini — APPROVED** [review]

**Comment by ricardozanini** [comment]
> 4d3feff

From 10.x.

**Comment by tiagobento** [comment]
@ricardozanini Thanks! I get a different commit SHA from 10.0.x (https://github.com/apache/incubator-kie-tools/commit/f15c0a4cd5bb650143616c39558a5619c5a681c7). I guess this one you shared is from Walter's fork? Anyway, all good :)

**Review by tiagobento — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Comment by wmedvede** [comment]
Fixes: #2504

**Pull request merged**
