### PR TITLE
[0.27.0-prerelease] KOGITO-8798: Skip VSCode Select states test becau…

### PR DESCRIPTION
**Pull request by LuboTerifaj**
…se of bug in Canvas API (#1505)

https://issues.redhat.com/browse/KOGITO-8798

Cherry-pick for: https://github.com/kiegroup/kie-tools/pull/1505

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hey @handreyrc , here is the cherry-pick for 0.27.0. Could you please have a look? Thanks!

**Comment by caponetto** [comment]
@LuboTerifaj The release branch is closed for new PRs unless the PR fixes a blocker issue.

**Comment by LuboTerifaj** [comment]
Hello @caponetto , 

the PR doesn't affect any functional changes. In addition, the jira has the blocker priority set.

According to the changes, I don't see the reason why we should not merge this PR. It there any specific reason why we should avoid merging?

Thanks!

**Comment by ederign** [comment]
@LuboTerifaj, we are in the final stages of the manual sanity check (in collaboration with IBM), and if we change the codebase, we will need to restart this process again. 

Let's merge this important PR on the main, which will be included in the subsequent releases. I hope you understand.

**Comment by LuboTerifaj** [comment]
Hey @ederign , I see. Thank you for the clarification.

**Pull request closed without merging**
