### PR TITLE
Quarkus LTS Upgrade to 3.8.4

### PR DESCRIPTION
**Pull request by baldimir**
Related https://github.com/apache/incubator-kie-issues/issues/958

Ensemble:
https://github.com/apache/incubator-kie-drools/pull/5853
https://github.com/apache/incubator-kie-optaplanner/pull/3076/files
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3477
https://github.com/apache/incubator-kie-kogito-apps/pull/2039
https://github.com/apache/incubator-kie-kogito-examples/pull/1908
https://github.com/apache/incubator-kie-kogito-images/pull/1760

### CODE REVIEW

**Comment by pefernan** [comment]
@baldimir I think we must wait until we merge the other upstream PRs and we get a new `kogito` timestamped version that's upgraded to Quarkus `3.8.4`, otherwhise `kie-tools` will be using a Quarkus `3.8.4` and a `kogito` version that still relies in Quarkus `3.2`

**Comment by yesamer** [comment]
@baldimir Yep, I agree with @pefernan

**Review by yesamer — CHANGES_REQUESTED** [review]
We need to wait for the first TIMESTAMPED version of Kogito that supports Quarkus 3.8.x (hopefully 20240505)

**Comment by tiagobento** [comment]
Upgrading Quarkus and upgrading to a new timestamped SNAPSHOT in one shot is the way to go.. We need to merge this PR with  
- https://github.com/apache/incubator-kie-tools/pull/2272

If 999-20240428 is indeed already ported to Quarkus 3.8.4... which I'm not sure it is...

**Comment by porcelli** [comment]
based on the comments, I think it's safe to close this until we have a new weekly updated

**Pull request closed without merging**
