### PR TITLE
KOGITO-3909: New Data Type Is Dirty indicator - reproducer

### PR DESCRIPTION
**Pull request by jomarko**
Adding test to check 'Is Dirty' indicator is shown after new Data Type was added

For more details see: https://issues.redhat.com/browse/KOGITO-3909

Dependent on:
- https://github.com/kiegroup/kie-wb-common/pull/3537
- https://github.com/kiegroup/appformer/pull/1090

### CODE REVIEW

**Comment by tiagobento** [comment]
@jomarko As per the new workflow, you can go ahead and merge the appformer/kie-wb-common parts. Then, you can generate a new version using our `Maven :: Publish Editors snapshot version to NPM` workflow.

**Comment by jomarko** [comment]
@tiagobento yes, I am waiting for final approval/response to my comment on kiegroup/kie-wb-common#3537

**Review by jstastny-cz — APPROVED** [review]
Code looks good, thanks.

**Comment by jomarko** [comment]
Fail in the appformer build:
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources (default-resources) on project dashbuilder-webapp: Execution default-resources of goal org.apache.maven.plugins:maven-resources-plugin:2.6:resources failed: Plugin org.apache.maven.plugins:maven-resources-plugin:2.6 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-core:jar:2.0.6 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-core/2.0.6/maven-core-2.0.6.jar: Connection reset -> [Help 1]
```

**Comment by tiagobento** [comment]
@jomarko Jozef, I just merged #374 and it updated the Editors version too. Since the version there is newer than the one you have here, please rebase this PR and accept the changes from `master`. The checks will run again for us to be sure, but I expect them to be all green =) Thanks!

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
