### PR TITLE
NO-ISSUE: Set locale to "en-US" before generating `image-builder` and `run-script-if` READMEs

### PR DESCRIPTION
**Pull request by ljmotta**
Adding this prevent `yargs` of using the machine locale.

### CODE REVIEW

**Review by thiagoelg — APPROVED** [review]

**Comment by tiagobento** [comment]
What problem does this solve? I get that this pins the locale, but why do we need that?

**Comment by ljmotta** [comment]
@tiagobento `yargs --help` is used to write the the `image-builder` and `run-script-if` README files. By default `yargs` use the machine locale, so in my case it was `en-BR`, which re-writed the files using Portuguese.

**Comment by tiagobento** [comment]
Maybe instead of hardcoding it to all the invocations of `image-builder` and `run-script-if`, we could simply foce the locale in the invocations specific to building the READMEs, no?

**Comment by tiagobento** [comment]
I mean, defining a locale is pretty out of scope for `run-script-if` and `image-builder`.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
