### PR TITLE
[kie-issues#1446] BPMN Editor - Decision name UI field removal

### LINKED ISSUE #1446: Stunner Editor - Remove "decision name" field
The "decision name" property field in the BPMN editor when a DMN type Rule Task is selected is useless. The data is not used in the backend, and there isn't any way to retrieve a decision based on its name. This field is unnecessary. The rest of the fields should stay the same and in the same order.

### PR DESCRIPTION
**Pull request by LightGuard**
Closes https://github.com/apache/incubator-kie-issues/issues/1446

The "Decision Name" field in the UI does not do anything. I've gone through the backend, we don't even haven anyway of referencing a "decision name." Remove this field as it is unnecessary.

Thanks to @jomarko for a starting point.

### CODE REVIEW

**Comment by LightGuard** [comment]
Fixes #2542

**Comment by LightGuard** [comment]
Fixes https://github.com/apache/incubator-kie-issues/issues/1446

**Comment by LightGuard** [comment]
Is there anything to be done for the Code scanning job? Looks like we're missing something for that job to complete.

**Comment by tiagobento** [comment]
I'm not sure @LightGuard. I remember seeing it a while ago but thought GitHub was unstable. Feel free to look into it if you got time...

**Review by jomarko — COMMENTED** [review]
Thank you for the PR @LightGuard . I always like situation where we reduce the codebase to maintain. This seems to be the case. What I see as important to do at the same time to reflect this also in [apache/incubator-kie-kogito-examples](https://github.com/apache/incubator-kie-kogito-examples). There are multiple examples where:
- are README files with instruction to set `Decision Name` what is nto true anymore, e.g. [1]
- are screenshots containing `Decision Name` what is not true anymore, e.g. [2]
- are assignments in the bpmn files, not needed anymore, e.g. [3]

[1] https://github.com/apache/incubator-kie-kogito-examples/blob/main/kogito-quarkus-examples/process-decisions-quarkus/README.md?plain=1#L76

[2] https://github.com/apache/incubator-kie-kogito-examples/blob/main/kogito-quarkus-examples/process-decisions-quarkus/docs/images/traffic-violation-dmn-businessrule-properties.png

[3] https://github.com/apache/incubator-kie-kogito-examples/blob/main/kogito-quarkus-examples/process-decisions-quarkus/src/main/resources/traffic-rules-dmn.bpmn#L220

**Comment by tiagobento** [comment]
Thank you @jomarko. Can you please file an issue on `kie-issues` for us to track those outdated places? Thanks!

**Review by tiagobento — APPROVED** [review]

**Review by porcelli — APPROVED** [review]
LGTM

**Comment by jomarko** [comment]
@tiagobento , sure, ticket created https://github.com/apache/incubator-kie-issues/issues/1449

**Pull request merged**
