### PR TITLE
KOGITO-8307: SWF Editor - States without incoming transition are shown in top left corner

### PR DESCRIPTION
**Pull request by danielzhe**
Ticket: https://issues.redhat.com/browse/KOGITO-8307

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Hey @LuboTerifaj 
Early review appreciated, as the deadline for this fix in end of this week. Could you please take a look? 
Thanks in advance!

**Review by LuboTerifaj — COMMENTED** [review]
Hello @danielzhe , the build failed. Could you please have a look? Thanks!

**Comment by danielzhe** [comment]
All green, @LuboTerifaj !

**Review by LuboTerifaj — APPROVED** [review]
Hello @danielzhe ,

I have just one minor comment:

The states are shown on the left from states with outgoing transition. I am wondering if it wouldn't be better to show them on the right side. If we keep it as it is and you add more statements without transitions, those with outgoing transitions will be too far from the rest of states.

I will leave the comment in the jira as well.

The PR fixes the original issue, so I am approving it.

Thanks!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @danielzhe ,

I just rechecked the PR and compared it with main once again, but unfortunately I found the issue with centering start node.  See the picture:
Screenshot from 2022-12-09 15-38-35

Could you please fix that?

Thanks!

**Comment by romartin** [comment]
Hey @danielzhe 

Is this ready for review again?

**Comment by danielzhe** [comment]
@romartin Yes

@LuboTerifaj Changes applied!

**Review by LuboTerifaj — APPROVED** [review]
Hey @danielzhe ,

The whole diagram sometimes look weird and not centered as I already mentioned in other jiras/PRs, but it is a general issue of node tree rendering algorithm, not related to this one.

It looks good to me now.

Thank you for the fix!

**Comment by romartin** [comment]
ok Thanks @LuboTerifaj !

BTW can you please @danielzhe do the cherry-pick to this branch please? https://github.com/kiegroup/kie-tools/tree/0.26.0-prerelease

**Pull request merged**
