### PR TITLE
KOGITO-2204: Initial E2E tests for desktop channel

### PR DESCRIPTION
**Pull request by domhanak**
@jomarko Please take a look and let me know your opinion about the code.

Stabilizing this on CI now.
There is an issue with parallel execution that I am looking into.

### CODE REVIEW

**Comment by domhanak** [comment]
@tiagobento @paulovmr Is there a way to abort the CI? CI check here getting stuck, I am unable to reproduce locally though.

**Comment by paulovmr** [comment]
Hi @domhanak , I've cancelled this PR's jobs, also I created a [PR](https://github.com/kiegroup/kogito-tooling/pull/263) to set a timeout for these jobs (30min for CI and 90min for FDB).

**Comment by domhanak** [comment]
No luck yet, there seems to be an issue with Xvfb and environment. Locally I can see the test pass and run, but when I fiddle with environment and DISPLAY, xvfb I can reproduce to some extent.

**Comment by domhanak** [comment]
So the issue is that port chromedriver tries to run on is already in use (98) when tests start to boot up the chromedriver. Looking for workaround and what is actually running there.

**Comment by domhanak** [comment]
Another possibility is that GHActions have chrome of version 85, which is not compatible with 78 which is used by spectron.

**Comment by domhanak** [comment]
Closing to avoid pooling the CI resources. Will reopen once stabilized on my fork.

**Pull request closed without merging**
