### PR TITLE
NO-ISSUE: Use timestamped SNAPSHOT on `serverless-logic-web-tools-swf-builder-image`

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Comment by tiagobento** [comment]
@yesamer Since the `main-2024-02-18` tag of `quay.io/kiegroup/kogito-swf-builder-nightly` is currently broken, can you please incorporate my changes adapting to the latest timestamped SNAPSHOT/tag on #2193 ?

**Comment by tiagobento** [comment]
@yesamer I'll close this PR after you've applied the changes to #2193...

**Comment by tiagobento** [comment]
Never mind, I think we need to wait for https://github.com/apache/incubator-kie-kogito-images/pull/1750 to be merged, then wait for a new timestamped SNAPSHOT so we can update.

**Comment by ricardozanini** [comment]
> Never mind, I think we need to wait for [apache/incubator-kie-kogito-images#1750](https://github.com/apache/incubator-kie-kogito-images/pull/1750) to be merged, then wait for a new timestamped SNAPSHOT so we can update.

I'm just waiting for the CI to decide to work :)

**Comment by tiagobento** [comment]
Closed as changes were incorporated in #2193

**Pull request closed without merging**
