### PR TITLE
AF-2273 / AF-2274: New Chrome Extension features

### PR DESCRIPTION
**Pull request by tiagobento**
This PR includes:
- Visualizing diagram editors on Visualization GitHub screen
- Visualizing diagram editors on PR GitHub screen with comparison between original and changed files
- Resiliency mechanism to render features depending on GitHub's DOM structure. If GitHub changes its screens, we can quickly find out what's changed and react accordingly.

### CODE REVIEW

**Comment by tiagobento** [comment]
Jenkins please retest this

**Comment by manstis** [comment]
Shouldn't `yarn.lock` files be removed these days?!

**Comment by tiagobento** [comment]
@manstis Yes, but that's on a different PR. When that PR is merged we will no longer commit `yarn.lock` files.

**Comment by tiagobento** [comment]
Looks like this PR won't turn green while Jenkins is not configured to access our CI's NPM registry instead of the default one.

**Comment by tiagobento** [comment]
@domhanak ^

**Review by ederign — APPROVED** [review]

**Comment by domhanak** [comment]
@tiagobento let me know for PR's like this, it is hard to do a review when you merge it so fast :)

**Comment by tiagobento** [comment]
@domhanak Don't worry about that. I ask for reviews to notify you that new stuff is coming, but if you can't review it before we decide to merge, it's alright :)

We squash the commits, so every PR becomes one single commit that you can later review and add your comments. Just make sure to tag me in them so I get an email.

**Pull request merged**
