### PR TITLE
Bump `kie` to `8.32.0` on Stunner Editors

### PR DESCRIPTION
**Pull request by yesamer**
Update of `org.antlrgwt` is required as well https://github.com/kiegroup/drools/pull/4852

### CODE REVIEW

**Comment by jomarko** [comment]
@yesamer thank you for the PR. I would like to be sure I understand the affected area of the DMN Editor.

Is the `antlr4gwt` dependency crucial for an autocompletion of feel expressions, or validation of feel expressions or execution of them, or ...

**Comment by yesamer** [comment]
>  autocompletion of feel expressions 

This. @Rikkola Can you please confirm that?

**Comment by Rikkola** [comment]
@jomarko @yesamer It is, antrl is used with C3 to look at the existing code and figure out the suggestion.

**Comment by jomarko** [comment]
### Manual checks 
Done just in VS Code as online-editor (kie sandbox) is not in build artifacts
- [x] Autocompletion for empty text
- [x] Autocompletion for non empty text
- [x] Confirm autocompletion, type again, choose another autocompletion suggestion
- [x] Autocompletion and switching DMN expression editors

**Review by jomarko — APPROVED** [review]
Thank you for this change @yesamer

**Pull request merged**
