### PR TITLE
KOGITO-3660: Generate input/output columns, based on the type of the input nodes/the type decision node

### PR DESCRIPTION
**Pull request by vpellegrino**
KOGITO-3660
Using Enricher strategy for enrich expression models like we were doing in the legacy editor.

### CODE REVIEW

**Review by jomarko — COMMENTED** [review]
@vpellegrino thank you, would you mind to fix one codesmell found by sonar please?

https://sonarcloud.io/project/issues?id=org.kie.kogito%3Akogito-tooling&open=AX7ESaad93bXKuDNtCt8&pullRequest=837&resolved=false&sinceLeakPeriod=true&types=CODE_SMELL

**Comment by vpellegrino** [comment]
@jomarko done: https://github.com/kiegroup/kie-tools/pull/837/commits/81811b58cb4433e0f7f0ffb3807b3444cce7511a

**Review by jomarko — APPROVED** [review]
No issues found during manual check.

**Comment by vpellegrino** [comment]
@yesamer @danielzhe @fantonangeli guys, can you please review? We need another approval before asking for merge, thanks

**Review by yesamer — APPROVED** [review]
LGTM

**Review by fantonangeli — APPROVED** [review]
Everything good from my side

**Comment by vpellegrino** [comment]
@yesamer can we get a merge, please?

**Pull request merged**
