### PR TITLE
NO-ISSUE: Bump `express` version to `4.19.2`

### PR DESCRIPTION
**Pull request by yesamer**
Fixes https://github.com/advisories/GHSA-rv95-896h-c2vc

### CODE REVIEW

**Review by porcelli — APPROVED** [review]
thank you for addressing important CVE

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@yesamer  Not sure why we didn't see the older entry of `express` being removed from `pnpm-lock.yaml`, though...

**Comment by yesamer** [comment]
@tiagobento I'll check it

**Comment by yesamer** [comment]
@tiagobento Removed.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
