### PR TITLE
KOGITO-7902: Missing unit test coverage for TransitionMarshalling and WorkflowMarshalling classes

### PR DESCRIPTION
**Pull request by Josephblt**
**JIRA:** [KOGITO-7902 - Missing unit test coverage for TransitionMarshalling and WorkflowMarshalling classes](https://issues.redhat.com/browse/KOGITO-7902)

Adding coverage for Definition classes and marshallers.

**VS Code Extension:** [Serverless Workflow]()

### CODE REVIEW

**Comment by domhanak** [comment]
@Josephblt Hi, nice work. Although I did not expect selenium coverage. The idea behind the JIRA was unit test for the specific classes. 
I see some code duplication, I guess we can handle that later.
Any idea why builds do not run?

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
@domhanak please missing review here. Thanks!

**Comment by domhanak** [comment]
@romartin I do not see the build executed for the PR. Any ideas why?

**Comment by romartin** [comment]
@domhanak no idea honestly. I can't see the button for rebuilding either. It looks the build workflow is not executed. @Josephblt can you please rebase or something and try to force the build?

**Comment by romartin** [comment]
@Josephblt I still can't see the build resuls, any ideas why?

**Comment by Josephblt** [comment]
Hello @romartin, retriggered the builds again. Let's see how it goes.

**Review by domhanak — APPROVED** [review]

**Pull request merged**
