### PR TITLE
BXMSPROD-1128: Nightly build

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1128

### CODE REVIEW

**Comment by tiagobento** [comment]
@Ginxo Please see #344.

**Review by jstastny-cz — APPROVED** [review]
I reviewed the packages pushed to internal registry. I was able to build testing application using the package.
So I approve in a sense that outcome is correct. I have limited insights to do the actual code review.

**Comment by tiagobento** [comment]
Closing as I think this subject is resolved now. cc @Ginxo

**Comment by Ginxo** [comment]
@tiagobento this PR needs to be merged

**Comment by tiagobento** [comment]
@Ginxo The `pom.xml` file on this PR looks invalid to me, since the referenced modules there do not exist anymore.. Could you please check?

**Comment by Ginxo** [comment]
closed by https://github.com/kiegroup/kogito-tooling/pull/407

**Pull request closed without merging**
