### PR TITLE
KOGITO-7629: SWF Viewer - Exception is thrown when an arrow is selected

### PR DESCRIPTION
**Pull request by hasys**
No null pointers any more on selection Edges.

To see raising/not raising exception open Developer Tools console.

[VSIX for tests](https://drive.google.com/file/d/1Hh8z50WJhGkKZPcnF2pFuUmKCxFfAfAC/view?usp=sharing)

### CODE REVIEW

**Review by caponetto — APPROVED** [review]
Thanks @hasys, changes resolve the issue.
I didn't find any other issue related to selection, but maybe we should avoid calling  `moveCursorToNode` (line 41) if `stateName` is null.
cc @fantonangeli

**Comment by hasys** [comment]
> Thanks @hasys, changes resolve the issue. I didn't find any other issue related to selection, but maybe we should avoid calling `moveCursorToNode` (line 41) if `stateName` is null. cc @fantonangeli

Hello @caponetto,
thank you for the quick response. The called method already have null pointer checker in it, I think it will be excessive to add addition one. WDYT?

```java
    @Override
    public void moveCursorToNode(final String stateName) {
        if (stateName != null) {
            DiagramApiInteropWrapper.get().moveCursorToNode(stateName);
        }
    }
```

**Comment by caponetto** [comment]
@hasys I agree! I didn't see that null check. Thanks for pointing this out!

**Review by romartin — APPROVED** [review]

**Review by LuboTerifaj — COMMENTED** [review]
Hello @hasys ,

would it be possible to add a test for the change?

Otherwise it looks good to me.

Thanks!

**Comment by hasys** [comment]
Hi @LuboTerifaj,

good point, I added tests for this class and for my changes as well.

Thank you!

**Review by romartin — APPROVED** [review]
Looks good to me @hasys . Let's just add some test cases. Thanks!

**Comment by hasys** [comment]
Hello @LuboTerifaj, @romartin,

tests are ready see [new commit](https://github.com/kiegroup/kie-tools/pull/1140/commits/5c1200a7a9f376edf8d4a96be4c87f4e3f0b95a2)

Thank you!

**Review by LuboTerifaj — COMMENTED** [review]
Hello @hasys , could you please unignore the ignored tests? Thanks!

**Comment by hasys** [comment]
Great catch @LuboTerifaj,

it was a commit for building on my machine see [KOGITO-7613](https://issues.redhat.com/browse/KOGITO-7613). Anyway I reverted this commit, so it's ready.

Thank you!

**Review by LuboTerifaj — APPROVED** [review]
Great @hasys , thanks for the update. It looks good to me now.

**Review by caponetto — APPROVED** [review]

**Comment by hasys** [comment]
@kiegroup/gatekeepers this pr is ready for merge, thank you!

**Pull request merged**
