### PR TITLE
KOGITO-6238: Fix WorkspaceAPI file opening in Windows environments

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.redhat.com/browse/KOGITO-6238 

The change substitutes `fsPath` with `path`

**fsPath vs path comparison on different env.**

**Linux** 
- fsPath: `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources/Traffic Violation.dmn`
- path: `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources/Traffic Violation.dmn`  <--
- dirname(fsPath): `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources`
- dirname(path): `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources` <--
- joined(fsPath): `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources/External.dmn`
- joined(fsPath):  `/home/yamer/IdeaProjects/kogito-examples/dmn-quarkus-example/src/main/resources/External.dmn` <--

**Windows** 
- fsPath: `c:\Users\LaptopHP\Downloads\dmn-quarkus-example\src\main\resources\Traffic Violation.dmn`
- path: `/c:/Users/LaptopHP/Downloads/dmn-quarkus-example/src/main/resources/Traffic Violation.dmn` <--
- dirname(fsPath): `.`
- dirname(path): `/c:/Users/LaptopHP/Downloads/dmn-quarkus-example/src/main/resources` <--
- joined(fsPath): `External.dmn`
- joined(fsPath):  `/c:/Users/LaptopHP/Downloads/dmn-quarkus-example/src/main/resources/External.dmn` <--

### CODE REVIEW

**Comment by yesamer** [comment]
@jomarko @danielzhe I suggest manually testing this after https://github.com/kiegroup/kogito-editors-java/pull/161 merge.

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@yesamer Excellent catch! Thanks for promptly sending this PR!!

**Review by jomarko — APPROVED** [review]
Approving, as don't have WIN environment to try the changes. Code looks good to me.

**Comment by tiagobento** [comment]
Waiting on @danielzhe's review to merge.

**Comment by danielzhe** [comment]
Great job! I tested it with https://github.com/kiegroup/kogito-editors-java/pull/161 and it worked. Thank you!

**Review by danielzhe — APPROVED** [review]

**Pull request merged**
