### PR TITLE
KOGITO-4588: Test cutom data types are supported by DMN Expression Editor

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
Thanks for this test case @jomarko

**Review by ljmotta — APPROVED** [review]

**Comment by tiagobento** [comment]
Let's wait for the test to be un-skipped so that it actually runs and we can confirm that the CI is green. Once #723 is merged, we can re-trigger the CI here.

**Comment by tiagobento** [comment]
@jomarko Btw we also have this one: `dmn-new-expression-editor.spec.ts` for the Standalone Editors.

**Comment by jomarko** [comment]
@tiagobento could you please explain your comment above?

_@jomarko Btw we also have this one: dmn-new-expression-editor.spec.ts for the Standalone Editors._  I do not understand your point.

**Comment by tiagobento** [comment]
@jomarko There's another test that is skipped waiting for the Editors version to be bumped.

**Comment by jomarko** [comment]
@tiagobento _@jomarko There's another test that is skipped waiting for the Editors version to be bumped._ yes, they will be handled separately [1]. I will not unskip them as part of this PR.

please also notice, this PR is not dependent on #723. Tests adding via #721 are dependent on https://github.com/kiegroup/kogito-editors-java/pull/196 where I am not sure if those changes will be 8.5.4 or 8.5.5

in case they are in 8.5.4, yes, you are correct. Otherwise this PR can be merged right now.

[1]
https://issues.redhat.com/browse/KOGITO-6421

**Comment by tiagobento** [comment]
@jomarko This PR adds a tests that doesn't run. This is essentially dead code. I'd rather wait for this PR to be able to be merged with the test unskipped. There's no point in merging it before we actually see this test running.

**Comment by tiagobento** [comment]
@jomarko I think you can un-skip the test now and see how it works on the CI?

**Comment by jomarko** [comment]
@tiagobento yes, thank you for a reminder, I removed the `skip`. Lets wait for CI results.

**Comment by jomarko** [comment]
@tiagobento , the test is failing, as the changes https://github.com/kiegroup/kogito-editors-java/pull/196 we merged after 17th of December.

**Comment by tiagobento** [comment]
Ok, let's wait for this PR to be cherry-picked.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
