### PR TITLE
Bump Editors to version 8.5.4

### PR DESCRIPTION
**Pull request by yesamer**

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@yesamer You need to update `feel-input-component` and `boxed-expression-component` too. @ljmotta Can you please assist Yeser on this one?

**Review by tiagobento — CHANGES_REQUESTED** [review]
See comment above.

**Comment by ljmotta** [comment]
@tiagobento Sure thing, I'm going to open a PR to this branch updating the versions.

**Comment by ljmotta** [comment]
@yesamer Hi, I've opened this PR to your branch https://github.com/yesamer/kogito-tooling/pull/2 . It updates the `boxed-expression-component` and `feel-input-component` versions. Also, it updates the DMN Runner Table to be compatbile with the latest version.

**Comment by yesamer** [comment]
Hi @ljmotta, 
- Merged https://github.com/yesamer/kogito-tooling/pull/2
- Integrated your pr https://github.com/kiegroup/kogito-tooling/pull/718 to fix tests

Still, one test is failing on DMN Runner:

@kogito-tooling/online-editor:   ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
@kogito-tooling/online-editor:   │ ✔  DMNExpressionEditor.ts                   01:04        3        2        -        1        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✔  DMNGuidedTourTest.ts                     00:36        1        1        -        -        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✖  DMNRunnerTest.ts                         01:56        2        1        1        -        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✔  NewFileTest.ts                           01:06        3        3        -        -        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✔  OpenFromSourceTest.ts                    01:22        3        3        -        -        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✔  TrySampleTest.ts                         01:18        3        3        -        -        - │
@kogito-tooling/online-editor:   ├────────────────────────────────────────────────────────────────────────────────────────────────┤
@kogito-tooling/online-editor:   │ ✔  UploadFileTest.ts                        01:38        4        4        -        -        - │
@kogito-tooling/online-editor:   └────────────────────────────────────────────────────────────────────────────────────────────────┘
@kogito-tooling/online-editor:     ✖  1 of 7 failed (14%)                      09:03       19       17        1        1        -

**Review by tiagobento — APPROVED** [review]
@yesamer @ljmotta Thanks guys 😍

**Pull request merged**
