### PR TITLE
KOGITO-8793: BoudingBox values of states with tooltip boxes are wrong

### PR DESCRIPTION
**Pull request by hasys**
Hello @LuboTerifaj, @handreyrc,

there is a fix, now tooltip is created on mouse hover and removed on mouse out, so BoundingBox not expanding by the tooltip until it is not created.

Thank you!

### CODE REVIEW

**Comment by hasys** [comment]
Hi @LuboTerifaj,

we checked with @handreyrc  the it tests and they are passing locally and failing on the CI, looks like we have random fails back on the menu. Is it known issue?

I restarted the build, let's see if it will pass now. Thank you!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @hasys ,

I found issue with node dimensions. The function returns [250, 92] instead of [250, 90] for states with icons.

Could you please also add the tests for checking the expected values?

Regarding the test stability, yes there may be a different environment configuration using CI in comparison with local env. We should definitely stabilize it once this issue is resolved.

I can have a look at the issue afterwards.

Thank you!

**Review by handreyrc — CHANGES_REQUESTED** [review]
Hey @hasys, 

Great job here the code looks good and works fine to me!

In my opinion it would be good to add some regular unit tests around the creation and destruction of the the tooltip box making sure those methods are being called in the process. 
It should also be possible to add some IT tests in the scope of the sw-editor to assert the dimensions of the group. There are some helper classes implemented to call js methods.

WDYT?

**Comment by hasys** [comment]
Hello @handreyrc, @LuboTerifaj,

I added integration test for Dimension. Thank you for the quick feedback!

**Review by handreyrc — APPROVED** [review]
Hey @hasys,

Thanks for adding IT tests!
Everything looks good to me.

 Thanks a lot for your work here.

**Review by LuboTerifaj — APPROVED** [review]
Hey @hasys ,

it looks good to me now.

Thank you!

**Comment by hasys** [comment]
Thank you @LuboTerifaj, @handreyrc!

Hello @kiegroup/gatekeepers, this PR is ready for merge. Thank you!

**Review by romartin — APPROVED** [review]

**Pull request merged**
