### PR TITLE
FAI-188: Score Cards: Integrate into kogito-tooling channels

### PR DESCRIPTION
**Pull request by manstis**
**=== PLEASE IGNORE ME ===**

Move along; there is nothing to see here.... (when #272 is merged I'll rebase this...)

See https://issues.redhat.com/browse/FAI-188

@tiagobento @ederign 

This provides "just enough" of a PMML editor to consider how it will be integrated into channels.

The `kogito-tooling/packages/pmml-editor/dist/editor` contains the editor that supports `setContent(..)`.

You can run `yarn run build:showcase` in `kogito-tooling/packages/pmml-editor` and `yarn run start` to get a simple container to demonstrate _using_ the PMML editor itself. You can browse for a file or create a new one; either of which invokes `setContent(..)` on the editor.

The purpose of this PR is to start an early discussions about _how_ React/TS editors are to be re-used.

It contains a `PMMLEditorFactory` (the use of which has already been suggested to be obsolete).

I thought this may be useful for _us_ to have a working example to figure out/test integration.

WDYT?

### CODE REVIEW

**Comment by manstis** [comment]
@ederign pointed me to the following:
- https://github.com/paulovmr/kogito-online/blob/teste-embeddable/index2.html#L57-L58
- https://paulovmr.github.io/kogito-online/dmn/

Which may impact how _new_ React based editors are packaged/referenced....

I await to here from the masters.

**Comment by tiagobento** [comment]
@manstis Hi! That's right. @paulovmr has been working on creating a single JS file containing our Editors. This is really cool and will facilitate how people can consume and embed our Editors in their apps. I don't see, however, how that would affect the PMML Editor. What are your concerns around that? :)

We will continue to have an EmbeddedEditor component for React-based applications but we will also have this "standalone embeddable" version, which can be consumed as a plain JS/TS library.

**Comment by ederign** [comment]
Hi @manstis in fact, your EmbeddedEditor work really sped up Paulo's task. I see Paulo's work as a nice 'wrapper' for external consumption of our editors. Internally, we can keep following the current approach. (/cc @porcelli )

Adding to what Tiago said, in the future and if makes sense for customers/community, we can even write the same type of wrappers for the PMML editor, allowing users to embedded them on their own applications in a nice way

**Comment by manstis** [comment]
Great thanks @tiagobento @ederign I misunderstood that @paulovmr current work was replacing how additional editors are added to channels. This PR therefore remains "valid" being the first(?) REACT editor to trial adding to channels. Once my existing PR is merged I'll rebase this and see if I can progress it to include the mocked PMML editor in a channel (but not to be merged into `master`). How are (React) editors now instantiated? @tiagobento has said `EditorFactory` is deprecated (although it still appears to be used in the `envelope` on `master`).

**Comment by tiagobento** [comment]
@manstis Yes, exactly. This PR remains valid :)

The `EditorFactory` has not been deprecated and it is (and will continue being) used. What's deprecated was the `CompositeEditorFactory`, since we now don't want two different Editors to be bundled inside the same Envelope.

**Comment by manstis** [comment]
Outdated and not required at the moment...

**Pull request closed without merging**
