### PR TITLE
KOGITO-8716: [SWF Viewer] Backward orthogonal Lines should not overlap states

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, could you please review this PR?

**JIRA**: [KOGITO-8716](https://issues.redhat.com/browse/KOGITO-8716)

Thanks

### CODE REVIEW

**Review by romartin — APPROVED** [review]
It looks good @handreyrc !! Thanks for this fix!

BTW @LuboTerifaj could you please prioritize this ticket? We are planning to merge this into the prerelease branch as soon as possible, and then we'll start the sanity tests. It means we cannot start until this completed.

BTW @handreyrc once merging this to master, let's please do the cherry-pick to the `0.27.0-prerelease` branch. Thanks!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

I tested also other scenarios than kogito and specifction examples and unfortunately I found the following issues.

- If there is incoming connection from the lower level to the level up node, the transition is going through state to the one more level up.
through-level-above

- If there are multiple nodes on the same level, the connection may go through the node on level above, depending where are the nodes placed.
through-level-above-2

**Source** for both issues above:

<details><summary>loanbroker-edited.sw.json</summary>

```
{
  "id": "loanbroker",
  "name": "loanbroker",
  "specVersion": "0.8",
  "start": "GetCreditScore",
  "dataInputSchema": "loanbroker.schema.json",
  "functions": [
    {
      "name": "getCreditScore",
      "operation": "specs/credit-bureau.yaml#getCustomerCreditScore",
      "type": "rest"
    },
    {
      "name": "fetchQuotes",
      "operation": "specs/aggregator.yaml#fetchQuotesByInstance",
      "type": "rest"
    }
  ],
  "events": [
    {
      "name": "requestQuote",
      "type": "kogito.serverless.workflow.request.quote",
      "kind": "produced"
    },
    {
      "name": "aggregatedQuotesResponse",
      "type": "kogito.serverless.loanbroker.aggregated.quotes.response",
      "kind": "consumed",
      "source": "/kogito/serverless/loanbroker/aggregator"
    },
    {
      "name": "loanBrokerRequestedQuotes",
      "type": "kogito.serverless.workflow.aggregated.quotes",
      "kind": "produced"
    },
    {
      "name": "loanBrokerRequestedQuotesTimeout",
      "type": "kogito.serverless.workflow.aggregated.quotes.timeout",
      "kind": "produced"
    }
  ],
  "states": [
    {
      "name": "GetCreditScore",
      "type": "operation",
      "actions": [
        {
          "functionRef": {
            "refName": "getCreditScore",
            "arguments": {
              "SSN": "${ .SSN }"
            }
          },
          "actionDataFilter": {
            "toStateData": "${ .credit }"
          }
        }
      ],
      "stateDataFilter": {
        "output": "${ {  amount, term, credit } }"
      },
      "transition": "RequestQuote"
    },
    {
      "name": "RequestQuote",
      "type": "callback",
      "action": {
        "eventRef": {
          "triggerEventRef": "requestQuote"
        }
      },
      "eventRef": "aggregatedQuotesResponse",
      "eventDataFilter": {
        "data": "${ {\"aggregatedQuotesArrived\" : true} }"
      },
      "transition": "CheckRequestQuoteArrived",
      "timeouts": {
        "eventTimeout": "PT10S"
      }
    },
    {
      "name": "CheckRequestQuoteArrived",
      "type": "switch",      
      "dataConditions": [
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "FetchQuotes"
        },
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "GetCreditScore"
        },
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "CheckRequestQuoteArrived2"
        },
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "CheckRequestQuoteArrived3"
        },
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "CheckRequestQuoteArrived4"
        }
      ],      
      "defaultCondition": {
        "end": {
          "produceEvents": [
            {
              "eventRef": "loanBrokerRequestedQuotesTimeout"
            }
          ],
          "terminate": true
        }
      }      
    },
    {
      "name": "CheckRequestQuoteArrived2",
      "type": "switch",
      "dataConditions": [
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "FetchQuotes"
        }
      ],
      "defaultCondition": {
        "end": {
          "produceEvents": [
            {
              "eventRef": "loanBrokerRequestedQuotesTimeout"
            }
          ],
          "terminate": true
        }
      }
    },
    {
      "name": "CheckRequestQuoteArrived3",
      "type": "switch",
      "dataConditions": [
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "FetchQuotes"
        },
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "XState"
        }
      ],
      "defaultCondition": {
        "end": {
          "produceEvents": [
            {
              "eventRef": "loanBrokerRequestedQuotesTimeout"
            }
          ],
          "terminate": true
        }
      }
    },
    {
      "name": "XState",
      "type": "inject",
      "data": {
         "result": "Hello World!"
      }
    },
    {
      "name": "CheckRequestQuoteArrived4",
      "type": "switch",
      "dataConditions": [
        {
          "condition": "${ .aggregatedQuotesArrived }",
          "transition": "FetchQuotes"
        }
      ],
      "defaultCondition": {
        "end": {
          "produceEvents": [
            {
              "eventRef": "loanBrokerRequestedQuotesTimeout"
            }
          ],
          "terminate": true
        }
      }
    },
    {
      "name": "FetchQuotes",
      "type": "operation",
      "actions": [
        {
          "functionRef": {
            "refName": "fetchQuotes",
            "arguments": {
              "id": "$WORKFLOW.instanceId"
            }
          },
          "actionDataFilter": {
            "toStateData": "${ .quotes }"
          }
        }
      ],
      "transition": "RequestQuote",
      "end": {
        "produceEvents": [
          {
            "eventRef": "loanBrokerRequestedQuotes"
          }
        ],
        "terminate": true
      }
    }
  ]
}
```
</details>

___
	
- Connection may go also through neighbour node:
neighbour

  - **Source** for the issue:
 
<details><summary>order-saga-error-handling-edited.sw.json</summary>

```
{
  "id": "order_saga_error_workflow",
  "version": "1.0",
  "name": "Order Fulfilment Workflow Saga example",
  "description": "An example of how to implement Saga for the Order Fulfilment example using Error Handling and Compensation",
  "errors" : [
    {
      "name" : "reserve stock failed",
      "code": "org.kie.kogito.ServiceException"
    },
    {
      "name": "process payment failed",
      "code": "org.kie.kogito.ServiceException"
    },
    {
      "name": "shipping failed",
      "code": "org.kie.kogito.ServiceException"
    }
    
  ],
  "start": "reserveStock",
  "functions": [
    {
      "name": "reserveStock",
      "type": "custom",
      "operation": "service:org.kie.kogito.StockService::reserveStock"
    },
    {
      "name": "cancelStock",
       "type": "custom",
      "operation": "service:org.kie.kogito.StockService::cancelStock"
    },
    {
      "name": "processPayment",
      "type": "custom",
      "operation": "service:org.kie.kogito.PaymentService::processPayment"
    },
    {
      "name": "cancelPayment",
      "type": "custom",
      "operation": "service:org.kie.kogito.PaymentService::cancelPayment"
    },
    {
      "name": "scheduleShipping",
      "type": "custom",
      "operation": "service:org.kie.kogito.ShippingService::scheduleShipping"
    },
    {
      "name": "cancelShipping",
      "type": "custom",
      "operation": "service:org.kie.kogito.ShippingService::cancelShipping"
    },
    {
      "name": "orderSuccess",
      "type": "custom",
      "operation": "service:org.kie.kogito.OrderService::success"
    },
    {
      "name": "orderFailure",
      "type": "custom",
      "operation": "service:org.kie.kogito.OrderService::failure"
    },
    {
      "name": "log",
      "type": "custom",
      "operation": "sysout"
    }
  ],
  "states": [
    {
      "name": "reserveStock",
      "type": "operation",
      "actions": [
        {
          "name": "reserveStockAction",
          "functionRef": {
            "refName": "reserveStock",
            "arguments": {
              "orderId": ".orderId",
              "failService": ".failService"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".stockResponse"
          }
        }
      ],
      "transition": "processPayment",
      "compensatedBy": "CancelStock",
      "onErrors": [
        {
          "errorRef": "reserve stock failed",
          "transition": "ServiceError"
        }
      ]
    },
    {
      "name": "processPayment",
      "type": "operation",
      "actions": [
        {
          "name": "processPaymentAction",
          "functionRef": {
            "refName": "processPayment",
            "arguments": {
              "orderId": ".orderId",
              "failService": ".failService"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".paymentResponse"
          }
        }
      ],
      "transition": "scheduleShipping",
      "compensatedBy": "CancelPayment",
      "onErrors": [
        {
          "errorRef": "process payment failed",
          "transition": "ServiceError"
        }
      ]
    },
    {
      "name": "scheduleShipping",
      "type": "operation",
      "actions": [
        {
          "name": "scheduleShippingAction",
          "functionRef": {
            "refName": "scheduleShipping",
            "arguments": {
              "orderId": ".orderId",
              "failService": ".failService"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".shippingResponse"
          }
        }
      ],
      "transition": "CompleteOrder",
      "compensatedBy": "CancelShipping",
      "onErrors": [
        {
          "errorRef": "shipping failed",
          "transition": "ServiceError"
        }
      ]
    },
    {
      "name": "ServiceError",
      "type": "inject",
      "data": {},
      "transition": {
        "nextState": "FailedOrder",
        "compensate": true
      }
    },
    {
      "name": "CancelStock",
      "usedForCompensation": true,
      "type": "operation",
      "actions": [
        {
          "name": "cancelStockAction",
          "functionRef": {
            "refName": "cancelStock",
            "arguments": {
              "stockId": ".stockResponse.resourceId"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".cancelStockResponse"
          }
        }
      ]
    },
    {
      "name": "CancelPayment",
      "usedForCompensation": true,
      "type": "operation",
      "actions": [
        {
          "name": "cancelPaymentAction",
          "functionRef": {
            "refName": "cancelPayment",
            "arguments": {
              "paymentId": ".paymentResponse.resourceId"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".cancelPaymentResponse"
          }
        }
      ]
    },
    {
      "name": "CancelShipping",
      "usedForCompensation": true,
      "type": "operation",
      "actions": [
        {
          "name": "cancelShippingAction",
          "functionRef": {
            "refName": "cancelShipping",
            "arguments": {
              "shippingId": ".shippingResponse.resourceId"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".cancelShippingResponse"
          }
        }
      ]
    },
    {
      "name": "FailedOrder",
      "type": "operation",
      "actions": [
        {
          "name": "orderFailureAction",
          "functionRef": {
            "refName": "orderFailure",
            "arguments": {
              "orderId": ".orderId"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".orderResponse"
          }
        }
      ],
      "end": {
        "terminate": "true"
      }
    },
    {
      "name": "CompleteOrder",
      "type": "operation",
      "actions": [
        {
          "name": "orderSuccessAction",
          "functionRef": {
            "refName": "orderSuccess",
            "arguments": {
              "orderId": ".orderId"
            }
          },
          "actionDataFilter": {
            "results": ".",
            "toStateData": ".orderResponse"
          }
        }
      ],
      "transition": "processPayment",
      "end": {
        "terminate": "true"
      }
    }
  ]
}
```
</details>

___	

- It may happen the connection is going through the level up node even if there are not incoming connections from the lower level.  
  - Add `"transition": "scheduleShipping"` to `FailedOrder` state in the order-saga-error-handling-edited.sw.json example above and see the diagram.
through-level-above-3        
        
- The transitions may have redundant parts. For example:
  - Change transition from `FetchQuotes` state to `GetCreditScore` state in the loanbroker-edited.sw.json example above and see the diagram.
redundant-parts-1


Note, there might also other scenarios with similar issues, but it is not possible to test and list them all here.

Thanks!

**Comment by handreyrc** [comment]
Hey @LuboTerifaj  and @romartin;

Good catch @LuboTerifaj! 
We were not handling cases where the backwards transition should come from center magnet instead of right/left magnet.  

All the edge cases reported above are fixed.

We are ready for another round!

Thank you guys.

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @handreyrc ,

Unfortunately the issue is not fixed.

Consider  the following scenario:

monitor-job-edited-through-state-2


<details><summary>monitor-job-edited-to-showcase-diagram-issue.sw.json</summary>

```
{
  "id": "jobmonitoring",
  "version": "1.0",
  "specVersion": "0.8",
  "name": "Job Monitoring",
  "description": "Monitor finished execution of a submitted job",
  "start": "SubmitJob",
  "functions": [
    {
      "name": "submitJob",
      "operation": "http://myapis.org/monitorapi.json#doSubmit"
    },
    {
      "name": "checkJobStatus",
      "operation": "http://myapis.org/monitorapi.json#checkStatus"
    },
    {
      "name": "reportJobSuceeded",
      "operation": "http://myapis.org/monitorapi.json#reportSucceeded"
    },
    {
      "name": "reportJobFailed",
      "operation": "http://myapis.org/monitorapi.json#reportFailure"
    }
  ],
  "states":[
    {
      "name":"SubmitJob",
      "type":"operation",
      "actionMode":"sequential",
      "actions":[
      {
          "functionRef": {
            "refName": "submitJob",
            "arguments": {
              "name": "${ .job.name }"
            }
          },
          "actionDataFilter": {
            "results": "${ .jobuid }"
          }
      }
      ],
      "stateDataFilter": {
          "output": "${ .jobuid }"
      },
      "transition": "CheckApplication"
  },  
  {
    "name":"CheckApplication",
    "type":"switch",
    "dataConditions": [
       {
         "condition": "${ .applicants | .age >= 18 }",
         "transition": "GetJobStatus"
       },
       {
         "condition": "${ .applicants | .age < 18 }",
         "transition": "GetJobStatus2"
       }
    ],
    "defaultCondition": {
       "transition": "RejectApplication"
    }
 },
  {
      "name":"GetJobStatus",
      "type":"operation",
      "actionMode":"sequential",
      "actions":[
      {
        "functionRef": {
            "refName": "checkJobStatus",
            "arguments": {
              "name": "${ .jobuid }"
            }
          },
          "actionDataFilter": {
            "results": "${ .jobstatus }"
          }
      }
      ],
      "stateDataFilter": {
          "output": "${ .jobstatus }"
      },
      "transition": "DetermineCompletion"
  },
  {
    "name":"GetJobStatus2",
    "type":"operation",
    "actionMode":"sequential",
    "actions":[
    {
      "functionRef": {
          "refName": "checkJobStatus",
          "arguments": {
            "name": "${ .jobuid }"
          }
        },
        "actionDataFilter": {
          "results": "${ .jobstatus }"
        }
    }
    ],
    "stateDataFilter": {
        "output": "${ .jobstatus }"
    },
    "transition": "DetermineCompletion"
},
  {
    "name":"DetermineCompletion",
    "type":"switch",
    "dataConditions": [
      {
        "condition": "${ .jobStatus == \"SUCCEEDED\" }",
        "transition": "JobSucceeded"
      },
      {
        "condition": "${ .jobStatus == \"FAILED\" }",
        "transition": "JobFailed"
      },
      {
        "condition": "${ .jobStatus == \"FAILED\" }",
        "transition": "CheckApplication"
      }
    ],
    "defaultCondition": {
      "transition": "CheckApplication"
    }
  },
  {
      "name":"JobSucceeded",
      "type":"operation",
      "actionMode":"sequential",
      "actions":[
      {
        "functionRef": {
            "refName": "reportJobSuceeded",
            "arguments": {
              "name": "${ .jobuid }"
            }
        }
      }
      ],
      "end": true
  },
  {
    "name":"JobFailed",
    "type":"operation",
    "actionMode":"sequential",
    "actions":[
    {
        "functionRef": {
          "refName": "reportJobFailed",
          "arguments": {
            "name": "${ .jobuid }"
          }
        }
    }
    ],
    "end": true
  }
  ]
}

```
</details>

In addition, from user perspective, both the source and target magnets selection is not deterministic.
- See example above, sometimes a top/bottom magnet is chosen and sometimes east/est magnet is chosen.
- You can compare this example with loan-broker-edited.sw.json example from my previous [pullrequestreview-1311368508]( https://github.com/kiegroup/kie-tools/pull/1476#pullrequestreview-1311368508).

Thanks!

**Review by LuboTerifaj — APPROVED** [review]
Hey @handreyrc , @romartin ,

as we discussed on chat. I am okay with merging this PR as it basically doesn't introduce any regressions, but it fixes certain scenarios.

However, note the issue is still present.

I am about to upload the testing scenario to both jiras: https://issues.redhat.com/browse/KOGITO-8716 and https://issues.redhat.com/browse/KOGITO-8683

Thanks!

**Comment by LuboTerifaj** [comment]
Hey @handreyrc , @romartin , I decided to report a separate jira for that: https://issues.redhat.com/browse/KOGITO-8755

**Comment by romartin** [comment]
thanks @LuboTerifaj !

**Pull request merged**
