### PR TITLE
KOGITO-6962: Nightlies: Reorganize folder struct and job generation

### PR DESCRIPTION
**Pull request by radtriste**
https://issues.redhat.com/browse/KOGITO-6962

Depends on https://github.com/kiegroup/kogito-pipelines/pull/416

### CODE REVIEW

**Comment by tiagobento** [comment]
Hi @radtriste! Thanks for the PR. Can you please give us a little bit more context on what you're working on?

**Comment by radtriste** [comment]
@tiagobento everything is on the dependent PR: https://github.com/kiegroup/kogito-pipelines/pull/416

This is a global Kogito job reorganization and DSL improvements, and mainly impacting the Kogito Runtimes part.
It should not impact the current tooling jobs. But some common classes have been redesigned, hence the change here to keep the compatibility.

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
jenkins retest this

**Comment by radtriste** [comment]
@tiagobento why `CodeQL / Analyze (java)` is failing ?

**Comment by radtriste** [comment]
btw @tiagobento could you approve this one ?

**Comment by tiagobento** [comment]
Hi @radtriste! We're already investigating why `CodeQL / Analyze (java)` is failing. For now, let's ignore it. 

Regarding `CI :: Monorepo (full)`, you have formatting issues. This can be easily solved by running `yarn format` at the root of the repository.

**Comment by radtriste** [comment]
jenkins failure is expected

**Comment by radtriste** [comment]
jenkins retest this

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
