### PR TITLE
Editors bump for 7.46.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by ederign**

### CODE REVIEW

**Comment by tiagobento** [comment]
@ederign I'd say something's not right with this version yet because our VS Code extension size dropped from ~20mb to ~7mb.

**Comment by ederign** [comment]
@tiagobento let's wait until tomorrow and fire again

**Comment by romartin** [comment]
I'm also waiting for this guys... xD

**Comment by tiagobento** [comment]
@ederign @romartin No luck yet.

**Comment by tiagobento** [comment]
@ederign @romartin Just tested locally and the WARs coming from Maven at 7.46.0-SNAPSHOT seem to not have the GWT bundles. It's like GWT compilation was skipped there. The FDB works fine here, though, as we build every repos during the CI job.

@mbiarnes Do you know if something changed that may be causing this?

**Comment by tiagobento** [comment]
@ederign @romartin Looks like time has fixed that :) Merging.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
