### PR TITLE
NO-ISSUE: Rename findings of it tests to e2e tests

### PR DESCRIPTION
**Pull request by tomasdavidorg**
There are some more it tests strings which should be replaced to e2e.

### CODE REVIEW

**Comment by zdrapela** [comment]
Hi, I found some remnants of it-tests in `chrome-extension-pack-kogito-kie-editors`. There is `packages/chrome-extension-pack-kogito-kie-editors/it-tests/samples/` folder that is hard coded in some of the packages in the test files of  `chrome-extension-pack-kogito-kie-editors`. It probably should be also renamed to `e2e-tests` So please check that.

**Review by zdrapela — COMMENTED** [review]
This is probably fine? https://github.com/tomasdavidorg/kie-tools/blob/cd4cb514488d4f3e30d9149c2000d59f60ea72b4/packages/serverless-workflow-vscode-extension/e2e-tests/resources/greeting-flow/pom.xml#L8C44-L8C44

**Comment by tomasdavidorg** [comment]
> Hi, I found some remnants of it-tests in `chrome-extension-pack-kogito-kie-editors`. There is `packages/chrome-extension-pack-kogito-kie-editors/it-tests/samples/` folder that is hard coded in some of the packages in the test files of `chrome-extension-pack-kogito-kie-editors`. It probably should be also renamed to `e2e-tests` So please check that.

Thanks for the findings, I missed them... These changes will break the CI check, I will first wait to be the CI green and then I will push the changes.

**Comment by zdrapela** [comment]
Ok, cool. 

I just found another thing. We need to do the following replacements:
- `it_tests` -> `e2e_tests` because of kn-plugin-workflow build tags (for some reason it was changed in `package.json`, but not in the test files) and this results in not running the tests at all.
- `IT_TESTS` -> `E2E_TESTS` to rename some constants in the test files.

**Comment by tomasdavidorg** [comment]
Build was green. @zdrapela I pushed the other changes. Please take a look.

**Review by zdrapela — APPROVED** [review]
Looking good now. Thanks!

**Comment by ljmotta** [comment]
Hi @tomasdavidorg @zdrapela ! It looks like I've missed a few of the "it" references in my last PR! Sorry about that.

Just a heads up, I didn't make the change on the `chrome-extension` packages as they point to a URL in the main branch which doesn't exist until the PR is merged. e.g. `blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.bpmn` will only exist after a PR is merged with the new e2e-tests folder. As the e2e-tests folder doesn't exist in the main branch, the tests will not pass. I couldn't figure out a simple way to fix this problem so I didn't make the change.

**Comment by zdrapela** [comment]
> Just a heads up, I didn't make the change on the `chrome-extension` packages as they point to a URL in the main branch which doesn't exist until the PR is merged. e.g. `blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/samples/test.bpmn` will only exist after a PR is merged with the new e2e-tests folder. As the e2e-tests folder doesn't exist in the main branch, the tests will not pass. I couldn't figure out a simple way to fix this problem so I didn't make the change.

Yes, that is tricky. I can only think of making two PRs - one that would copy the files to `e2e-tests/samples` and another one that would remove them from `it-tests/samples` and reference the files from `e2e-tests/samples` after the first PR is merged.

**Comment by tomasdavidorg** [comment]
@zdrapela @ljmotta please take a look on https://github.com/kiegroup/kie-tools/pull/1998. After that PR is merged, I will update this one. So tests can pass.

**Comment by caponetto** [comment]
https://github.com/kiegroup/kie-tools/pull/1998 is merged. Let's move forward with this one please.

**Comment by tomasdavidorg** [comment]
@caponetto @ljmotta I rebased the branch with the main. It should be ready to merge when CI is green.

**Review by caponetto — APPROVED** [review]
Thanks @tomasdavidorg!

**Review by ljmotta — APPROVED** [review]
@tomasdavidorg Thanks!

**Pull request merged**
