### PR TITLE
KOGITO-2926: Provide `readOnly` property on EditorContext

### PR DESCRIPTION
**Pull request by tiagobento**
See https://issues.redhat.com/browse/KOGITO-2926

### CODE REVIEW

**Comment by manstis** [comment]
I was looking for this side of the DMN work today :-)

**Comment by tiagobento** [comment]
I'll wait for #258 to be merged so I can change the default undo/redo shortcuts to only be registered if not in readonly mode.

**Comment by tiagobento** [comment]
This PR is ready for review @tomasdavidorg @paulovmr. Please use the Chrome Extension from our Full Downstream build artifacts to test the Readonly mode. 

Examples:
--
READONLY -> https://github.com/tiagobento/KieDora/blob/master/Drawing%201-3.dmn
READONLY -> https://github.com/tiagobento/KieDora/pull/1/files
NOT READONLY -> https://github.com/tiagobento/KieDora/edit/master/Drawing%201-3.dmn

**Review by paulovmr — APPROVED** [review]
Not related to this PR, but in read-only mode, this file has a different arrow position:
READONLY -> https://github.com/tiagobento/KieDora/blob/master/Drawing%201-3.dmn
NOT READONLY -> https://github.com/tiagobento/KieDora/edit/master/Drawing%201-3.dmn

@karreiro could you check that in the DMN editor please?

**Comment by tomasdavidorg** [comment]
@tiagobento Is this read-only mode only for DMN? Should it also work for BPMN?

**Comment by tiagobento** [comment]
@tomasdavidorg Yes. BPMN doesn't support 'readonly' yet.

**Review by tomasdavidorg — COMMENTED** [review]
If the different arrow position issue is not related to this PR, I can approve this but for me it looks like it is caused by the read-only mode.

Feel free to merge this if it is not related and the issue is reported. :slightly_smiling_face:

**Comment by karreiro** [comment]
@paulovmr @tomasdavidorg I confirm this is an issue in the editor side. I've raised a JIRA for that: https://issues.redhat.com/browse/KOGITO-3274

**Pull request merged**
