### PR TITLE
kie-issues#1210: Adjust CI to dockerhub repos and images

### LINKED ISSUE #1216: Release kie-tools-ci-build image as docker.io/apache/incubator-kie-tools-ci-build

### PR DESCRIPTION
**Pull request by rodrigonull**
Closes: https://github.com/apache/incubator-kie-issues/issues/1216, https://github.com/apache/incubator-kie-issues/issues/1218, https://github.com/apache/incubator-kie-issues/issues/1219

This PR updates the CI Jenkins jobs to publish KIE Tools images to docker.io.

### CODE REVIEW

**Comment by tiagobento** [comment]
@rodrigonull @thiagoelg is preparing a PR renaming the packages and some other stuff, but I think we can safely merge this one before that lands, WDYT?

**Comment by rodrigonull** [comment]
@tiagobento we still need to wait for the dockerhub credentials and I also need to update this PR to stop using the `*-nightly` image names before we can merge it.

**Comment by tiagobento** [comment]
How do we coordinate this PR with
- https://github.com/apache/incubator-kie-tools/pull/2342

?

**Comment by thiagoelg** [comment]
> How do we coordinate this PR with
> 
> * [kie-issues#1230: Rename kie-tools images from quay.io/kie-tools to docker.io/apache/incubator-kie-* #2342](https://github.com/apache/incubator-kie-tools/pull/2342)
> 
> ?

The #2342 PR already sets the environment variables on the Jenkisnfiles, so I think we can revert them on this PR (some variables were changed and will conflict with this PR as is).
Everything else should be fine and once #2342 is merged this can be merged as well.

**Comment by tiagobento** [comment]
So what do we do? Merge what PR first?

**Comment by thiagoelg** [comment]
> So what do we do? Merge what PR first?

#2342 (as soon as we figure out the sonataflow-operator stuff)

**Comment by tiagobento** [comment]
Closing in favor of
- #2364

**Pull request closed without merging**
