### PR TITLE
KOGITO-9929: Filter and Timeout Tooltips show null instead of undefined

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.redhat.com/browse/KOGITO-9929

### CODE REVIEW

**Review by handreyrc — CHANGES_REQUESTED** [review]
Hey @treblereel,

I noticed there are more cases involving the null. It is the same issue in other places.
Check the Operation state and Parallel state  if you have the following properties defined as below:
 - "actions": [{}]
 - "functionRef": {}
 
Maybe it's an oportunity to check all the information we are presenting from Icon's tooltips,  we may find more similar cases.

Please, could you take a look at those as well?

Thanks!

**Comment by treblereel** [comment]
> Hey @treblereel,
> 
> I noticed there are more cases involving the null. It is the same issue in other places. Check the Operation state and Parallel state if you have the following properties defined as below:
> 
> * "actions": [{}]
> * "functionRef": {}
> 
> Maybe it's an oportunity to check all the information we are presenting from Icon's tooltips, we may find more similar cases.
> 
> Please, could you take a look at those as well?
> 
> Thanks!

In case we have multiple 'null' messages instead of 'undefined', we should rework our rendering. Otherwise, our models will be flooded with Js.undefined() checks, which isn't great.

@LuboTerifaj What do you think?

**Comment by LuboTerifaj** [comment]
Hello @handreyrc , [KOGITO-9929](https://issues.redhat.com/browse/KOGITO-9929) is caused by [KOGITO-9831](https://issues.redhat.com/browse/KOGITO-9831). The issues you are mentioning were also present on main before. It may be beneficial to go through all icons and identify potential issues. However, I would report it in a separate jiras. There are already some issues reported, for example: [KOGITO-8762](https://issues.redhat.com/browse/KOGITO-8762), so we might want to revisit it, and decide what should be, or what shouldn't be shown in the diagram.

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @treblereel ,

There is still null shown in some places within filters and timeouts:

- In stateDataFilter: `output: null`	
- In timeouts: 
  - `EventTimeout: null`
  - `ActionExecTimeout: null`

Could you please have a look at it?

Thanks!

**Comment by LuboTerifaj** [comment]
Hello @treblereel , regarding rework of rendering I agree. See my [comment](https://github.com/kiegroup/kie-tools/pull/2044#issuecomment-1825496952) above. The current fix looks more like a temporary solution for [KOGITO-9929](https://issues.redhat.com/browse/KOGITO-9929) regression.

**Review by LuboTerifaj — APPROVED** [review]
Hello @treblereel , the fix looks good to me. Thanks!

**Review by handreyrc — APPROVED** [review]
Hey @treblereel and @LuboTerifaj ,

It looks good to me as well lets move forward with it!

Thanks!

**Pull request merged**
