### PR TITLE
KOGITO-5012: VSCode IT tests are not showing test ouput in console

### PR DESCRIPTION
**Pull request by domhanak**
@tiagobento I think we misunderstood each other last time we were discussing this. So I am removing the retries and reporter to show the logs in console. The output is still generated even without reporter specified. Default one is used :)

### CODE REVIEW

**Comment by domhanak** [comment]
FDB failed on appformer, please rebuild it.

**Comment by tiagobento** [comment]
@domhanak Hi! Nice PR. Can you also remove the dependency from `package.json`? I don't think it's used anymore after removing the reporter.

**Comment by domhanak** [comment]
@tiagobento I checked and the dependency is still needed to produce the output file that we upload. 
Let's merge this as-is.

**Comment by domhanak** [comment]
Created JIRA for tracking: https://issues.redhat.com/browse/KOGITO-5012

Desktop test fail on mac-os but these are unrelated to changes in this PR.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
