### PR TITLE
Fix bpmn test after readonly change

### PR DESCRIPTION
**Pull request by tomasdavidorg**
This PR should be merge after #471

### CODE REVIEW

**Comment by domhanak** [comment]
@caponetto This is related to the chrome-ext it-tests failing with 7.52

**Review by domhanak — APPROVED** [review]
Thanks @tomasdavidorg for adding the visibility check! LGTM!

**Review by ederign — APPROVED** [review]
LGMT, @caponetto can you please take a look? I've retrigger the CI

**Review by caponetto — APPROVED** [review]
LGTM. Let's wait for a green build on the chrome extension it-tests.

**Comment by tomasdavidorg** [comment]
Chrome extensions it-tests are green 🟢.

**Pull request merged**
