### PR TITLE
Skip GWT compiler in `lienzo-webapp` for yarn builds

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by jomarko** [comment]
@tiagobento @romartin hello, just a friendly reminder, if you have a moment to review this PR.

**Review by yesamer — APPROVED** [review]

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Thanks @jomarko for this.
I understand then you'll guys change the CI scripts to run with the profile `no-showcase` enabled, right? As I see it's not enbabled by default during the build.
Once confirming, please let me know and I can merge!
Thanks!

**Comment by jomarko** [comment]
@romartin not sure I understand your question

it is used already:

```
packages/stunner-editors/package.json:    "build:dev:linux:darwin": "mvn clean install -DskipTests -DskipITs -Pno-showcase && yarn dist",
packages/stunner-editors/package.json:    "build:dev:win32": "yarn powershell mvn clean install `-DskipTests `-DskipITs `-Pno-showcase && yarn dist",
packages/stunner-editors/package.json:    "build:prod:linux:darwin": "yarn lint && mvn clean install -DskipTests=$(build-env global.build.test --not) -DskipITs -Pno-showcase && yarn dist",
packages/stunner-editors/package.json:    "build:prod:win32": "yarn lint && yarn powershell mvn clean install `-DskipTests=$(build-env global.build.test --not) `-DskipITs `-Pno-showcase && yarn dist",
```

**Comment by romartin** [comment]
ok thanks for clarification @jomarko !

**Pull request merged**
