### PR TITLE
KOGITO-7196: SWF Viewer - Replace reset viewport button by autofit

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR?

### CODE REVIEW

**Review by romartin — APPROVED** [review]
Thanks @inodeman , looks good to me!

**Comment by romartin** [comment]
hey @domhanak , do you want to take a look at this? Thx in advance!

**Review by domhanak — CHANGES_REQUESTED** [review]
HI @inodeman @romartin I noticed an issue with this. Here is my review.

**Use cases**

- Button is there and does what it should do but the action is not working properly 100% of the time. See third point.
- When I use the autofit button without moving the scrollbars everything works nicely.
- When I use the autofit button when I move the scrollbars first the autofit, fits the image into wrong place. See picture:
Screenshot from 2022-06-01 10-06-23

**Here are the steps to reproduce:**
1. Open the `Event Based Switch Example`
2. Zoom in using the widget so that you can move the scrollbars (both or one, issue happens in both cases)
3. Move the Scrollbars into different position. ( I move the all the way to the right in the screenshot)
4. Use autofit
5. Notice the image not centered and fitted.

**Expected results**
The scrollbars are also reset into initial position & image is fitted properly.

I also noticed that the canvas can not be navigated using mouse and I can only use the scrollbars, let me know what is the plan about this. I think it should be reported for enhancing later.

**Comment by romartin** [comment]
thanks for the feedback @domhanak , good catches. ( Hopefully we'll be able to automate all those checks sooner than later, right? hehe :) )

Please @inodeman waiting for your answers or fixes too :)

Thanks guys

**Comment by inodeman** [comment]
Hi @domhanak @romartin looking into it, should have a fix soon

**Comment by inodeman** [comment]
Hi @domhanak @romartin fixed the issue about Scrollbars not resetting, about the issue about not being able to navigate using the mouse I think that will have to be another issue/discussion, let me know what you think

**Review by domhanak — APPROVED** [review]
Thanks, LGTM now :smile:

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
