### PR TITLE
AF-2209: Remove yarn.lock files from kiegroup projects

### PR DESCRIPTION
**Pull request by tiagobento**
See description on JIRA.

Related:
https://github.com/kiegroup/appformer/pull/813
https://github.com/kiegroup/kie-wb-common/pull/2933
https://github.com/kiegroup/kogito-tooling/pull/20

### CODE REVIEW

**Review by domhanak — CHANGES_REQUESTED** [review]
Should we also add the file to `.gitignore`?

**Comment by tiagobento** [comment]
@domhanak It's already there https://github.com/kiegroup/kogito-tooling/blob/master/.gitignore#L9

**Review by domhanak — APPROVED** [review]

**Comment by domhanak** [comment]
@mareknovotny ok to merge

**Comment by tiagobento** [comment]
@mareknovotny Are we good to merge this one?

**Comment by mareknovotny** [comment]
yep, I don't have anything against merging ;)

**Review by mareknovotny — APPROVED** [review]

**Pull request merged**
