### PR TITLE
kie-issues#38: Download .HTML file Button in Documentation doesn't work

### LINKED ISSUE #38: DMN Editor: `Download .HTML file` Button in Documentation doesn't work
**Step to reproduce:**

- Open any DMN File with DMN Editor
- Enter into "Documentation" tab
- Try to click on the `Download .HTML file` button. Nothing happens 
- Additionally this button is not enabled in VSCode

**Expected behavior**
A HTML file should be downloaded after clicking the button

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/kiegroup/kie-issues/issues/38

In this PR I restored the `Download .HTML file button` in ALL the channels.
In addition, I added some minor improvements to the generated HTML file (eg. no more static year in the file, added a title, and removed unused fields).
I updated the style of the buttons as well, using the PatternFly 4 style.

Plain editor:
Screenshot 2022-11-25 at 12 11 19

VSCode version (Print button not supported: we need to integrate that with VSCode API)
Screenshot 2022-11-25 at 12 10 31

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Review by jomarko — COMMENTED** [review]
Thank you @yesamer for these changes. I think a little bit more cleanup can be done as part of this PR https://github.com/yesamer/kie-tools/pull/3. Please have a look and let me know.

**Comment by yesamer** [comment]
@jomarko Thank you! Consider that `DMNDocumentationViewButtonsVisibilitySupplier` is still used because we want to hide the Print button only in VsCode

--> https://github.com/kiegroup/kie-tools/pull/1348/files#diff-e3a229a5a5256a74cd6264023fa4fea58600302c0bc9faf01aee4e6ed0c0553aR82

**Comment by jomarko** [comment]
@yesamer thank you. I closed https://github.com/yesamer/kie-tools/pull/3. However, please, update alternatives properties file please.

**Comment by yesamer** [comment]
@jomarko Sure, thank you, I totally forgot that file existence :D

**Review by jomarko — APPROVED** [review]
Thank you @yesamer

**Pull request merged**
