### PR TITLE
Fix Cypress performance issues by downgrading the version

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://issues.redhat.com/browse/KOGITO-4906

If https://github.com/kiegroup/kogito-tooling/pull/474 is merged sooner. This PR needs to be updated.

### CODE REVIEW

**Comment by jomarko** [comment]
Do we have this video turned off for chrome tests already? asking as chrome-extension tests failed on WIN.

**Comment by tomasdavidorg** [comment]
@jomarko There is no video recording for chrome tests. For the cypress tests see my comment in https://issues.redhat.com/browse/KOGITO-4906?focusedCommentId=16060655&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-16060655

**Comment by tomasdavidorg** [comment]
@jomarko The windows fails look like random issues. Retriggering the build.

**Comment by jomarko** [comment]
@tomasdavidorg sorry for and inconvenience, I didn't realize chrome-extension tests are not cypress tests. Thank you for investigation. No comments from my site.

**Review by jomarko — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
Please do not merge before #474 is merged, I will update this PR then.

**Review by paulovmr — APPROVED** [review]

**Review by jstastny-cz — APPROVED** [review]
LGTM.

**Comment by tomasdavidorg** [comment]
@ederign @paulovmr Could you please merge? The Chrome tests on MacOS are not relevant (Chrome was upgraded during running the test by the system - driver is not compatible with the new Chrome version - this will be fixed when github actions machines will be updated to the new Chrome / Chrome driver version).

**Review by ederign — APPROVED** [review]

**Pull request merged**
