### PR TITLE
KOGITO-4137: Update Patternfly to version 4.70.2

### PR DESCRIPTION
**Pull request by ljmotta**
## Task
https://issues.redhat.com/browse/KOGITO-4137

### CODE REVIEW

**Comment by ljmotta** [comment]
@manstis  I still couldn't fix the safari loading screen as proposed on the https://github.com/kiegroup/kogito-tooling/pull/326 , so I've created a separate PR to just update the PF version. This way, we're going to have it on master as soon as possible.

**Review by tiagobento — APPROVED** [review]

**Comment by ederign** [comment]
@tiagobento can we wait to merge this after 0.8.2?

**Review by ederign — APPROVED** [review]

**Comment by tiagobento** [comment]
@ederign Sure.

**Comment by manstis** [comment]
@kelvah FYI

**Review by jstastny-cz — APPROVED** [review]
OUIA related changes come from introducing OUIA to new components (article) and changing the way how OUIA component ids are generated if not specified. Looks good.

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
