### PR TITLE
Productization build script

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]
LGTM! The idea is that our productisation environment will have this `MVN_SETTINGS_PATH` environment variable configured before running `yarn build:productization` on the root of this repo, correct?

Also, will the full script be commited here on this repo as well?

**Comment by tiagobento** [comment]
@Ginxo Can we combine #314 and this one?

**Comment by Ginxo** [comment]
I would adapt https://github.com/kiegroup/kogito-tooling/pull/314 after we merge this one @tiagobento if you don't mind

**Comment by tiagobento** [comment]
@Ginxo Ok, that's fine for me :)

**Review by antncl — APPROVED** [review]

**Comment by Ginxo** [comment]
@ederign @caponetto could you please check? This is blocking productization thanks.

**Review by caponetto — APPROVED** [review]
LGTM

**Comment by Ginxo** [comment]
could any of you please merge it? thanks

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
