### PR TITLE
KOGITO-7670: Impossible to set image-registry and image-name in kn workflow build

### PR DESCRIPTION
**Pull request by cimbalek**
fix viper keys naming

### CODE REVIEW

**Review by ljmotta — APPROVED** [review]
@cimbalek Thanks for this PR! Good catch.

**Comment by tiagobento** [comment]
Jenkins please retest this.

**Comment by cimbalek** [comment]
@ljmotta should I cherrypick to anywhere? I'm sorry for a possibly stupid question, I'm completely new to this.

**Comment by ljmotta** [comment]
@cimbalek  I'm not sure if I understood. It's already merged in the `main` branch. You can use it by fetching the origin, and rebasing in your local main as follow:
```
git fetch origin
git checkout main
git rebase origin/main
``` 

Or if you wish you could merge/rebase it in any local branch:
```
// in your local branch
git fetch origin
// merge or rebase
git merge origin/main or git rebase origin/main
```

**Comment by ljmotta** [comment]
@cimbalek After thinking a while about what you asked :sweat_smile: , no, you don't need to cherry-pick this fix in any other branch.

**Pull request merged**
