### PR TITLE
KOGITO-734: Remove scroll from pages on both Chrome and Safari

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Comment by manstis** [comment]
I thought you was only targeting Chrome?

If you're targeting Safari too; then surely we'd need to cover that permutation in the GWT editors?

**Comment by tiagobento** [comment]
@manstis I thought Chrome and Safari shared the same 'target' on GWT compilation.. isn't that the case? If it's not, then I think we should have another permutation. cc @ederign @paulovmr

**Comment by manstis** [comment]
@tiagobento Yeah my mistake.. looks like Chrome uses `safari` in it's User Agent.

**Review by ederign — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
Works fine! Thank you @tiagobento

**Pull request merged**
