### PR TITLE
NO-ISSUE: Upgrade Kogito to `999-20241016-SNAPSHOT`

### PR DESCRIPTION
**Pull request by yesamer**

### CODE REVIEW

**Comment by yesamer** [comment]
999-20241016-SNAPSHOT is missing for:
`https://repository.apache.org/content/groups/snapshots/org/kie/kogito/jitexecutor-native-darwin/ `

**Comment by tiagobento** [comment]
I guess we need to run this manually?

**Comment by tiagobento** [comment]
Ok, so the job was executed (https://github.com/apache/incubator-kie-kogito-apps/actions/runs/11374884070) but failed because of `Terminating due to java.lang.OutOfMemoryError: Java heap space`

**Comment by tiagobento** [comment]
https://repository.apache.org/content/repositories/snapshots/org/kie/kogito/jitexecutor-native-darwin/999-20241016-SNAPSHOT/ 😎 Thanks @ljmotta !!!

**Review by tiagobento — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Pull request merged**
