### PR TITLE
Re-include PMML Editor on the excluded packages

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Comment by manstis** [comment]
How does this differ to https://github.com/kiegroup/kogito-tooling/pull/449?

**Comment by manstis** [comment]
Ha, OK stupid question 101. Ignore me.

**Comment by manstis** [comment]
Please let me know when this is merged and I will rebase and add the exclusion to my PR as requested.

**Comment by tiagobento** [comment]
@manstis It's merged.

**Pull request merged**
