### PR TITLE
NO-ISSUE: Misleading forms

### PR DESCRIPTION
**Pull request by Josephblt**
Done:

- Created info icon and tooltip
- Set tooltip content for Collection constraint
- Set tooltip content for Collection item constraint

Final Version
Screenshot from 2024-05-24 06-56-38
Screenshot from 2024-05-24 06-56-42

### CODE REVIEW

**Comment by tiagobento** [comment]
@Josephblt Looks good, now we're just missing the text.. Would be good to have a screenshot of the popups open too.

**Comment by Josephblt** [comment]
Hello @tiagobento, @gitgabrio, @baldimir, @jomarko @yesamer. I would appreciate your opinion on the style of the tooltips.

Here are the two options:
Screenshot from 2024-05-23 14-55-30

1. Blue icon and title.
2. Black icon and tile.

Also, please feel free to suggest any changes in the content of the tooltips or anything else.

**Comment by yesamer** [comment]
Hi @Josephblt,
I like option 1. , but probably option 2. is more consistent with the current editor style. So, I vote for option 2.

I think that having that (aka itemDefinition#allowedValue) it's a technicality not so useful for the end user. I guess nobody will use the xsd as a reference, the goal here is to give a reference for the documentation.

So, I'd change that to `Collection constraint (Type Constraint)` and  `Collection item constraint (Allowed Values)` or similar.

WDYT?

**Comment by gitgabrio** [comment]
I personally agree with @yesamer [comment](https://github.com/apache/incubator-kie-tools/pull/2361#issuecomment-2128645243).

**Comment by Josephblt** [comment]
Hello @yesamer, @gitgabrio. I agree, the blue hints are way nicer but in the end, less is more, and the extra colors are just unnecessary detail. As for the headers I tried to go with a full dev look here. But, just as with the colors, it is a little over the top. Here is the final version with your suggestions.

Screenshot from 2024-05-24 06-56-38
Screenshot from 2024-05-24 06-56-42

**Comment by gitgabrio** [comment]
@Josephblt Fine for me
(side-note: force-push is a gh-smell)

**Review by yesamer — APPROVED** [review]

**Review by klbowers — APPROVED** [review]
LGTM!

**Review by porcelli — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
