### PR TITLE
kie-issues#49: Stunner - Scrolling outside the editing cell closes the Text Editor losing any change

### LINKED ISSUE #49: Stunner: Scrolling outside the editing cell closes the Text Editor losing any change
**Steps to reproduce**
- Open a new DMN file
- Add Decision node
- Add Literal expression (or Decision Table)
- Add 5 lines of text
- Scroll down outside the Literal Expression editing area (or outside the DecisionTable text box area)
#Unexpected: focus and last edited data are lost

**Expected behavior**
- Scrolling outside the editing area should not be losing data

https://issues.redhat.com/browse/KOGITO-5599

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/kiegroup/kie-issues/issues/49

Before:
https://user-images.githubusercontent.com/16005046/208081570-4b789473-8352-4af3-b281-2e8f80c501b4.mov

After:
https://user-images.githubusercontent.com/16005046/208081601-6f3c7458-a0db-4e15-ad02-87cc9e7c7f2e.mov

This PR fixes a very annoying bug that occurs when the user performs a `MouseWheel` event over the GridTable during a cell editing. After that event, any user change is lost. 

To fix it, I simply assigned the same handler used for `MouseDown` event in `DefaultGridLayer` class. That handler flushes (save and close) any opened Cell in the canvas. Note that `flush` method calls the detach method internally, so there's no need to call both `flush` and `destroyResources` methods. 
With this change, is no longer necessary to register a handler for `MouseWheel` in `DMNGridPanel`, thus I removed it.
Unfortunately, the same is not true for Test Scenario: Despite the change applied in `DefaultGridLayer`, Test Scenario still requires registering the handler for `MouseWheel` in `ScenarioGridPanel`. DMN and Scesim have some differences in the panel/grid initialization, so this could explain the difference. 

PR contains code smells fixes as well.

### CODE REVIEW

**Comment by jomarko** [comment]
### DMN Manual checks review

- [x] Confirm changes
- [x] Cancel changes
- [x] Multiple consequent changes
- [x] Switch between multiple expression editors
- [x] Undo
- [x] Monaco editor
- [x] Save file
- [x] Tab, Shift + Tab

### SceSim Manual checks review
- [x] Confirm changes
- [x] Cancel changes
- [x] Multiple consequent changes
- [x] Switch between multiple scesim files
- [x] Undo
- [x] Save file
- [x] Tab, Shift + Tab

**Review by jomarko — APPROVED** [review]
Seems working fine to me. Thank you @yesamer .

**Comment by yesamer** [comment]
@tiagobento Can you please approve this and eventually merge it? Thx

**Comment by yesamer** [comment]
@tiagobento Can you please approve this and eventually merge it? Thx

**Pull request merged**
