### PR TITLE
KOGITO-4104: [DMN Designer] Rename 'Dismiss' to 'Skip tour'

### PR DESCRIPTION
**Pull request by karreiro**
See https://issues.redhat.com/browse/KOGITO-4104

This PR just renamed the "Dismiss" button to "Exit the tour". This was a suggestion from one of our users, and the new label was approved by @lclay2 :-)

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Review by ljmotta — APPROVED** [review]

**Comment by karreiro** [comment]
@jomarko Could you please take a look on this? :-)

**Comment by jomarko** [comment]
@karreiro , it seems there is a new proposal in Jira, 'Skip tour', will you implement it?

**Comment by karreiro** [comment]
@jomarko @ljmotta I've just updated the PR with the suggestion that @lclay2 left in the JIRA yesterday. Could you please have a look on this?

**Comment by jomarko** [comment]
@karreiro sure, sorry for delay, will do it right now.

**Comment by karreiro** [comment]
@jomarko I've applied the rename in the first step of the tour as well. Thank you for the suggestion.

**Review by jomarko — APPROVED** [review]
Thank you @karreiro

**Comment by karreiro** [comment]
(rebasing the branch... 👀)

**Review by yesamer — APPROVED** [review]

**Comment by karreiro** [comment]
@tiagobento May we proceed with the merge of this? :-)

**Pull request merged**
