### PR TITLE
KOGITO-5542: Form Generation CLI: add form config file

### PR DESCRIPTION
**Pull request by pefernan**
Adding companion config file for the forms generated with the CLI. The config file allows the user link external resources (scripts/css) to the form.

### CODE REVIEW

**Comment by tiagobento** [comment]
@pefernan Hi Pere! Some tests are failing, mind to check?

**Comment by pefernan** [comment]
@tiagobento done!

**Comment by tiagobento** [comment]
Hi @pefernan! The first monorepo PR just got merged, do you mind rebasing your branch so that it already runs with the new CI?

**Comment by pefernan** [comment]
@tiagobento done!

**Review by tiagobento — APPROVED** [review]
Great work Pere!

**Pull request merged**
