### PR TITLE
kie-issues#1163: incubator-kie-tools missing header files (Part III)

### LINKED ISSUE #1163: incubator-kie-tools missing header files
Following files has been listed by the RAT tool. Still under the investigation if all of them require license, but some are clearly needed like Java files.

https://gist.github.com/porcelli/69467dc36462fa4a42339e697d50fd59

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/1163

Headers added in:
- All `*.md` files
- All `pom.xml` files
- All `*.properties` files
- All `*.scesim` files
- All `*.bpmn` & *.bpmn2` files
- All `*.pmml` files
- All `*.dmn` files
- All `*.yaml` & `*.yml` 
files
- All `*.sh` files
- All `*.xml` files

Some yaml files have been ignored because autogenerated.

@porcelli @LightGuard @Josephblt

### CODE REVIEW

**Review by Josephblt — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Comment by porcelli** [comment]
@yesamer we had some build failures =/

**Comment by yesamer** [comment]
@tiagobento Do you know the reason for those `git diffs` against the yaml file I modified?

**Comment by thiagoelg** [comment]
> @tiagobento Do you know the reason for those `git diffs` against the yaml file I modified?

Probably because these files are auto-generated.

I know that in `kogito-serverless-operator` there's a script that adds headers to these files, not sure why it's not working, I'll take a look.

For the helm charts files, we need to add these headers after generating them somehow.

**Comment by porcelli** [comment]
generated files do not need license headers... can we document what are the generated files?

**Comment by yesamer** [comment]
Thank you @thiagoelg!

Based on that, I guess can we ignore them @porcelli, right?

**Comment by porcelli** [comment]
correct, would need just to document - ideally adding to NOTICE file

**Review by pefernan — APPROVED** [review]

**Review by Josephblt — APPROVED** [review]

**Pull request merged**
