### PR TITLE
kie-issues#1041: Document how to upgrade `kie-tools` and `kie-sandbox-quarkus-accelerator` to a new timestamped SNAPSHOT or fixed release of upstream

### LINKED ISSUE #1041: Document how to upgrade `kie-tools` and `kie-sandbox-quarkus-accelerator` to a new timestamped SNAPSHOT or fixed release of upstream
There are several changes necessary to make sure the entire `kie-tools` repo is aligned with a single version of upstream. This task is for documenting it inside the `kie-tools` repo, in a Markdown file in the root directory.

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/1041

@tiagobento Open to evaluate any change/integration.

### CODE REVIEW

**Comment by tiagobento** [comment]
@yesamer Thanks Yeser! Looks great! I would just add a mention to the environment variables on `root-env/env/index.js`.

**Comment by yesamer** [comment]
@tiagobento Done!

**Comment by tiagobento** [comment]
@yesamer Two other last things... Today with the problem we found on `main` (#2232), @rodrigonull told me there are jobs publishing weekly timestamped SNAPSHOTs of `kogito-images`. Looks like we still have https://github.com/apache/incubator-kie-issues/issues/1082 to fix, but the difference is that for the images, the tag is actually `999-YYYYMMDD` instead of `main-YYYY-MM-DD`. Can you update that please?

Also, it's important that all snapshots are using the same date. Right now, on main, because of many reasons, we have images at 2024-04-03 and other stuff at 20240331.

**Comment by yesamer** [comment]
@tiagobento Done

**Review by tiagobento — APPROVED** [review]

**Review by thiagoelg — APPROVED** [review]

**Pull request merged**
