### PR TITLE
[10.0.x] kie-issues#2482: serverless-workflow-dev-ui-webapp: receive a parameter to recognize we are in a local cluster

### PR DESCRIPTION
**Pull request by fantonangeli**
Issue: https://github.com/apache/incubator-kie-tools/issues/2482

### CODE REVIEW

**Comment by thiagoelg** [comment]
I'm looking into the dev-deployment-upload-service tests failing

**Comment by fantonangeli** [comment]
> I'm looking into the dev-deployment-upload-service tests failing

Thank you so much @thiagoelg!
The only clue I can think now is that in the 10.0.x PRs list below, my PR is the only one updating the `pnpm-lock.yaml`
https://github.com/apache/incubator-kie-tools/pulls?q=is%3Apr+base%3A10.0.x

**Comment by thiagoelg** [comment]
This should fix it: https://github.com/apache/incubator-kie-tools/pull/2502 🙏

**Comment by fantonangeli** [comment]
Thanks again @thiagoelg for your PR.

@thiagoelg and @tiagobento Because the CI was failing I updated the file:
[packages/kie-sandbox-helm-chart/src/Chart.lock](https://github.com/apache/incubator-kie-tools/pull/2500/commits/25fc523599f89a09b9c38a3d7e21c977f6925218)
To update this file I used the command:
`pnpm -r -F kie-sandbox-helm-chart build:prod`
The red CI is [here](https://github.com/apache/incubator-kie-tools/actions/runs/10194281854/job/28200549568)

Can you confirm I did it right?

image

**Comment by thiagoelg** [comment]
Looks good @fantonangeli.

I guess we need to update the `install.js` script for `kie-sandbox-helm-chart` so that it updates the lockfile during the bootstrap of the repo.

Created an issue for it here: https://github.com/apache/incubator-kie-tools/issues/3948

**Review by wmedvede — APPROVED** [review]

**Comment by fantonangeli** [comment]
Thanks a lot @thiagoelg

**Review by ricardozanini — APPROVED** [review]

**Pull request merged**
