### PR TITLE
[0.19.2-prerelease] KOGITO-7386: implement acceptance tests for collection with generics in BPMN editor

### PR DESCRIPTION
**Pull request by domhanak**
cherry-pick of the main PR #1030

### CODE REVIEW

**Review by tomasdavidorg — APPROVED** [review]

**Comment by tiagobento** [comment]
@domhanak Conflicts after #1034

**Comment by domhanak** [comment]
Rebased @tiagobento

**Comment by tiagobento** [comment]
@domhanak Formatter issues 🙈

**Comment by domhanak** [comment]
@tiagobento ah, will fix.

**Comment by tiagobento** [comment]
@yesamer Build is failling on the 0.19.2-prerelease branch.. IDK if there's much we can do there except from applying #1039 ?

**Comment by domhanak** [comment]
@tiagobento If you know what to cherry-pick let me know :)

**Comment by yesamer** [comment]
@domhanak @tiagobento Yes, we should apply #1039 in this branch as well

**Comment by yesamer** [comment]
https://github.com/kiegroup/kie-tools/pull/1042 @tiagobento @domhanak

**Pull request merged**
