### PR TITLE
BAQE-1669: Include BPMN Kogito runtime selenium tests in default build

### PR DESCRIPTION
**Pull request by domhanak**
JIRA: https://issues.redhat.com/browse/BAQE-1669

Makes the tests part of default build & fixes them.
This mirrors the same behavior as DMN editor is doing.

### CODE REVIEW

**Comment by domhanak** [comment]
Forgot about the code-coverage, fixing...

**Review by tomasdavidorg — APPROVED** [review]

**Comment by domhanak** [comment]
So it seems DMN tests failing. Investigating.

**Comment by yesamer** [comment]
@domhanak I'm afraid these `it-tests` are broken for DMN Editor. Unfortunately, they were disabled for months, and probably the new logic we introduced resulted in these failures. To don't block this PR, I propose to mark them with `@Ignore` annotation and create a ticket to fix them.

**Comment by domhanak** [comment]
@yesamer Sure I will try to provide fix and if it is something that should take longer I will report and move it as a separate work.

**Comment by domhanak** [comment]
@yesamer So far I identified the errors/failures to be related to `Automatic Layout` modal popping up, so I will try to fix that.

**Comment by domhanak** [comment]
@yesamer Fixed most errors, only thing that fails now is this - `DMNDesignerKogitoSeleniumIT#testPaymentDateFile_KOGITO404` Looks like it expects `semantic:` prefix but the file after unmarshall has `dmndi:` or `dmn:` prefix

**Comment by yesamer** [comment]
> @yesamer Fixed most errors, only thing that fails now is this - `DMNDesignerKogitoSeleniumIT#testPaymentDateFile_KOGITO404` Looks like it expects `semantic:` prefix but the file after unmarshall has `dmndi:` or `dmn:` prefix

Great Job @domhanak ! I'll check the last issue

**Comment by yesamer** [comment]
Hi @domhanak I solved the issue you reported, please refer to https://github.com/domhanak/kie-tools/pull/21

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thank you @domhanak!

**Review by yesamer — APPROVED** [review]

**Review by jomarko — APPROVED** [review]

**Comment by yesamer** [comment]
@domhanak Can I merge this?

**Comment by domhanak** [comment]
@yesamer Yes please!

**Pull request merged**
