### PR TITLE
KOGITO-8798: Skip VSCode Select states test because of bug in Canvas API

### PR DESCRIPTION
**Pull request by LuboTerifaj**
https://issues.redhat.com/browse/KOGITO-8798

### CODE REVIEW

**Comment by LuboTerifaj** [comment]
Hello @handreyrc , @domhanak , could you please have a look at this PR? Thank you!

**Review by domhanak — APPROVED** [review]
What's the reason behind this PR? Was the test failing somewhere? You reference a bug with coordinates but I do not see them used now which is confusing me. Can't we just wait until #1366  and do a proper fix after it is merged? 

Here is my approval although I would prefer fixing the test directly in #1366

**Comment by LuboTerifaj** [comment]
Hello @domhanak ,

the coordinates and dimensions are not used because the part of the test is commented out. It was commented out in https://github.com/kiegroup/kie-tools/pull/1498.

As a result, the test is passing without testing what it is supposed to test. The PR changes the passed test, which is the state we want to avoid because the issue mentioned in my previous point, to the skipped one with the reference to the issue why it is skipped.

Thanks!

**Review by handreyrc — APPROVED** [review]
Hey @LuboTerifaj,

I agree that conceptualy it is a better approach to skip those tests other than commenting them out. This way we keep a better track of the tests executed and test summary consistent with what was indeed tested and what wasn't.
That being said I'm approving this PR.

Thanks

**Comment by LuboTerifaj** [comment]
Hello @paulovmr , this is ready to merge. Thanks!

**Review by caponetto — APPROVED** [review]

**Pull request merged**
