### PR TITLE
KOGITO-8328:  SWF Editor - Upgrade stream to GWT 2.10

### PR DESCRIPTION
**Pull request by romartin**
Upgrade of `serverless-workflow-diagram-editor` packages to _GWT 2.10.0_

See https://issues.redhat.com/browse/KOGITO-8328

### CODE REVIEW

**Review by LuboTerifaj — APPROVED** [review]
All integration tests passed. The changes look good to me. Thanks!

**Comment by romartin** [comment]
ok thakns @LuboTerifaj ! 
@treblereel your review turn, please! thanks!

**Comment by romartin** [comment]
@treblereel waiting for your review, please! Thanks in advance!

**Review by treblereel — APPROVED** [review]
All ok, good to go!

**Comment by LuboTerifaj** [comment]
@kiegroup/gatekeepers please merge. Thanks!

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
