### PR TITLE
KOGITO-8776: [SWF Diagram Editor] VsCode Plugin is being updated during the IT tests execution

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin,
Could you please review this PR?

 **JIRA**: [KOGITO-8776](https://issues.redhat.com/browse/KOGITO-8776)

Thanks!

### CODE REVIEW

**Review by paulovmr — CHANGES_REQUESTED** [review]
Hi @handreyrc , could you please add the `"extensions.autoUpdate"` property to the it-tests of the `vscode-extension-yard-editor` and `vscode-extension-pack-kogito-kie-editors` as well? They are also missing.

**Comment by handreyrc** [comment]
Hey @paulovmr,

Sure, consider it done!

Thanks!

**Review by paulovmr — APPROVED** [review]
Thanks!

**Review by domhanak — APPROVED** [review]
Good catch. @LuboTerifaj FYI

**Review by romartin — APPROVED** [review]

**Review by LuboTerifaj — COMMENTED** [review]
Hello @handreyrc ,

thank you for the PR.

However the test was not "fixed" properly. You commented out the code without further investigation.

The issue is, the Canvas API is broken. I reported the issue here: https://issues.redhat.com/browse/KOGITO-8793.

I would suggest to either update the test case so it does test what it is supposed to test, or ignore the test completely. Now we ended up with the test case that actually doesn't test what it is supposed to test.

Please if you are not sure what to do with such test, ask the creator of the test for the review next time.

Thank you!

**Comment by LuboTerifaj** [comment]
Here is the PR: https://github.com/kiegroup/kie-tools/pull/1505

**Comment by romartin** [comment]
thanks @LuboTerifaj , let's take this as a priority.

**Pull request merged**
