### PR TITLE
NO-ISSUE: Upgrade Kogito to `999-20240623-SNAPSHOT`

### PR DESCRIPTION
**Pull request by pefernan**
Ensemble:
https://github.com/apache/incubator-kie-tools/pull/2442
https://github.com/apache/incubator-kie-sandbox-quarkus-accelerator/pull/12

### CODE REVIEW

**Comment by yesamer** [comment]
@pefernan 

- jit-executor is still using `20240505`
- 
Screenshot 2024-06-21 at 14 48 54

**Review by yesamer — COMMENTED** [review]
@pefernan 

- jit-executor is still using `20240505`
- 
Screenshot 2024-06-21 at 14 48 54

**Comment by tiagobento** [comment]
After updating the values, you need to run a `bootstrap` to update the derivatives...

**Comment by pefernan** [comment]
@yesamer yea sorry, I'm working on it. I'm having some problems with my laptop today. 

As far as I know, jit-executor-native haven't been published :S

**Comment by tiagobento** [comment]
Hi guys! I took the liberty to take a look at this PR, and found out that indeed the JIT Executor Native is not being published to NPM anymore. We're actually publishing it to Maven now. I updated `extended-services` to download and unpack the binaries from Maven, and therefore now we only depend on upstream Images and Maven artifacts.

I also updated some other references from 20240509 to 20240620. Let's see how the build goes. 🙏

**Comment by rodrigonull** [comment]
FYI: a new weekly snapshot is available: `999-20240623-SNAPSHOT`

**Review by yesamer — APPROVED** [review]

**Comment by pefernan** [comment]
@rodrigonull great, going to update

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
