### PR TITLE
kie-issues#588: Add `NOTICE` file with findings in KIE Tools repository

### LINKED ISSUE #588: Add NOTICE.txt file with findings in KIE Tools repository

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/kiegroup/kie-issues/issues/588

### CODE REVIEW

**Review by porcelli — APPROVED** [review]
LGTM!

**Review by porcelli — APPROVED** [review]
LGTM!

**Comment by LightGuard** [comment]
I don't have a problem with it, though I wonder if we should be modifying the original copyright header instead of adding a new one beneath. It's in source control, and we can go back later.

**Review by LightGuard — APPROVED** [review]

**Comment by LightGuard** [comment]
We're green now, should we merge?

**Pull request merged**
