### PR TITLE
Update tests to use samples from kogito-tooling repository

### PR DESCRIPTION
**Pull request by tomasdavidorg**

### CODE REVIEW

**Comment by tiagobento** [comment]
@tomasdavidorg Hi Tomas! FDB is failing.. can you please check that?

**Comment by tomasdavidorg** [comment]
Hi @tiagobento , this PR is still in progress but the fail is probably not related to these changes. It looks like the editor is not loaded in time of access. I am investigating it.

**Comment by tomasdavidorg** [comment]
FDB failed on goal `Build kie-wb-common`:
```
2020-11-05T07:09:20.6816051Z [ERROR] Failed to execute goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source (add-source) on project kie-wb-common-dmn-webapp-kogito-testing: Execution add-source of goal org.kie:kie-gwthelper-maven-plugin:1.3:add-source failed: Plugin org.kie:kie-gwthelper-maven-plugin:1.3 or one of its dependencies could not be resolved: Could not transfer artifact org.apache.maven:maven-model:jar:3.6.0 from/to central (https://repo.maven.apache.org/maven2): Transfer failed for https://repo.maven.apache.org/maven2/org/apache/maven/maven-model/3.6.0/maven-model-3.6.0.jar: Connection reset -> [Help 1]
```

**Comment by tomasdavidorg** [comment]
Hi @tiagobento, all the checks are green. Could you please take a look? The PR tests will remain disabled as they are blocked by the https://issues.redhat.com/browse/KOGITO-3764 . When the issue is fixed, I will create a new PR to enable them https://issues.redhat.com/browse/KOGITO-3762.

**Review by domhanak — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
