### PR TITLE
KOGITO-8603: Add basic tests for dashbuilder autocomplete feature

### PR DESCRIPTION
**Pull request by barboras7**

### CODE REVIEW

**Comment by barboras7** [comment]
jenkins retest this

**Review by tomasdavidorg — APPROVED** [review]

**Comment by barboras7** [comment]
@jesuino could you please take a look so that we can merge?

**Review by jesuino — APPROVED** [review]
Thanks @barboras7  it looks good to me

Soon we will improve the schema for more auto complete options, but the test case you are covering (column type completion) will not be modified, so it is all good!

**Comment by barboras7** [comment]
@caponetto Could you please merge this?

**Review by caponetto — APPROVED** [review]

**Pull request merged**
