### PR TITLE
KOGITO-7663: Fix inconsistency in filename template description and default value

### PR DESCRIPTION
**Pull request by zdrapela**
Jira: https://issues.redhat.com/projects/KOGITO/issues/KOGITO-7663

### CODE REVIEW

**Comment by tiagobento** [comment]
This pattern is inherited from the DMN and BPMN extensions, that made the generated SVG compatible with Business Central. 

I'm +1 to change it for SWF, though.

cc @ederign

**Comment by ederign** [comment]
Hi @zdrapela this makes sense, but before merging this,  we need to double check if this is not somehow hardcoded on quarkus dev UI. @Sara4994 could you please confirm?

**Comment by Sara4994** [comment]
@ederign just checked quarkus dev UI, it is not hardcoded.

**Comment by domhanak** [comment]
@zdrapela confilicts, could you please report a follow-up JIRA to add some sort of integration tests into VSCode suite for the SVG gen?

**Comment by domhanak** [comment]
@zdrapela now it looks like a formatting issue, please check

**Comment by zdrapela** [comment]
@domhanak It was some issue with `prettier`, but now all checks are OK. 
Now I found out, that [README](https://github.com/kiegroup/kie-tools/blob/main/packages/vscode-extension-serverless-workflow-editor/README.md) mentions `${fileBasenameNoExtension}-svg.svg` as a default value (instead of current default `${fileBasename}.svg`). BPMN and DMN also use `${fileBasenameNoExtension}-svg.svg`, so it might be better to go that way.

**Review by domhanak — APPROVED** [review]
LGTM.

**Comment by tiagobento** [comment]
Deferring to @ederign.

**Comment by ederign** [comment]
@paulovmr would mind to take a look ?

**Comment by paulovmr** [comment]
Hi @zdrapela , the `kogito-addons-quarkus-process-svg` extension looks at a file with the same name as the workflow definition to make the SVG available through a REST service, so we should use `${fileBasenameNoExtension}.svg` by default. If you could please change that on the README as well. Thanks!

**Review by paulovmr — CHANGES_REQUESTED** [review]
Hi @zdrapela , the `kogito-addons-quarkus-process-svg` extension [looks](https://github.com/kiegroup/kogito-runtimes/blob/main/addons/common/process-svg/src/main/java/org/kie/kogito/svg/AbstractProcessSvgService.java#L67) at a file with the same name as the workflow definition to make the SVG available through a REST service, so we should use `${fileBasenameNoExtension}.svg` by default. If you could please change that on the README as well. Thanks!

**Comment by zdrapela** [comment]
Hi @paulovmr, thank you for explaining. I changed that to `${fileBasenameNoExtension}.svg` in the default value (same as it was before this PR), in the description and in README.

**Review by paulovmr — APPROVED** [review]
Thanks, @zdrapela !

**Comment by domhanak** [comment]
I think we can ignore the sonar check. It was broken works now and does not make sense for this PR.

**Review by yesamer — APPROVED** [review]

**Review by ederign — APPROVED** [review]

**Pull request merged**
