### PR TITLE
KOGITO-9159: Remove deprecated "vscode-extension-serverless-workflow-editor" extension

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Review by caponetto — APPROVED** [review]

**Comment by LuboTerifaj** [comment]
Hello @paulovmr , could you please rebase your PR with main? Thank you!

**Comment by paulovmr** [comment]
@LuboTerifaj Done!

**Comment by caponetto** [comment]
The `staging` and `daily-dev` jobs have been consistently failing since May 10.
However, we can see in this PR that the staging job has passed so let's merge it asap.

I assume the failures have to do with resource limits being reached and a workaround that I tested is to add `--workspace-concurrency=1` to staging and daily-dev builds just like we do for `CI :: Build`. We can do this if this PR does not resolve the issue.

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Pull request merged**
