### PR TITLE
NO-ISSUE: Remove workflow plugin dependency on knative/client int…

### PR DESCRIPTION
**Pull request by treblereel**
…erface

issue: https://github.com/apache/incubator-kie-issues/issues/1228

(cherry picked from commit dc7a3ecbcf65c835b0963e273c8a2308581e73d1)

### CODE REVIEW

**Review by wmedvede — APPROVED** [review]

**Comment by domhanak** [comment]
@tomasdavidorg fyi, want to check?

**Review by tomasdavidorg — APPROVED** [review]

**Comment by caponetto** [comment]
@treblereel The CI on Windows has failed. Could you please check?

**Comment by treblereel** [comment]
hmm,
```
packages/kogito-serverless-operator build:dev: ./hack/goimports.sh
packages/kogito-serverless-operator build:dev: Windows Subsystem for Linux has no installed distributions.
packages/kogito-serverless-operator build:dev: Distributions can be installed by visiting the Microsoft Store:
packages/kogito-serverless-operator build:dev: https://aka.ms/wslstore
```
not sure it's related to this pr, but lets take a look

**Comment by tiagobento** [comment]
@treblereel I saw you made #2339, which is a great test. I went looking into the changes of this PR and indeed there was no indication that the changes were related with the failure. 

Because you changed `kn-plugin-workflow`, all dependencies are built with `build:dev` (ignoring tests, linters etc). However, the `kogito-serverless-operator` package is configured with a command for Windows that doesn't seem to work. If you look at the `build:prod` command, the build is skipped. 

Please change `build:dev:win32` to `"build:dev:win32": "echo 'Build not supported on Windows'",`, so the `kogito-serverless-operator` package is also not built on Windows in development mode.

Sorry for the inconvenience! And great idea of sending this separate PR.

**Comment by treblereel** [comment]
It looks like CI is broke, https://github.com/apache/incubator-kie-tools/pull/2339

**Comment by treblereel** [comment]
@tiagobento yeap, let me do a separate PR for this.

**Pull request merged**
