### PR TITLE
KOGITO-7560: Bump all `monaco-editor` dependencies version to 0.33.0

### PR DESCRIPTION
**Pull request by yesamer**
**Module to test**

- [x] `monaco-editor`
- [ ] `examples\webapp`
- [x] `feel-input-component`
- [x] `pmml-editor`
- [x] `stunner-editors` - Web versions of DMN & BPMN editors
- [x] **`kie-kogito-editor-extension` - VSCode versions of DMN & BPMN and PMML editors**
--------------------------------------------------------------------------------------------------------
- [x] `kie-kogito-editor-extension` - VSCode versions of DMN Editor (Boxed expression editor)
- [x] `kie-kogito-editor-extension` - VSCode versions of BPMN Editor (Task node)
- [x] `kie-kogito-editor-extension` - VSCode versions of PMML Editor (Add Characteristic > Add attribute)

### CODE REVIEW

**Comment by tiagobento** [comment]
@yesamer I know this is WIP, but just so I don't forget. I think our `monaco-editor` package doesn't work well with this version.. Just pointing that out so look extra carefully to the components that use this module.

**Comment by yesamer** [comment]
@tiagobento `I think our monaco-editor package doesn't work well with this version..` Do you mean with the newer version `0.33.0`? 
However, I'm aware this is a tricky update, I'll check it very carefully. In case of issues, I'll raise an hand

**Comment by tiagobento** [comment]
Yes, with 0.33.0 I remember there were some problems.

**Comment by yesamer** [comment]
@tiagobento I am quite confident the new version will solve most of the failures. ;)
In case of other root causes, we will fix them too.

**Comment by tiagobento** [comment]
@yesamer On `stunner-editors`, we also have Monaco being used on the BPMN Editor. More specifically at the Task nodes. If you open the Properties panel you should see a place there where you can choose the language and a Monaco editor pops up.

**Comment by yesamer** [comment]
@tiagobento Thank you! Do you know where is used in PMML editor?

**Comment by tiagobento** [comment]
@yesamer Yes. Go to `Add characteristic` then `Add attribute`. There, you should be checking for the fonts and the autocompletion of `True` and `False` values only. It's pretty simple usage.

**Comment by yesamer** [comment]
It seems `examples\webapp` DMN and BPMN editors are not working correctly
Screenshot from 2022-07-20 16-40-02

**Comment by tiagobento** [comment]
As part of this PR, we should also remove the custom rules we have at `.syncpackrc.json`.

**Comment by yesamer** [comment]
@tiagobento Should I remove the file?

**Comment by tiagobento** [comment]
@yesamer I don't think so, leave it there 😝

**Comment by tiagobento** [comment]
@tomasdavidorg Can you please help verify this PR? It touches a lof of important places. Let us know if you have questions on how to test it.

**Comment by tomasdavidorg** [comment]
Hi @tiagobento, I can take a look. What are the impacted editors? BPMN, DMN, PMML? And what about the channels? Vscode, online?

**Comment by yesamer** [comment]
Hi @tomasdavidorg, yes, this change affects all the editors you mentioned. Please consider my list in the first post to have more details.

**Review by tomasdavidorg — APPROVED** [review]
@yesamer Looks good to me. I didn't find any problem. Just the `examples\webapp` does not work.

**Comment by yesamer** [comment]
@tomasdavidorg thank you! 
@tiagobento I would ask for an engineering review too, just to triple-check :)

**Comment by tiagobento** [comment]
@yesamer I'll take a look at this one ASAP.

**Comment by tiagobento** [comment]
@yesamer Just noticed that this branch is on the origin repo. Can you please reopen a PR from your fork instead?

**Comment by yesamer** [comment]
Reopened here: https://github.com/kiegroup/kie-tools/pull/1098

**Pull request closed without merging**
