### PR TITLE
KOGITO-8404: Dashbuilder VSCode extension: Auto Complete

### PR DESCRIPTION
**Pull request by AjayJagan**
adding autocomplete support to vscode extension of dashbuilder
JIRA: https://issues.redhat.com/browse/KOGITO-8404

### CODE REVIEW

**Comment by AjayJagan** [comment]
need to wait for this minor fix: https://github.com/jesuino/dashbuilder-website/pull/10 .. before we can start testing :)

**Comment by jesuino** [comment]
Hello Ajay,

Thank you so much for this PR! Your work is looking great and I really appreciate your hard work on it!

I can see auto complete working very well, just a few thoughts:

1) I see that some minor problems are displayer as errors - would it be possible to set as WARNINGS instead? Here's for example, this works as String or number, so not an issue if this is a String

image


2) In properties it says that the property should be String, which is not true - it can be any primitive type:

image


3) This also could be a warning because lower or upper case would work

image


4) In `settings`, lookup is indeed obligatory, but it may be defined globally, inside `global`, so it would be great to have it as a warning as well instead error

5) In the case showed on the image below baseUrl is not required and width/height for external are not numbers:

image


6) groupFunctions also work as "functions" - I would prefer to validate to functions because it is what we are going to use

image


7) In this case I don't know why it complains about the fields under "echarts" - this is a free object where users can add any property to the component - so we should not have validation under the component configuration

image


8) the fields html and javascript under displayer/html are indeed String - I am not sure why it complained:

image

That's all for now. 

Thanks!

**Review by jesuino — CHANGES_REQUESTED** [review]
Please see my comment!

**Review by fantonangeli — APPROVED** [review]
Thank you @AjayJagan. 
From the code viewpoint, this work looks great!

**Comment by jesuino** [comment]
Hello @AjayJagan ,

Thanks for your changes, it is working great now!

I will approve this PR and suggest some changes to the schema:

1) For `axis -> x` or `axis -> y `any of the properties are required:

image

I know that you did this because the auto complete when adding the property is really great

2) For sort we made a change to sortOrder to "order"

image

3) On settings.chart.zoom it is actually a boolean or string 

image

4) On settings.columns only ID is required

image

5) For settings.filter only enabled is required

image

6) With lookup uuid is indeed is required - but sometimes we define it globally in global.settings - but I don't know if this is possible to solve on the schema - if does it is not possible to solve don't worry

image

7) Finally I still see message as ERRORS, but it would be good it it was as WARNING - if it is not possible just let me know 

We can approve and merge this PR and do these improvements to the schema in parallel

Thanks!

**Review by jesuino — APPROVED** [review]
LGTM!

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
