### PR TITLE
KOGITO-2076: Open File API

### PR DESCRIPTION
**Pull request by caponetto**
**Task**: [KOGITO-2076](https://issues.redhat.com/browse/KOGITO-2076)

**Related PRs**:
- https://github.com/kiegroup/appformer/pull/961
- https://github.com/kiegroup/kogito-tooling/pull/151

**Note**: Wait for https://github.com/kiegroup/kogito-tooling/pull/142 get merged first.

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Review by tiagobento — COMMENTED** [review]
Since we'll wait for #142 to be merged, I'll review it more carefully after that. Looking at the code now I don't see anything to change :)

**Comment by manstis** [comment]
@caponetto  Hi.. your PR can proceed.... however (not unexpectedly) there are some conflicts now the re-usable embedded editor changes have been merged (`-desktop` and `-online` now use the same _core_ embedded editor so you will need to move some of your changes to `embedded-editor` but the code should look familiar, just in a different place). Also, whatever you change to `embedded-editor` will affect `-desktop`, `-online` and `-chrome-extension` so be warned!

**Comment by tiagobento** [comment]
@caponetto Is this ready for review?

**Comment by caponetto** [comment]
@tiagobento not yet! I'm working on it.

**Review by tiagobento — APPROVED** [review]
LGTM! Nice feature :)

**Review by jomarko — COMMENTED** [review]
@caponetto hello, code looks good to me, however one question before my approval. 
Is this just a  middle step for future PRs (features) or already now can user spot a difference? Sorry it is not clear to me from jira description. 

e.g. Previously opening new tab in VS code caused error now it works.

**Comment by caponetto** [comment]
Hi @jomarko, thanks for the review! Currently, it is just a middle step. Is is up to the editors to use the API to fit their needs.

**Review by jomarko — APPROVED** [review]
@caponetto thank you.

**Pull request merged**
