### PR TITLE
KOGITO-7199: SWF Viewer - Usability improvements for mediators (Mouse Pointers)

### PR DESCRIPTION
**Pull request by Josephblt**
**JIRA:** [KOGITO-7199 - SWF Viewer - Usability improvements for mediators (Mouse Pointers)](https://issues.redhat.com/browse/KOGITO-7199)

Scale about a point.
Change mouse pointer once starting the keystroke combination -> Use according to pointers

**VS Code Extension:** [Serveless Workflow Editor](https://drive.google.com/file/d/1AdXFiu-zNa6PZ3_ashk_0oPc7eUjNiHz/view?usp=sharing)

### CODE REVIEW

**Comment by domhanak** [comment]
@Josephblt What should be the goal of this JIRA? Not clear from the description.

**Review by romartin — APPROVED** [review]
Thanks @Josephblt , looks good!!

**Comment by romartin** [comment]
@domhanak please missing review here. Thanks!

**Comment by domhanak** [comment]
@romartin @Josephblt as I mentioned in my previous comment, I do not know what to test. The JIRA does not state that clearly.

**Comment by romartin** [comment]
hey  @Josephblt can you please sync with  @domhanak on the goals to test please?

**Comment by Josephblt** [comment]
Hello @domhanak, @romartin. I did a minor update on this PR, it does not change much but standardizes mediator activation and cursor changes. I also updated the PR description and left a comment describing the changes. VSCode extension is updated.

**Comment by romartin** [comment]
@domhanak please missing review here, once possible. thanks!

**Review by domhanak — APPROVED** [review]
I guess rebasing is needed? LGTM otherwise

**Pull request merged**
