### PR TITLE
Bump `org.kie` to `8.20.0.Beta`

### PR DESCRIPTION
**Pull request by yesamer**

### CODE REVIEW

**Comment by yesamer** [comment]
@tiagobento Can you please approve and merge it?

**Comment by tiagobento** [comment]
@yesamer Should we be doing that on `serverless-workflow-diagram-editor` too? cc @romartin

**Comment by yesamer** [comment]
@tiagobento Good point, done!

**Comment by yesamer** [comment]
@tiagobento Can you please approve and merge it?

**Comment by yesamer** [comment]
@tiagobento `org.kie` assets are not used in SWF module, removed it. Can I have an approval please ?

**Review by romartin — APPROVED** [review]
thanks @yesamer , I also understand kie assets are not being used in swf too, also builds are green, so it looks good to me, thanks!

**Pull request merged**
