### PR TITLE
KOGITO-7679: SW Stunner Editor changes user's cursor if node is selected making it impossible to edit the file

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, could you please review this PR?

 **JIRA**: [KOGITO-7679](https://issues.redhat.com/browse/KOGITO-7679)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Hey @domhanak 

Assigned you as a reviewer for this PR, as the ticket defines :)

Please notice this is a **critical issue**, which prevents users for the proper authoring of the JSON, so would really appreciate early review as much as possible, thanks in advance!

NOTE: If this gets merged, this other PR can be closed - https://github.com/kiegroup/kie-tools/pull/1077

Thanks!

**Review by romartin — APPROVED** [review]
Looks great for me, thanks @handreyrc !

**Review by domhanak — CHANGES_REQUESTED** [review]
I just followed the steps to reproduce and the issue persists,
once the state becomes valid again, after 2-3 seconds cursor is moved to the  start of state.

**Comment by domhanak** [comment]
See the video for issue and workaround:
[Screencast from 08-10-2022 09:39:27 AM.webm](https://user-images.githubusercontent.com/5937251/183843461-5d612153-91c8-4040-96f0-290bc40b0841.webm)

**Comment by handreyrc** [comment]
Hey @domhanak,

It seems you are facing some sort of instalation or build issue. 
I also asked @Josephblt to check it and it works well.

I'm sharing my VSIX for you to test just in case.
**VS Code**: [plugin](https://drive.google.com/file/d/1TuYiU9PXzxDO3Og59MBz5tJJNtvGq15U/view?usp=sharing) 

Please ping me if the issue persits and we can figure it out.

Thanks

**Comment by domhanak** [comment]
@Josephblt Tagging you here, since you have no issues with the installation could you please verify?

**Review by domhanak — APPROVED** [review]
Code looks good to me, please verify the fix as I have issues with my  VSCode and do not want to stall this PR as lots of you reported it works in chat.

**Comment by Josephblt** [comment]
Yeah @domhanak . Tested it on friday. It worked all right. I used @handreyrc .vsix.

**Review by Josephblt — APPROVED** [review]

**Review by LuboTerifaj — APPROVED** [review]
I didn't find any issues. It looks good to me. Thanks!

**Comment by handreyrc** [comment]
Thanks @domhanak @Josephblt @LuboTerifaj for testing this PR.

This PR is ready to be merged!

**Pull request merged**
