### PR TITLE
KOGITO-6671: Render Question, Allowed Answers and Text Annotations on DMN Documentaion page

### PR DESCRIPTION
**Pull request by jomarko**
For more details see:
- https://issues.redhat.com/browse/KOGITO-6671

### CODE REVIEW

**Review by yesamer — APPROVED** [review]
LGTM @jomarko

**Review by yesamer — APPROVED** [review]
@jomarko Thank you for managing that. Tell me when you want to merge it.

**Comment by jomarko** [comment]
@yesamer please merge, "(build) kie-tools-stunner-editors " will not finish, there is an issue in jenkins machine provisioning infrastructure. Also please tell me if I should try to backport into business central.

**Comment by yesamer** [comment]
@jomarko I would consider the backport to BC only if requires a very low effort. If this is the case, please proceed. Thank you!

**Pull request merged**
