### PR TITLE
KOGITO-4654 Check the code is formatted during CI build

### PR DESCRIPTION
**Pull request by jomarko**
This PR follows changes done by:
- kiegroup#465

For more details see:
- https://issues.redhat.com/browse/KOGITO-4654

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
I would rather do the check in a separate workflow so the FDB or other builds are not blocked by this. WDYT?

**Comment by tomasdavidorg** [comment]
Chrome fails are caused by update of Chrome browser to version 90. Fix is here https://github.com/kiegroup/kogito-tooling/pull/483

Maybe we could also consider separation of the `yarn.lock` check from the FBD and CI builds later. @tiagobento WDYT?

**Comment by tiagobento** [comment]
Hi @jomarko @tomasdavidorg. Thanks for submitting this PR. However, I agree with @tomasdavidorg that the FDB Is not the best place to run it. We should include this check on our "CI - Default" workflows. Also, as you're adding a script to check the formatting, why not add one to actually to the formatting too? :) I'd say `yarn format` and `yarn format:check` are good names.

**Comment by jomarko** [comment]
Thank you for quick feedback, incorporating changes now.

**Comment by jomarko** [comment]
@tomasdavidorg if I have a look on the `ci.yml`, there is a step `Check yarn.lock md5`. it seems to me be a duplicate of `pull_request_full_downstream_ci.yml` - `Check yarn.lock`. Should I remove `Check yarn.lock` step?

**Comment by tiagobento** [comment]
@jomarko I think you can remove the yarn.lock check from FDB, yes. There's no reason for this to be duplicated.

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@jomarko The CI is breaking on the new check. Looks like some files were not formatted?

**Comment by jomarko** [comment]
@tiagobento there seems to be specific issue on windows. mac and ubuntu passed `format:check`. I tried to fix with the last commit.

I didn't find un-formatted files even after rebasing with master.

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
