### PR TITLE
Bump Editors to 8.4.0 and Kogito Runtime to 1.11.1.Final

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Comment by domhanak** [comment]
Checked locally and vscode tests works well there. ON CI there seems to be some dialog blocking the further clicks I will investigate & try to add screenshots for future analysis. In the meantime, rerun should help.

**Comment by domhanak** [comment]
@tiagobento I identified the issue, DMN editor now correctly assumes the isDirty identification when user edits particular properties I am working on a fix.

**Comment by tiagobento** [comment]
@domhanak Perfect, Dominik! Thanks for looking into that! Please send a PR to `tiagobento:bump-editors-to-8.4.0.Final` when you have the fix :D

**Comment by domhanak** [comment]
@tiagobento here it is https://github.com/tiagobento/kogito-tooling/pull/39 Not adding screenshots as mentioned in my comment. It will be a separate JIRA and PR :) 
On my first run I must have used older editors and this issue did not manifest. Apologies for the incorrect info there.

**Review by caponetto — APPROVED** [review]

**Review by ederign — APPROVED** [review]

**Pull request merged**
