### PR TITLE
KOGITO-9597: Broken error page layout

### PR DESCRIPTION
**Pull request by treblereel**
jira: https://issues.redhat.com/browse/KOGITO-9597

### CODE REVIEW

**Review by hasys — APPROVED** [review]
Hi @treblereel, looks and works good, thank you!

Just my 2c will be good to report an issue to clean up unused resources in the future. 

Thank you!

**Review by LuboTerifaj — COMMENTED** [review]
Hello @treblereel ,

is it necessary to use base64 representation of the fonts? Are there any disadvantages to have them in separate files? My concern is the worse code readability and maintainability.

Other than that it looks good to me.

Thanks!

**Review by LuboTerifaj — APPROVED** [review]
Hello @treblereel , please see my comment above. I am approving the fix for now since we are close to the next release. We can address the issue in a separate jira if necessary. Thanks!

**Comment by caponetto** [comment]
Hi, in order to include this fix in the 0.31.0 release, we will need a cherry-pick to `0.31.0-prerelease` branch.
@treblereel could you please do that?
cc @paulovmr

**Comment by treblereel** [comment]
@caponetto https://github.com/kiegroup/kie-tools/pull/1902

**Review by romartin — APPROVED** [review]

**Pull request merged**
