### PR TITLE
KOGITO-8062: DSL: Refactor environments

### PR DESCRIPTION
**Pull request by radtriste**

### CODE REVIEW

**Comment by tiagobento** [comment]
@radtriste What's the status of this PR? Still WIP?

**Comment by radtriste** [comment]
@tiagobento yes it is. This is a nice to have. I just have other priorities for now ;)

**Comment by radtriste** [comment]
@ederign @tiagobento all good to be merged

**Comment by radtriste** [comment]
cc @paulovmr

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
