### PR TITLE
KOGITO-6544: [KIE Sandbox] Can't open files with upper-case extensions

### PR DESCRIPTION
**Pull request by thiagoelg**
# JIRA Issue
https://issues.redhat.com/browse/KOGITO-6544

# In this PR
- Added support for uppercase file extensions (BPMN, BPMN2, DMN, PMML, and SCESIM) in KIE Sandbox, VSCode extensions and Chrome extension

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@tomasdavidorg This is ready for review.

**Comment by tomasdavidorg** [comment]
Hi @thiagoelg, I checked both VS code and Kie Sandbox and they look good to me. However I was not able to open bpmn/BPMN file at all. I just got the loading text inside VS Code (1.63.2). I also tried the main branch and the extension which are published and I saw the same problem. Do you know if there is a known issues?
Screenshot from 2022-01-17 12-24-09

About the Chrome extension and the desktop application: Is this PR only for VS Code and Kie Sandbox? Is there any plan to fix this issue also for them?

**Comment by tomasdavidorg** [comment]
@tiagobento ^

**Comment by thiagoelg** [comment]
Hi @tomasdavidorg, I committed a fix for the Chrome Extension, It should be working now! Thanks!

About the BPMN files not loading, this is an issue that I also stumbled upon while working on this PR and I've opened a new JIRA for it here: https://issues.redhat.com/browse/KOGITO-6550

**Comment by tomasdavidorg** [comment]
Thanks a lot @thiagoelg are you looking also at the Desktop channel? Just want to make sure :-D. Thanks

**Comment by thiagoelg** [comment]
@tomasdavidorg yep, looking into it right now, should be a similar fix :D

**Comment by tomasdavidorg** [comment]
Hi, @thiagoelg 

I found one more issue in the Desktop app:

Screenshot from 2022-01-18 10-25-29

There is no logo for BPMN, BPMN2 or DMN files in `kogito-tooling/packages/desktop/static/images`. The issue is on the line 105 in `kogito-tooling/packages/desktop/src/webview/editor/EditorToolbar.tsx`:

https://github.com/kiegroup/kogito-tooling/blob/main/packages/desktop/src/webview/editor/EditorToolbar.tsx#L105

``src={`images/${fileExtension}_kogito_logo.svg`}``

Maybe we could lowercase the `fileExtension`.

**Comment by thiagoelg** [comment]
That fix worked perfectly, thanks @tomasdavidorg!

image
image

**Review by tomasdavidorg — APPROVED** [review]
@thiagoelg thanks for the changes. Looks good to me now.

**Comment by manstis** [comment]
Just asking... what about `.bPmN` etc

Presumably they're edge cases we don't care about.

**Comment by tomasdavidorg** [comment]
I would say those other variations of letters are not the same as `.bpmn` and `.BPMN` and we can ignore them.

**Pull request merged**
