### PR TITLE
KOGITO-6249: Check if there are new changes in the Gist before force-pushing

### PR DESCRIPTION
**Pull request by thiagoelg**
# JIRA Issue
https://issues.redhat.com/browse/KOGITO-6249|

# On this PR
- Added a check to see if Gist can be pushed normally, if not, offer to force push instead.

### Happy path

https://user-images.githubusercontent.com/10515135/148298378-a9d20d20-c1ce-419e-939f-9763ec6848a1.mp4

### User dismiss force push

https://user-images.githubusercontent.com/10515135/148298388-b3128fce-c269-4bbb-b65d-e84cb42593b0.mp4

### CODE REVIEW

**Comment by tiagobento** [comment]
@thiagoelg As we spoke, there's an issue with the idempotence of the `Push` action. This is not necessarily related to this PR, as the same occurs on the current version, but it would be nice to fix it, so we avoid checking for local changes before pushing a Gist.

**Comment by thiagoelg** [comment]
> @thiagoelg As we spoke, there's an issue with the idempotence of the `Push` action. This is not necessarily related to this PR, as the same occurs on the current version, but it would be nice to fix it, so we avoid checking for local changes before pushing a Gist.

With the help from @tiagobento this issue was solved by adding a remote ref check before pushing, this way if the remote and local refs are the same we can skip pushing.

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@tomasdavidorg This is ready for review.

**Comment by tomasdavidorg** [comment]
Hi @thiagoelg, one question when:

1. Gist with two or more files is created and imported to the sandbox.
2. Gist is modified on Github pages.
3. Gist is modified in the Sandbox.
4. User tries to leave the editor without updating the gist.
5. Dialog is displayed
image

Clicking `Push to 'origin/master'` button won't do anything. Shouldn't be there also "force push" option?

**Comment by thiagoelg** [comment]
@tomasdavidorg Nice catch! I've committed a fix for this behavior.

https://user-images.githubusercontent.com/10515135/148836193-324ddb7b-045a-48e7-b38a-e2cd2ed44dca.mp4

https://user-images.githubusercontent.com/10515135/148836181-86bf5a5e-89ce-4cef-9ed3-bcdaef2928fe.mp4

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@thiagoelg Nice! Approved again 😄

**Review by tomasdavidorg — APPROVED** [review]
Thanks @thiagoelg. Looks good to me now.

**Pull request merged**
