### PR TITLE
KOGITO-3718, KOGITO-4261: Test included models on VSCode kogito extension

### PR DESCRIPTION
**Pull request by jomarko**
The actual change is https://github.com/kiegroup/kogito-tooling/pull/395/commits/6af6a77aea816da53f9a26be05caa3606b7709bc

Can not be merged sooner than listed PRs:
- #391 
- #383 
- kiegroup/appformer#1090
- kiegroup/kie-wb-common#3537

    For more details see
    - https://issues.redhat.com/browse/KOGITO-3718
    - https://issues.redhat.com/browse/KOGITO-4261

### CODE REVIEW

**Comment by tiagobento** [comment]
@jomarko This PR has conflicts, would you please rebase it?

**Comment by jomarko** [comment]
@tiagobento sure, I included just #383 commits to see tests works in our CI and ignored my tests that still depends on kiegroup/appformer#1090 and kiegroup/kie-wb-common#3537

**Comment by jomarko** [comment]
@tomasdavidorg @jstastny-cz added you as reviewers too, interested in your opinion of new test as you are experienced UI testers.

**Review by jstastny-cz — COMMENTED** [review]
I am not familiar with this suite, so I'll leave to others to approve/request changes.

I don't see anything wrong in the code at the first sight.

**Review by tomasdavidorg — APPROVED** [review]

**Comment by jomarko** [comment]
full downstream build is failing as:
```
:11:13.2688448Z vscode-extension-pack-kogito-kie-editors:      NoSuchElementError: no such element: Unable to locate element: {"method":"link text","selector":"demo.dmn"}
2021-01-27T21:11:13.2690584Z vscode-extension-pack-kogito-kie-editors:   (Session info: chrome=83.0.4103.122)
2021-01-27T21:11:13.2693834Z vscode-extension-pack-kogito-kie-editors:   (Driver info: chromedriver=83.0.4103.39 (ccbf011cb2d2b19b506d844400483861342c20cd-refs/branch-heads/4103@{#416}),platform=Linux 5.4.0-1036-azure x86_64)
2021-01-27T21:11:13.2697488Z vscode-extension-pack-kogito-kie-editors:       at Object.checkLegacyResponse (/home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/error.js:546:15)
2021-01-27T21:11:13.2701625Z vscode-extension-pack-kogito-kie-editors:       at parseHttpResponse (/home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/http.js:509:13)
2021-01-27T21:11:13.2705234Z vscode-extension-pack-kogito-kie-editors:       at /home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/http.js:441:30
2021-01-27T21:11:13.2707753Z vscode-extension-pack-kogito-kie-editors:       at runMicrotasks (<anonymous>)
2021-01-27T21:11:13.2709966Z vscode-extension-pack-kogito-kie-editors:       at processTicksAndRejections (internal/process/task_queues.js:97:5)
2021-01-27T21:11:13.2850700Z vscode-extension-pack-kogito-kie-editors:   From: Task: WebElement.findElement(By(link text, demo.dmn))
2021-01-27T21:11:13.2854228Z vscode-extension-pack-kogito-kie-editors:       at Driver.schedule (/home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/webdriver.js:807:17)
2021-01-27T21:11:13.2858134Z vscode-extension-pack-kogito-kie-editors:       at SideBarView.schedule_ (/home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/webdriver.js:2010:25)
2021-01-27T21:11:13.2862118Z vscode-extension-pack-kogito-kie-editors:       at SideBarView.findElement (/home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/node_modules/vscode-extension-tester/node_modules/selenium-webdriver/lib/webdriver.js:2057:17)
2021-01-27T21:11:13.2865301Z vscode-extension-pack-kogito-kie-editors:       at VSCodeTestHelper.<anonymous> (out/ui-test/helpers/VSCodeTestHelper.js:108:67)
2021-01-27T21:11:13.2867668Z vscode-extension-pack-kogito-kie-editors:       at step (out/ui-test/helpers/VSCodeTestHelper.js:48:23)
2021-01-27T21:11:13.2869956Z vscode-extension-pack-kogito-kie-editors:       at Object.next (out/ui-test/helpers/VSCodeTestHelper.js:29:53)
2021-01-27T21:11:13.2873494Z vscode-extension-pack-kogito-kie-editors:       at /home/runner/work/kogito-tooling/kogito-tooling/kogito-tooling/packages/vscode-extension-pack-kogito-kie-editors/out/ui-test/helpers/VSCodeTestHelper.js:23:71
2021-01-27T21:11:13.2876438Z vscode-extension-pack-kogito-kie-editors:       at new Promise (<anonymous>)
2021-01-27T21:11:13.2878564Z vscode-extension-pack-kogito-kie-editors:       at __awaiter (out/ui-test/helpers/VSCodeTestHelper.js:19:12)
2021-01-27T21:11:13.2881306Z vscode-extension-pack-kogito-kie-editors:       at VSCodeTestHelper.openFileFromSidebar (out/ui-test/helpers/VSCodeTestHelper.js:104:65)
```

trying new way of opening from side bar in last commit

**Comment by jomarko** [comment]
@tiagobento may I ask you to restart the failed checks? my last commit seems be promising to fix issue we have in #383

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
