### PR TITLE
Bump `vscode-extension-tester` to `4.4.0`

### PR DESCRIPTION
**Pull request by yesamer**

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@yesamer Feel free to merge once you're confident that there are no intermittent failures.

**Review by ederign — APPROVED** [review]

**Comment by yesamer** [comment]
2022-08-04T16:03:10.0650063Z   Editors are loading properly
2022-08-04T16:03:14.4279782Z (node:81632) PromiseRejectionHandledWarning: Promise rejection was handled asynchronously (rejection id: 1)
2022-08-04T16:03:14.4281259Z (Use `node --trace-warnings ...` to show where the warning was created)
2022-08-04T16:03:23.7498116Z       ✔ Opens demo.bpmn file in BPMN Editor and loads correct diagram: 9324ms
2022-08-04T16:03:32.2629619Z       ✔ Opens demo.dmn file in DMN Editor: 8031ms
2022-08-04T16:03:41.6496303Z       ✔ Include reusable-model in DMN Editor: 8840ms
2022-08-04T16:03:56.4169150Z       ✔ Undo command in DMN Editor: 12882ms
2022-08-04T16:04:05.6057969Z       1) Check new DMN Expression Editor
2022-08-04T16:04:05.6619157Z       2) "after each" hook for "Check new DMN Expression Editor"
2022-08-04T16:04:06.6770732Z Shutting down the browser
2022-08-04T16:04:07.3008240Z Uninstalling kie-group.vscode-extension-pack-kogito-kie-editors...
2022-08-04T16:04:07.3131223Z Extension 'kie-group.vscode-extension-pack-kogito-kie-editors' was successfully uninstalled!
2022-08-04T16:04:07.4156559Z 
2022-08-04T16:04:07.4158166Z   Suite duration: 57.351 s, Tests: 6
2022-08-04T16:04:07.4189495Z 
2022-08-04T16:04:07.4192958Z   4 passing (1m)
2022-08-04T16:04:07.4193559Z   2 failing
2022-08-04T16:04:07.4199553Z 
2022-08-04T16:04:07.4204926Z   1) Editors are loading properly
2022-08-04T16:04:07.4205897Z        Check new DMN Expression Editor:
2022-08-04T16:04:07.4207381Z      StaleElementReferenceError: stale element reference: element is not attached to the page document
2022-08-04T16:04:07.4208105Z   (Session info: chrome=98.0.4758.109)
2022-08-04T16:04:07.4209996Z       at Object.throwDecodedError (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/error.js:522:15)
2022-08-04T16:04:07.4212261Z       at parseHttpResponse (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/http.js:549:13)
2022-08-04T16:04:07.4214097Z       at Executor.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/http.js:475:28)
2022-08-04T16:04:07.4214922Z       at runMicrotasks (<anonymous>)
2022-08-04T16:04:07.4215890Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-04T16:04:07.4217638Z       at async Driver.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:735:17)
2022-08-04T16:04:07.4218180Z 
2022-08-04T16:04:07.4218448Z   2) Editors are loading properly
2022-08-04T16:04:07.4219215Z        "after each" hook for "Check new DMN Expression Editor":
2022-08-04T16:04:07.4220775Z      NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-dialog-box"}
2022-08-04T16:04:07.4221484Z   (Session info: chrome=98.0.4758.109)
2022-08-04T16:04:07.4223158Z       at Object.throwDecodedError (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/error.js:522:15)
2022-08-04T16:04:07.4225063Z       at parseHttpResponse (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/http.js:549:13)
2022-08-04T16:04:07.4226882Z       at Executor.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/http.js:475:28)
2022-08-04T16:04:07.4227717Z       at runMicrotasks (<anonymous>)
2022-08-04T16:04:07.4228541Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-08-04T16:04:07.4230258Z       at async Driver.execute (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:735:17)
2022-08-04T16:04:07.4232132Z       at async toWireValue (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:140:15)
2022-08-04T16:04:07.4233898Z       at async /home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:190:16
2022-08-04T16:04:07.4235730Z       at async forEachKey (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:184:9)
2022-08-04T16:04:07.4237623Z       at async convertKeys (/home/runner/work/kie-tools/kie-tools/node_modules/.pnpm/selenium-webdriver@4.2.0/node_modules/selenium-webdriver/lib/webdriver.js:189:3)

**Comment by yesamer** [comment]
@tiagobento @domhanak 
Reported 2 failures due to:
`StaleElementReferenceError: stale element reference: element is not attached to the page document`
Attempt # 2: on `kie-kogito-chrome-extension` it-test: `Error while finding element: By(css selector, .js-navigation-open)`
Attempt # 4 and # 5: on `kie-kogito-vscode-extension` it-test: `NoSuchElementError: no such element: Unable to locate element: {"method":"css selector","selector":".monaco-dialog-box"}`

~~These tests failures are intermittent too, and they occurred in the past too (in other PRs)~~
~~Therefore, I think this PR can be safely merged because:~~
- ~~The new `vscode-extension-tester` improves the stability of the tests: the previously skipped test seems working correctly;~~
- ~~The intermittent failures were already reported in the past, so not related to this change;~~

~~We just need to understand the root cause of these failures, and we'll finally have a stable test environment!~~

The case related to Attempt 2 is on `kie-kogito-chrome-extension`, so I don't consider it related to this PR. We can investigate it separately. 
I'm more worried about 4 and 5 attempts. I expected the new `vscode-extension-tester` version solved that bug.

**Comment by yesamer** [comment]
Unstable - Please do not merge.

**Comment by domhanak** [comment]
@yesamer If it is unstable, we can also try adding specific (non-mandatory) workflow that will trigger only vscode it-tests.
In the meantime we will be running these nightly on our jenkins, as a backup.

**Comment by domhanak** [comment]
@yesamer could you please fix the conflicts?

**Comment by yesamer** [comment]
Closing as part of https://github.com/kiegroup/kie-tools/pull/1178

**Pull request closed without merging**
