### PR TITLE
NO-ISSUE: ASF CI Migration - Update Jenkins jobs repository names and credentials

### PR DESCRIPTION
**Pull request by rodrigonull**
@tiagobento @porcelli Can we move https://github.com/kiegroup/serverless-logic-sandbox-deployment to apache org?
I think we forgot to move that one.

### CODE REVIEW

**Comment by porcelli** [comment]
Red Hat has concerns about moving those repos.

@ederign @krisv @mdproctor

**Comment by tiagobento** [comment]
@rodrigonull Can we change this PR to leave https://github.com/kiegroup/serverless-logic-sandbox-deployment at `kiegroup` for now? We can discuss that in parallel, as I think this PR addresses issues that are only not related to this repo, right?

**Comment by porcelli** [comment]
@tiagobento can we just remove the reference to serverless-logic-sandbox-deployment? I'm concerned about this cross organization in the CI between Apache and krigroup.

**Comment by ederign** [comment]
@tiagobento @rodrigonull @porcelli feel free to remove all CI references to serverless-logic-sandbox-deployment . We are going to implement a new deployment job on serverless-logic-sandbox-deployment repository.

**Comment by rodrigonull** [comment]
@ederign @porcelli @tiagobento I've removed all references to serverless-logic-sandbox-deployment.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
