### PR TITLE
KOGITO-7877: Migrate Cypress to version 10

### PR DESCRIPTION
**Pull request by tomasdavidorg**
https://issues.redhat.com/browse/KOGITO-7877

More information to migration:
https://docs.cypress.io/guides/references/migration-guide#Migrating-to-Cypress-version-10-0

Changes:
- Update Cypress dependencies to `10.7.0`
- Update `cypress-real-events` to `1.7.1`
- Rename `support/index.ts` / `support/index.js`  to  `support/e2e.ts`
- Remove `plugins/index.ts` if it is not used
- Rename test files `*.ts` to `*.cy.ts`
- Update `cypress.json` configuration to `cypress.config.ts`
- Rename `integration` directory to `e2e`

### CODE REVIEW

**Comment by tomasdavidorg** [comment]
@sjamboro FYI, pmml tests were also migrated.

**Review by jstastny-cz — COMMENTED** [review]
Why renaming integration to e2e? Afaik in case of standalone editors, the test is just checking rendering of existing assets, not sure it falls under e2e category. Is there any rule of thumb how the tests are being categorized?

**Comment by tomasdavidorg** [comment]
> Why renaming integration to e2e? Afaik in case of standalone editors, the test is just checking rendering of existing assets, not sure it falls under e2e category. Is there any rule of thumb how the tests are being categorized?

There are now two categories: e2e and component tests. https://www.cypress.io/blog/2022/06/01/cypress-10-release/#:~:text=The%20difference%20between%20component%20testing,end%20testing%20by%20calling%20cy. I believe the existing tests still fall into the e2e category.

**Comment by jstastny-cz** [comment]
> > Why renaming integration to e2e? Afaik in case of standalone editors, the test is just checking rendering of existing assets, not sure it falls under e2e category. Is there any rule of thumb how the tests are being categorized?
> 
> There are now two categories: e2e and component tests. https://www.cypress.io/blog/2022/06/01/cypress-10-release/#:~:text=The%20difference%20between%20component%20testing,end%20testing%20by%20calling%20cy. I believe the existing tests still fall into the e2e category.

Thank you, it's clear now.

**Review by jstastny-cz — APPROVED** [review]
LGTM

**Review by tiagobento — APPROVED** [review]
Great work, @tomasdavidorg !

**Pull request merged**
