### PR TITLE
KOGITO-6276: [DMN Designer] Integrate Import Java Classes component to JavaCodeCompletion service

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.redhat.com/browse/KOGITO-6276

Changes introduced in this PR:
- Removed mocks inside `dmn-loader` module for `import-java-classes`. I created a `JavaCodeCompletionService` to handle the LSP services. That service uses the reals JavaCodeCompletion API.
- The button status management is changed. Before this PR, the GWT layer was in charge to determine the status (enabled/disabled) of the button. Now, the status depends on the call results of `JavaCodeCompletionService.isLanguageServiceAvailable()`
- I defined a "debounce effect" when the user types the class name in the search box of the first step. This is to avoid multiple calls to the API during the key typing. Not sure is the best way to manage it, open to suggestions

** PLEASE NOTE: Currently I reported issues with the JavaCodeCompletionAPI, so I temporarily disabled the button. This means it is not possible to perform an end-2-end of the functionality. To test these changes with a mocked API, I suggest to user the showcase (go to `kie-tools/packages/import-java-classes/showcase` and type `yarn start`)

### CODE REVIEW

**Comment by tiagobento** [comment]
@yesamer I think this file `.vscode/settings.json` might be extra on this PR, can you please check?

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by yesamer** [comment]
jenkins retest this please

**Review by tiagobento — APPROVED** [review]

**Review by vpellegrino — APPROVED** [review]
LGTM, thanks @yesamer

**Comment by yesamer** [comment]
Hi @domhanak ! A kindly reminder for this PR review. Thank you!

**Comment by yesamer** [comment]
Hi @domhanak ! A kindly reminder for this PR review. Thank you!

**Comment by domhanak** [comment]
Feel free to proceed without my review, no free slot to do verify.

**Pull request merged**
