### PR TITLE
KOGITO-8032: Bump `vscode-extension-tester` version to 5.2

### PR DESCRIPTION
**Pull request by zdrapela**
**Jira:** https://issues.redhat.com/browse/KOGITO-8032

- `vscode-extension-tester` bumped to the latest available version: 5.2
- `vsce` bumped to latest version: 2.15.0 (now renamed to [`@vscode/vsce`](https://www.npmjs.com/package/@vscode/vsce))
- Version of VSCode to run test is now set to `max`, which points to latest version of VSCode that the `vscode-extension-tester` in the exact version supports, so the version of VSCode is still fixed and we only need to upgrade the `vscode-extension-tester` version. E.g. for `vscode-extension-tester` version 5.2, `max` = 1.73.1 (VSCode).
- It was needed to force `vsce` to ignore dependencies. Otherwise `vsce package` was failing. This was set in `package.json`s by adding `"vsce": {"dependencies": false}`.

Integration tests in packages `vscode-extension-pack-kogito-kie-editors`, `vscode-extension-serverless-workflow-editor` and `vscode-extension-yard-editor` ran locally 5x without errors.

### CODE REVIEW

**Comment by domhanak** [comment]
@yesamer FYI

@zdrapela nice work, thank you for the PR

**Comment by zdrapela** [comment]
The unability to easily bump the version of `vscode-extension-tester` was caused by change in `vsce`. Broader description is available in [this issue](https://github.com/redhat-developer/vscode-extension-tester/issues/519#issuecomment-1353008310).

**Review by yesamer — APPROVED** [review]
Thank you @zdrapela

**Comment by zdrapela** [comment]
Rebased to main to fix merge conflict.

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
