### PR TITLE
KOGITO-7500: Enable integrations tests for SWF editor extension (2) 

### PR DESCRIPTION
**Pull request by yesamer**
Trying to improve integration test stability.

### CODE REVIEW

**Comment by tiagobento** [comment]
@yesamer Did you observe any instabilities recently? We have a dedicated Jira for tracking those. See https://issues.redhat.com/browse/KOGITO-6643

**Comment by tiagobento** [comment]
Ok, just saw that it broke on the `main` branch CI. That's why they were disabled :/

**Comment by yesamer** [comment]
@tiagobento Really weird. I tested it locally many times and it was fine. When I opened the PR, it was fine. Anyway, let's try with this patch. If it fails again, I'll revert the change tomorrow.

**Comment by caponetto** [comment]
FYI I just observed the following error [on this run](https://github.com/kiegroup/kie-tools/runs/7202235553?check_suite_focus=true):
```
2022-07-05T20:20:28.0149433Z Launching tests...
2022-07-05T20:20:28.0149653Z 
2022-07-05T20:20:28.0150298Z   Serverless workflow editor - smoke integration tests
2022-07-05T20:20:38.9650270Z       1) Opens greetings.sw.json and loads two editor groups
2022-07-05T20:20:39.7351520Z Shutting down the browser
2022-07-05T20:20:40.4608786Z Uninstalling redhat.vscode-extension-serverless-workflow-editor...
2022-07-05T20:20:40.6198865Z Extension 'redhat.vscode-extension-serverless-workflow-editor' was successfully uninstalled!
2022-07-05T20:20:40.6621962Z 
2022-07-05T20:20:40.6622784Z   Suite duration: 12.648 s, Tests: 1
2022-07-05T20:20:40.6635733Z 
2022-07-05T20:20:40.6639689Z   0 passing (17s)
2022-07-05T20:20:40.6642609Z   1 failing
2022-07-05T20:20:40.6645414Z 
2022-07-05T20:20:40.6663203Z   1) Serverless workflow editor - smoke integration tests
2022-07-05T20:20:40.6663950Z        Opens greetings.sw.json and loads two editor groups:
2022-07-05T20:20:40.6664768Z 
2022-07-05T20:20:40.6665179Z       AssertionError: expected 0 to equal 7
2022-07-05T20:20:40.6665720Z       + expected - actual
2022-07-05T20:20:40.6666007Z 
2022-07-05T20:20:40.6666274Z       -0
2022-07-05T20:20:40.6666621Z       +7
2022-07-05T20:20:40.6666962Z       
2022-07-05T20:20:40.6667988Z       at Context.<anonymous> (out/serverless-workflow-editor-extension-smoke.test.js:115:39)
2022-07-05T20:20:40.6668881Z       at step (out/serverless-workflow-editor-extension-smoke.test.js:33:23)
2022-07-05T20:20:40.6837509Z       at Object.next (out/serverless-workflow-editor-extension-smoke.test.js:14:53)
2022-07-05T20:20:40.6838564Z       at fulfilled (out/serverless-workflow-editor-extension-smoke.test.js:5:58)
2022-07-05T20:20:40.6839211Z       at runMicrotasks (<anonymous>)
2022-07-05T20:20:40.6841654Z       at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
