### PR TITLE
[DO NOT MERGE] [WORK IN PROGRESS] Activate sonar checks for whole kie-tools

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by tiagobento** [comment]
@jomarko Since this is for everything, should we remove the old one that's only targeting `stunner-editors`?

**Comment by jomarko** [comment]
It is still work in progress, probably yes @tiagobento , will remove the old once new is working.

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by jomarko** [comment]
This PR is not ready for review!

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
is this still WIP?

**Pull request closed without merging**
