### PR TITLE
[0.26.2] KOGITO-8959: Take screenshots of failed VSCode extension integration tests

### PR DESCRIPTION
**Pull request by zdrapela**
Backporting the capability of taking screenshots of failed IT tests of VSCode extension from #1554 to 0.26.2

### CODE REVIEW

**Review by LuboTerifaj — COMMENTED** [review]
Hello @zdrapela , could you please update the cherry-picked commit message with [0.26.2] too? Thanks!

**Comment by zdrapela** [comment]
> Hello @zdrapela , could you please update the cherry-picked commit message with [0.26.2] too? Thanks!

Hey @LuboTerifaj , sure, no problem :+1:

**Review by paulovmr — APPROVED** [review]

**Comment by tiagobento** [comment]
Love the label! <3

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Pull request merged**
