### PR TITLE
kie-issues#965: Make sure `kie-tools` is using the latest timestamped SNAPSHOT from Kogito (999-20240403-SNAPSHOT)

### LINKED ISSUE #965: Make sure `kie-tools` is using the latest timestamped SNAPSHOT from Kogito (999-20240411-SNAPSHOT)
This depends on #960, as Kogito Runtimes is already on the Java 17, Maven 3.9.6, and Quarkus 3 stack.

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/965

### CODE REVIEW

**Comment by tiagobento** [comment]
We need to update `packages/kn-plugin-workflow` too, no?

**Comment by yesamer** [comment]
@tiagobento Good point, I noticed that @ederign just merged his PR. 
@ederign I can update the version in `kn-plugin-workflow` package as well, but I'm not familiar with the `go` code. What are the required steps to safely update it?

**Comment by ederign** [comment]
@yesamer I can do that!

**Comment by tiagobento** [comment]
@yesamer I think it's just a matter of updating `env/index.js` too.

**Comment by yesamer** [comment]
@tiagobento I'm afraid that is not enough. I noticed that some versions are present in the go files together with some dependency declarations (some of them have been renamed).
@ederign Thank you! Let me know if you want to include the changes in this PR or you prefer to manage it in a separate one.

**Comment by tiagobento** [comment]
@ederign @yesamer If possible, let's do a single PR? I think this PR can be used as a reference for writing a guide or for future updates we'll need.

**Comment by tiagobento** [comment]
@yesamer Please see https://github.com/apache/incubator-kie-tools/pull/2198#issuecomment-1998324557

**Comment by yesamer** [comment]
Updated to `20240317`

**Comment by yesamer** [comment]
Updated to `20240331`

**Comment by tiagobento** [comment]
🙏

**Review by tiagobento — APPROVED** [review]

**Review by thiagoelg — APPROVED** [review]

**Pull request merged**
