### PR TITLE
BXMSPROD-560 Revert "Remove yarn.lock (#20)" yarn.lock entry removed from .gitignore

### PR DESCRIPTION
**Pull request by Ginxo**

### CODE REVIEW

**Comment by tiagobento** [comment]
Hi @Ginxo. Thanks for engaging with `kogito-tooling`! Looks like our internal CI is failing with your changes.

@domhanak Can you help verifying that? I think that's related to our limitation with using the public NPM registry.

**Comment by Ginxo** [comment]
Taking a look.
I released a npm library to handle lock files problems https://www.npmjs.com/package/lock-treatment-tool
So just running `npm i lock-treatment-tool` and `locktt --registry=REGISTRY_URL` the yarn.lock resolved entries are updated.
The thing is we should assure the versioning integrity and lock files are the mechanism for that

**Comment by domhanak** [comment]
@Ginxo Could you please update the `Jenkinsfile` so that the build uses your tool?

**Comment by Ginxo** [comment]
@domhanak done!

**Comment by domhanak** [comment]
@Ginxo It looks like it is still not working like it should, I can still see it tries to access public registry.
May I suggest to install the tool globally on Jenkins slaves and just add `locktt --registry=REGISTRY_URL` step here? That is not solution to the issue, but I think it could be helpful in reducing the build time a tiny bit.

**Comment by tiagobento** [comment]
@Ginxo @domhanak @mareknovotny Could you guys provide me some guidance on why do you want the `yarn.lock` file back? FYI, we commit the `yarn.lock` file on our tags.

**Comment by Ginxo** [comment]
@tiagobento sure, the lock file absence could produce integrity problems in the future. We are currently having problems in projects like optaweb-vehicle-routing https://issues.jboss.org/browse/RHDM-1129 or  the appformer-js tests were failing due to the package-lock.json removal (there is no ticket for this one). Basically without the lock file we can't assure the project still working in the future.

**Comment by domhanak** [comment]
@Ginxo Do you mind sending this PR from a branch of your fork? It seem like current Jenkins implementation does not take you changes into account properly.

**Comment by Ginxo** [comment]
This is replaced by https://github.com/kiegroup/kogito-tooling/pull/32

**Pull request closed without merging**
