### PR TITLE
KOGITO-6193: Reactivate tests for DMN's new Boxed Expression component

### PR DESCRIPTION
**Pull request by jomarko**
This reverts commit 03c5cb7a9b80929af3b9c5fa44bafc75eacbea10.

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
Thanks for this PR @jomarko 
It re-enables existing tests

**Comment by tiagobento** [comment]
For this PR to pass, we need to release a new version of the Editors and upgrade it here too.

**Comment by jomarko** [comment]
@tiagobento could you help with that, or guide me how to do it please?

**Comment by tiagobento** [comment]
@yesamer Can you please assist Jozef on this matter?

**Comment by yesamer** [comment]
@jomarko Only an admin can release a new version of `kogito-editors-java`. I'll notice you when a new release will be created ( I think in the next very days)

**Comment by jomarko** [comment]
We will postpone the merge of this #662 until https://github.com/kiegroup/kogito-editors-java/pull/159, because that contains crucial fixes.

**Comment by jomarko** [comment]
@tiagobento please review and merge

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
