### PR TITLE
KOGITO-9831: SWF Editor - final migration to j2cl

### PR DESCRIPTION
**Pull request by treblereel**
jira: https://issues.redhat.com/browse/KOGITO-9831

### CODE REVIEW

**Comment by yesamer** [comment]
Hi @treblereel, a side note: I noticed you introduced some classes with `Copyright © 2023 Treblereel` header. I think that is not ideal according to the Apache rules. Is that header intended? If yes, can you please update the [NOTICE file](https://github.com/kiegroup/kie-tools/blob/main/NOTICE), using the same pattern already in place?  Thank you!

//cc @ederign @tiagobento

**Comment by treblereel** [comment]
> Hi @treblereel, a side note: I noticed you introduced some classes with `Copyright © 2023 Treblereel` header. I think that is not ideal according to the Apache rules. Is that header intended? If yes, can you please update the [NOTICE file](https://github.com/kiegroup/kie-tools/blob/main/NOTICE), using the same pattern already in place? Thank you!
> 
> //cc @ederign @tiagobento

Thanks for the tip, I'll double-check it.

**Review by handreyrc — CHANGES_REQUESTED** [review]
Hey @treblereel;

I noticed we are reintroducing the patternfly files removed in the [KOGITO-9728](https://github.com/kiegroup/kie-tools/pull/1937).
We have to keep the same approach. We cannot have those files as part of our source.

Could you check it please?

Thanks

**Comment by treblereel** [comment]
> Hey @treblereel;
> 
> I noticed we are reintroducing the patternfly files removed in the [KOGITO-9728](https://github.com/kiegroup/kie-tools/pull/1937). We have to keep the same approach. We cannot have those files as part of our source.
> 
> Could you check it please?
> 
> Thanks

Thank you, it ll be fixed

**Review by LuboTerifaj — COMMENTED** [review]
Hello @treblereel ,

### Code

There is still gwt used in some modules. Shouldn't be all its usages removed in this PR?

There is commented out code in the following Test classes. Could you please ensure there won't stay any leftovers?
- `EditorReadOnlyProviderTest`, `AbstractCanvasShortcutsControlImplTest`, `ElementProxyTest`, `CreateNodeToolboxActionTest`, `FlowActionsToolboxFactoryTest`, `GeneralCreateNodeActionTest`, `GroupActionsToolboxFactoryTest`, `MorphActionsToolboxFactoryTest`, `MorphNodeToolboxActionTest`, `SaveDiagramSessionCommandTest`, `StunnerEditorTest`

There is a commented out code in the following classes. Is there any reason why we need to keep it there?
- `AbstractModelBeanValidator`, `ModelBeanViolationImpl`, `ValidationSuccessNotification`, `WorkbenchEntryPoint`
	
There is a `TODO` in `org.uberfire.client.promise.Promises` class. Please ensure you don't forget on that.
		
	
### Behaviour
	
"null" instad of "undefined"  is shown in a tooltip when hovering over:
	
- Filter (StateDataFilter)
  - See [continuing-as-a-new-execution.sw.json](https://github.com/LuboTerifaj/specification/blob/examples-in-separate-files/examples/resources/continuing-as-a-new-execution.sw.json) file for example.
		
- Timeout
  - See [event-based-service-invocation.sw.yaml](https://github.com/LuboTerifaj/specification/blob/examples-in-separate-files/examples/resources/event-based-service-invocation.sw.yaml) file for example.
		
### Additional notes

Could you please resolve conflicts in your PR?

All integration tests passed. I didn't find any other issues.

Thank you!

**Comment by treblereel** [comment]
> Hello @treblereel ,
> 
> ### Code
> There is still gwt used in some modules. Shouldn't be all its usages removed in this PR?
> 
> There is commented out code in the following Test classes. Could you please ensure there won't stay any leftovers?
> 
> * `EditorReadOnlyProviderTest`, `AbstractCanvasShortcutsControlImplTest`, `ElementProxyTest`, `CreateNodeToolboxActionTest`, `FlowActionsToolboxFactoryTest`, `GeneralCreateNodeActionTest`, `GroupActionsToolboxFactoryTest`, `MorphActionsToolboxFactoryTest`, `MorphNodeToolboxActionTest`, `SaveDiagramSessionCommandTest`, `StunnerEditorTest`
> 
> There is a commented out code in the following classes. Is there any reason why we need to keep it there?
> 
> * `AbstractModelBeanValidator`, `ModelBeanViolationImpl`, `ValidationSuccessNotification`, `WorkbenchEntryPoint`
> 
> There is a `TODO` in `org.uberfire.client.promise.Promises` class. Please ensure you don't forget on that.
> 
> ### Behaviour
> "null" instad of "undefined" is shown in a tooltip when hovering over:
> 
> * Filter (StateDataFilter)
>   
>   * See [continuing-as-a-new-execution.sw.json](https://github.com/LuboTerifaj/specification/blob/examples-in-separate-files/examples/resources/continuing-as-a-new-execution.sw.json) file for example.
> * Timeout
>   
>   * See [event-based-service-invocation.sw.yaml](https://github.com/LuboTerifaj/specification/blob/examples-in-separate-files/examples/resources/event-based-service-invocation.sw.yaml) file for example.
> 
> ### Additional notes
> Could you please resolve conflicts in your PR?
> 
> All integration tests passed. I didn't find any other issues.
> 
> Thank you!

Thank you for your review!

**Review by handreyrc — APPROVED** [review]
@treblereel,

Everything looks good to me. I didn't find any regressions. 

Thanks!

**Comment by LuboTerifaj** [comment]
Running integration tests, I will let you know once they are finished.

**Review by LuboTerifaj — APPROVED** [review]
Hello @treblereel ,

Thanks for the updates.

I reported the issue that is not fixed here:

- https://issues.redhat.com/browse/KOGITO-9929

All tests passed and I didn't find any more issues.

**Comment by caponetto** [comment]
Hi @treblereel, I found a minor issue while comparing the changes in this PR with the current release of Serverless Logic Web Tools. Not a blocker but is it a known issue? 

You can see in red that an icon is missing when running it from this branch. The image below is the current release.

image

**Comment by treblereel** [comment]
> Hi @treblereel, I found a minor issue while comparing the changes in this PR with the current release of Serverless Logic Web Tools. Not a blocker but is it a known issue?
> 
> You can see in red that an icon is missing when running it from this branch. The image below is the current release.
> 
> image

@caponetto 
nope, it's not, lets file the issue, looks like font-awesome font is missed. 

And looks like it's specific to your case, coz in web/vscode it works as expected.

**Pull request merged**
