### PR TITLE
KOGITO-5883: Enhance forms codegen tool to add the needed JS interact with the channel.

### PR DESCRIPTION
**Pull request by pefernan**
Adding some enhancements on the form cli to add the required JS code that will connect the form with the envelope. It adds basic api to allow the user have some control over the form lifecycle and data-binding utilities.

### CODE REVIEW

**Comment by pefernan** [comment]
@paulovmr @tiagobento this PR isn't finished yet, will be doing some deep tests next week to find/fix possible issues. I just created the PR to see how it's doing with the checks :D

**Comment by tiagobento** [comment]
@pefernan What's the status of this PR? Should I review it? :D

**Comment by pefernan** [comment]
@tiagobento missed your message yea, we can review and merge hehe

**Comment by tiagobento** [comment]
@pefernan Ok!! Can you please rebase this PR?

**Comment by pefernan** [comment]
Done @tiagobento thanks!

**Comment by pefernan** [comment]
@tiagobento the build in windows is failing but I don't see the logs. Is it expectect windows to fail?

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
