### PR TITLE
KOGITO-6949: Upgrade selenium-webdriver

### PR DESCRIPTION
**Pull request by jomarko**
See https://issues.redhat.com/browse/KOGITO-6946

### CODE REVIEW

**Review by tomasdavidorg — APPROVED** [review]

**Review by yesamer — APPROVED** [review]

**Comment by caponetto** [comment]
Closing this one in favor of https://github.com/kiegroup/kie-tools/pull/923

**Comment by jomarko** [comment]
@caponetto hello, please are you aware this PR upgrades two more dependencies?
```
- "@types/selenium-webdriver": "^4.0.18"
- "selenium-webdriver": "^4.1.1",
 ```

**Comment by caponetto** [comment]
@jomarko That is right. Let's keep this PR then.

"selenium-webdriver": "^4.1.1" is still missing.

**Comment by jomarko** [comment]
@caponetto yes, thank you, I updated the PR to reflect your recent changes

**Review by caponetto — APPROVED** [review]

**Pull request merged**
