### PR TITLE
KOGITO-7623: Specs folder is not detected in Windows on SWF VSCode Extension

### LINKED ISSUE #1113: [VS Code] Kogito Serverless Workflow Editor - prompts for automatic opening on every json file
Kogito Serverless Workflow Editor VS Code extension - prompts for automatic opening on every plain `.json` file in every single project - if confirmed creates project settings.json file.

image

I would expect that the prompt should only appear on following files: (`*.sw.json`, `*.sw.yaml`, `*.sw.yml`) - otherwise it is pretty annoying. Also why project settings instead of top vs code settings?

Once the prompt appears it doesn't go away until you decide on one of the 2 options provided (there is not even ignore option) or to be exact it reappears on switching between any tabs.

### PR DESCRIPTION
**Pull request by thiagoelg**
Fixes https://issues.redhat.com/browse/KOGITO-7623
Fixes https://github.com/kiegroup/kie-tools/issues/1113
___

- Parse all files and directories paths as POSIX;
- Fix FsWatcher for specs files;
- Saves `kogito.yard.automaticallyOpenDiagramEditorAlongsideTextEditor` and `kogito.swf.automaticallyOpenDiagramEditorAlongsideTextEditor` settings to the user's `settings.json` file;
- Only show prompt for automatic opening diagram view for SWF or Yard files;

### CODE REVIEW

**Review by caponetto — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Comment by yesamer** [comment]
@thiagoelg @tiagobento Probably `yard-editor` is affected by the same issue... Can you please check and case fix it? The code should be the same.

**Review by ederign — APPROVED** [review]

**Comment by ederign** [comment]
@thiagoelg thanks for the quick fix!

**Review by yesamer — APPROVED** [review]
Thank you @thiagoelg !!

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me 🙂

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
