### PR TITLE
Bump editors version to 8.4.1

### PR DESCRIPTION
**Pull request by yesamer**
This PR updates all editors versions for all channels to 8.4.1, in order to enable the new Boxed Expression editor in DMN Designer.

### CODE REVIEW

**Review by vpellegrino — APPROVED** [review]
Thanks @yesamer!

**Comment by tiagobento** [comment]
I think this PR should be a part of #631, WDYT?

**Comment by yesamer** [comment]
Hey @tiagobento , I would prefer to proceed with separate PRs, in order to clearly separate the effects of the PRs. Moreover, I agreed with @vpellegrino to proceed in that way. In the end, there are no big differences, but that's my preference. thx!

**Comment by domhanak** [comment]
There is an issue in`chrome-extension-pack-kogito-kie-editors` tests @tomasdavidorg could you please check?

**Comment by tomasdavidorg** [comment]
@domhanak That should be fixed by https://github.com/kiegroup/kogito-tooling/pull/635. @yesamer Could you please rebase with the main branch?

**Comment by yesamer** [comment]
@tomasdavidorg @domhanak Done!

**Comment by domhanak** [comment]
@yesamer I checked the vscode tests locally with 8.4.1 editors and they passed. Looks like a CI instability.
Same tests passed in `monorepo-pr-ci-full`

**Comment by tiagobento** [comment]
@yesamer Ok, no problem. I was only concerned that #631 is loading a new JS file. But I'm guessing this file is not mandatory for the Editors to work properly and is only enabled by #631, right? So no issue :)

**Comment by yesamer** [comment]
> @yesamer Ok, no problem. I was only concerned that #631 is loading a new JS file. But I'm guessing this file is not mandatory for the Editors to work properly and is only enabled by #631, right? So no issue :)

That's correct @tiagobento, we need it only to activate #631. I don't expect issues with editors updating to version 8.4.1, but I think it's wise to proceed with separate PRs in order to avoid confusion in case of unexpected/side effects.

Can you please merge it whenever we have a green light here? Thx!

**Comment by yesamer** [comment]
@ederign @tiagobento Green lights here! Can you please review it and eventually merge it?

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
