### PR TITLE
KOGITO-6289: Regressions on copy/paste from other spreadsheet, after KOGITO-5078

### PR DESCRIPTION
**Pull request by ljmotta**
This PR updates the CSS class name that was modifed on https://github.com/kiegroup/kogito-editors-java/pull/181

### CODE REVIEW

**Comment by tiagobento** [comment]
This PR needs a new version of `kogito-editors-java` to be merged. CI won't pass until it is upgraded.

**Comment by tiagobento** [comment]
@ljmotta Yeser will do a release on Monday, so we can upgrade `kogito-tooling` with this new version.

@yesamer ^

**Comment by jomarko** [comment]
@tiagobento will be this versioning of `kogito-editors-java` needed also after we migrate that repository into monorepo?

Or then the actual `kogito-editors-java` code will be also used in all kogito channels?

**Review by jomarko — APPROVED** [review]

**Comment by tiagobento** [comment]
@jomarko No. Yeser will do a final release before the migration. After the migration is done, everything will be here on `kogito-tooling`, so we won't need to worry about this. :)

**Comment by tiagobento** [comment]
@ljmotta Can this one be closed? Was it included as part of #723 ?

**Comment by ljmotta** [comment]
@tiagobento Yes! it can.

**Pull request closed without merging**
