### PR TITLE
Update editors to latest snapshot 7.33.0-SNAPSHOT

### PR DESCRIPTION
**Pull request by tiagobento**

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Review by romartin — APPROVED** [review]
@tiagobento  @ederign 

Tested and it works for me, thanks!

**Although** let you know guys, that from VSCode, saving is not working for me... although I tested the stadanlone webapp runtime, and via API I can otain the right BPMN content, so I understand the process editor is working properly, but there is an issue somewhere on the integration between VSCode and the edtiors API. Does that makes sense?

Thx!

**Comment by ederign** [comment]
@romartin save menu is disable since last VSCode release. Did you try with ctrl/cmd+s ? @tiagobento can you please take a look at this?

**Comment by tiagobento** [comment]
@romartin Tested it and indeed saving is not working. I'm trying to find the cause. Will post here as soon as I find it.

**Comment by tiagobento** [comment]
@romartin @ederign Fixed on cffd3f6. There was a discrepancy between messages send and messages received. Tested locally and it works.

**Pull request merged**
