### PR TITLE
KOGITO-6974: Stunner Editors - Line control points are enabled in view only mode, but they should not

### PR DESCRIPTION
**Pull request by yesamer**
Part of https://github.com/kiegroup/kie-issues/issues/47 initiative

This is a 1:1 cherrypick of https://github.com/kiegroup/kie-tools/pull/943

@inodeman can you please review it?

### CODE REVIEW

**Review by inodeman — APPROVED** [review]
Hi @yesamer looks good, I remember this change in SWF.

**Comment by jomarko** [comment]
@yesamer hi, what is the use case of DMN read only mode in current kie tooling. Is it in the chrome extension? I am not aware of readonly mode available in VSCode or Sandbox. Is that correct?

**Comment by yesamer** [comment]
> @yesamer hi, what is the use case of DMN read only mode in current kie tooling. Is it in the chrome extension? I am not aware of readonly mode available in VSCode or Sandbox. Is that correct?

@jomarko IIRC it's on chrome extension only, yes

**Comment by jomarko** [comment]
@yesamer thank you, checking.

**Review by jomarko — APPROVED** [review]
Works fine

**Comment by yesamer** [comment]
@tiagobento Can I have a merge here? Thanks

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
