### PR TITLE
KOGITO-7325: Merge kie-editors-standalone reports into one file

### PR DESCRIPTION
**Pull request by domhanak**

### CODE REVIEW

**Review by tomasdavidorg — APPROVED** [review]

**Comment by domhanak** [comment]
Looks like mac and windows do not like this change I am looking for a fix.

**Review by jomarko — APPROVED** [review]
Verified locally as:
1. pnpm boostrap
2. pnpm -r -F kie-editors-standalone... build:prod 
3. export KIE_TOOLS_BUILD_testIT=true
4. pnpm -r -F kie-editors-standalone test:it

Thank you

**Review by yesamer — APPROVED** [review]
@domhanak Can I merge this?

**Comment by domhanak** [comment]
@yesamer yes  please

**Pull request merged**
