### PR TITLE
KOGITO-5108: Fix "Reopen As Diagram" flow

### PR DESCRIPTION
**Pull request by caponetto**
See [KOGITO-5108](https://issues.redhat.com/browse/KOGITO-5108)

**Demo**
KOGITO-5108

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
Great fix! Thanks @caponetto!

**Review by ederign — APPROVED** [review]

**Comment by domhanak** [comment]
Seems to be working when I set the KIE Editors as default ones in VSCode. I ran into an issue where after installing the extension BPMN, DMN, SCESIM files were open in text ediotr by default. I had to set KIE editors as default first to be able to test the issue. Is that expected?

Other than that I was able to complete the expected workflow on all files we support (bpmn, dmn, scesim). Thanks!

**Review by domhanak — APPROVED** [review]

**Comment by caponetto** [comment]
> Seems to be working when I set the KIE Editors as default ones in VSCode. I ran into an issue where after installing the extension BPMN, DMN, SCESIM files were open in text ediotr by default. I had to set KIE editors as default first to be able to test the issue. Is that expected?
> 
> Other than that I was able to complete the expected workflow on all files we support (bpmn, dmn, scesim). Thanks!

Hi @domhanak, thanks for taking a look at this!
I don't believe this behavior is related to the changes.
Can you please share a video or gif of the steps so I can try to reproduce and understand what's going on?

**Comment by domhanak** [comment]
@caponetto Definitely not related, I just asked it here because I found out during checks of this PR. I will report as a JIRA if I confirm. Thanks for the fix!

**Pull request merged**
