### PR TITLE
AF-2004: Configure CI tooling for Kogito - PR Check

### PR DESCRIPTION
**Pull request by domhanak**
@ederign @tiagobento Please take a look. This adds pull request checks. Simple example is here: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-tooling/ It builds my fork for now I will switch it to this repo in CI.

Two notes. I will be updating the label once we have new slave image with required changes. Once this is merged I will fine tune it.

Changes to slaves are in this PR:
https://github.com/kiegroup/kie-jenkins-scripts/pull/508

### CODE REVIEW

**Comment by tiagobento** [comment]
@domhanak Thanksf or the PR! Looked at the Jenkins link you provided and noticed some weird logs when runninng the vscode-extension integration tests about "Git Error".. did you see that?

```
{ message: 'Git error',
appformer-js-vscode-extension:   stdout: '',
appformer-js-vscode-extension:   stderr:
appformer-js-vscode-extension:    'fatal: Could not switch to \'/home/jenkins/workspace/_kogito_kogito-tooling_PR-9-K73C7XFUKBEDC7DPT4TUSC7MEKV72T4CSZIWO76J5IBSZM5TKIOQ/kogito-tooling/packages/vscode-extension/.vscode-test/vscode-1.36.1/VSCode-linux-x64/resources/app/out/vs/workbench/contrib/welcome/page/browser/\': No such file or directory\n',
appformer-js-vscode-extension:   exitCode: 128 }
```

Also, these integration tests do not appear to be showing up on this list https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/kogito/job/kogito-tooling/view/change-requests/job/PR-9/lastBuild/testReport/(root)/. Maybe it's because we didn't enable the `jest-junit` plugin?

**Comment by domhanak** [comment]
@tiagobento Yes, probably. I am investigating and fixing, in case you already have it let me know. Maybe we could try going with https://www.npmjs.com/package/jest-jenkins-reporter instead, I don't think that there is a need for junit reports here.

**Comment by tiagobento** [comment]
@domhanak Sounds good. Let me know when I can review this PR again.

**Comment by domhanak** [comment]
So the tests are run by mocha so I added the `mocha-jenkins-reporter` and now the report is generated. however, the git error is still present. Investigation is ongoing... I am consulting with our CI colleagues :) 
Edit: Locally it works, on Jenkins we have failure due to `git error'; the reports are not generated and the builds fails.

**Comment by tiagobento** [comment]
@domhanak ok, that's nice! we have good reports on a CI now. Do you want to merge this PR as is and work on the Git Error fix on a separate PR?

**Comment by domhanak** [comment]
@tiagobento Feel free to merge, issue is reported.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
