### PR TITLE
KOGITO-7740: KN Workflow plugin does not allow to use RHBQ version

### PR DESCRIPTION
**Pull request by ljmotta**
## JIRA
https://issues.redhat.com/browse/KOGITO-7740

## On this PR
- Add `[--quarkus-platform-group-id|-G]` to change the the Quarkus platform group Id.
- Add a P flag for `--quarkus-version`. Now, the Quarkus version can be also changed with the  `-V` flag.
- Remove the `--kogito-version` flag, as it should be determined by the quarkus-kogito-bom.
- Remove the `config` subcommand as it should manipulate the bom version instead of extension versions.

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by jstastny-cz** [comment]
Does any of the checks produce the plugin binary to test or should I checkout the branch?

**Comment by caponetto** [comment]
@jstastny-cz The artifacts associated with this PR are available in the last `CI :: Monorepo` run of this PR [1].

[1] https://github.com/kiegroup/kie-tools/actions/runs/2836163777

**Comment by cimbalek** [comment]
@ljmotta Hi, do we track changes in documentation related to this PR anywhere, please?

**Comment by jstastny-cz** [comment]
I've been able to run successfully command as
`kn workflow create --name serverless-workflow-hello-world --extension quarkus-jsonp,quarkus-smallrye-openapi -G com.redhat.quarkus.platform -V 2.7.6.Final-redhat-00006`
Looking at the output, there seems to be some unintended fragment popping up in console:
```
✅ Checking dependencies...
 - Java version check.
 - Maven version check.
-DplatformVersion=2.7.6.Final-redhat-00006Creating a Kogito Serverless Workflow project...
Workflow file created on ./serverless-workflow-hello-world/src/main/resources/workflow.sw.json 
🚀 Project creation took: 6.075902689s 
```
specifically `-DplatformVersion=2.7.6.Final-redhat-00006` 3rd line from the bottom.

**Comment by ljmotta** [comment]
@cimbalek These changes will be added in the https://github.com/kiegroup/kogito-docs/pull/135

@jstastny-cz Thanks for testing. Indeed I forgot a log there while I was testing. Could you please re-test? Also, regarding the https://issues.redhat.com/browse/KOGITO-7742, with those fixes, the default bom (quarkus-kogito-bom) should be generated.

Edit:
You can download the updated version here https://github.com/kiegroup/kie-tools/actions/runs/2839520279

**Review by jstastny-cz — APPROVED** [review]
LGTM, thanks.

**Review by paulovmr — APPROVED** [review]

**Pull request merged**
