### PR TITLE
kie-issues#833: Move all UI packages from `kogito-apps` to `kie-tools`

### PR DESCRIPTION
**Pull request by thiagoelg**
Reference: https://github.com/apache/incubator-kie-issues/issues/833

## Summary of the migration

Migrated packages from kogito-apps:
- management-console-webapp -> runtime-tools-management-console-webapp
- runtime-tools-dev-ui-webapp -> runtime-tools-process-dev-ui-webapp
- task-console-webapp -> runtime-tools-task-console-webapp

All dependencies of those packages that weren't previously migrated were migrated as well and were distributed across the new or renamed packages:
- runtime-tools-components
- runtime-tools-cypress-ouia
- runtime-tools-process-enveloped-components
- runtime-tools-process-gateway-api
- runtime-tools-process-webapp-components
- runtime-tools-shared-enveloped-components
- runtime-tools-shared-gateway-api
- runtime-tools-shared-webapp-components
- runtime-tools-swf-enveloped-components
- runtime-tools-swf-gateway-api
- runtime-tools-swf-webapp-components

## Unit and end-to-end tests

Most unit tests were stripped out of those packages since they weren't really testing anything.
End-to-end tests were also stripped out but may come back at a later stage, they were not considered right now due to the time it would take to set it up.

## Testing and validating this PR locally

Follow the steps below:

To fetch the branch from my fork without adding my fork as a remote, use this command:
```
git fetch https://github.com/thiagoelg/kie-tools.git kogito-apps-migration:kogito-apps-migration
```
then checkout the `kogito-apps-migration` branch.

Build the new packages with:
```
pnpm -F runtime-tools-management-console-webapp... -F runtime-tools-process-dev-ui-webapp... -F runtime-tools-task-console-webapp... build:dev
```

Then run them individually:
```
RUNTIME_TOOLS_MANAGEMENT_CONSOLE_WEBAPP__kogitoDataIndexUrl=<data_index_url> pnpm -F runtime-tools-management-console-webapp start
```
```
RUNTIME_TOOLS_PROCESS_DEV_UI_WEBAPP__kogitoDataIndexUrl=<data_index_url> pnpm -F runtime-tools-process-dev-ui-webapp start
```
```
RUNTIME_TOOLS_TASK_CONSOLE_WEBAPP__kogitoDataIndexUrl=<data_index_url> pnpm -F runtime-tools-task-console-webapp start
```

**You may also run the `dev` command instead of `start` to use the mock server (in this case, setting the environment variable is not necessary).**

### CODE REVIEW

**Comment by paulovmr** [comment]
Hi @thiagoelg , trying to run the steps provided for the Dev UI test here. Although I passed a different data index URL as a parameter, the webapp keeps requesting http://localhost:4000.

**Comment by thiagoelg** [comment]
> Hi @thiagoelg , trying to run the steps provided for the Dev UI test here. Although I passed a different data index URL as a parameter, the webapp keeps requesting http://localhost:4000.

Latest commit should fix that, hopefully

**Comment by paulovmr** [comment]
@thiagoelg Another thing that I think will be necessary to test the standalone Dev UI webapp is a parameter to set where the runtime service is running. This is because the Process Definitions tab does a request to `/q/openapi.json`, and normally this would work (when the real Dev UI extension is running along with the Quarkus service, at the same host and port). But, because this webapp runs in parallel to the Quarkus service in this local test environment, it has to make the request to `$RUNTIME_QUARKUS_SERVICE/q/openapi.json`. The default value could be empty string for when the Dev UI is being used, and it could be set the same way as the data-index URL for a test environment.

**Comment by pefernan** [comment]
@paulovmr @thiagoelg I already provided a fix for this here https://github.com/thiagoelg/kie-tools/pull/25

this also includes a fix for TaskInbox to enable impersonatino in dev-ui

**Comment by thiagoelg** [comment]
Thank you for the fixes and adjustments @pefernan! They're merged now.

**Comment by pefernan** [comment]
@thiagoelg you went too fast :)
I found a problem in `TaskInbox`, the `LoadingComponent` doesn't appear when launching a query [here](https://github.com/apache/incubator-kie-tools/pull/2180/files#diff-17fa65cf6354d088c18b7d4257ea6c9e78c416820f9ce5732a3c5270cdbb69ddR149). I'll be taking a look tomorrow

**Comment by thiagoelg** [comment]
> @thiagoelg you went too fast :) I found a problem in `TaskInbox`, the `LoadingComponent` doesn't appear when launching a query. I'll be taking a look tomorrow

No worries, I'll give you access to my fork so you can push straight to this branch. Thanks!

**Comment by pefernan** [comment]
@thiagoelg I just pushed a new commig restoring the Loading spinner in `TaskInbox`. I had to do a fix in `DataTable` to generate the right table column definition when loading. TBH I wasn't very familiar with this component code, but I think it deserves some refactor when we have time.

For now, if there are no other comments (or if I don't find any other issue while testing), I'll jump into https://github.com/apache/incubator-kie-issues/issues/963

**Comment by tiagobento** [comment]
@pefernan Tiny conflict here... Simply accepting whatever is on `main` and running ` pnpm bootstrap` should fix it though :)

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
