### PR TITLE
KOGITO-6291: Error "java.lang.ClassNotFoundException: org.glassfish.j…

### PR DESCRIPTION
**Pull request by jesuino**
…ersey.client.JerseyClientBuilder" when using remote dataset

-

Fixes for DB Runtime remote data set provider

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by sthundat** [comment]
Hi @jesuino ,
Thanks for the PR.
I have tried to set up the jar locally ,but  getting RuntimeException in the console log when importing kieserver dashboard.
`Error registering dataset: java.lang.RuntimeException: Configuration for remote datasettest1 not found`.

So do I need to set any configuration to enable the kieserver?

Thanks,
Savitha

**Comment by jesuino** [comment]
Hello Savitha, thanks for looking into this!

You will need to setup Kie Server connection using the following system properties:
```
dashbuilder.kieserver.serverTemplate.{server template}.location
dashbuilder.kieserver.serverTemplate.{server template}.user
dashbuilder.kieserver.serverTemplate.{server template}.password
```

here's an example:

```
java -jar -Dquarkus.http.port=8180 \
          -Ddashbuilder.runtime.multi=true \
          -Ddashbuilder.import.base.dir=$MODELS_DIR \
          -Ddashbuilder.dev=true \
          -Ddashbuilder.kieserver.serverTemplate.sample-server.location=http://localhost:8280/kie-server/services/rest/server \
          -Ddashbuilder.kieserver.serverTemplate.sample-server.user=kieserver \
          -Ddashbuilder.kieserver.serverTemplate.sample-server.password=kieserver1! $DASHBUILDER_RUNTIME
```

Please let me know if it works. Thanks!

**Comment by sthundat** [comment]
@jesuino 
Hi William,

I am able to import  kieserver dashboard on dasbuilder runtime with above system properties,and its working fine as shown below **if kieserver is separately installed on the specified port.**
image

So I would recommend to document it as a precondition that kieserver should up and running on some port when using `dashbuilder-runtime-app-runner.jar`

Also multi dashboard import is not working correctly.I don't see `Import Dashboards` button in the page even though I have enable `-Ddashbuilder.runtime.multi=true ` property.Please let me know if I missed anything

Thanks,
Savitha

**Comment by jesuino** [comment]
Hello @sthundat 

Thanks for checking this PR!

To enable upload you must set the system property `dashbuilder.runtime.allowUpload` to true. It will be documented in our release blog post!

>So I would recommend to document it as a precondition that kieserver should up and running on some port when using dashbuilder-runtime-app-runner.jar

Thanks, we will make it clear in the setup document for the demos dashboards.

**Review by sthundat — APPROVED** [review]
@jesuino Thanks William for the details

**Comment by sthundat** [comment]
@tiagobento 
Hi Tiago,
Thanks for merging.Can you please change `waiting for qe` label from the PR.I can see the same label in previously merged PR as well.
Thanks in advance,
Savitha

**Pull request merged**
