### PR TITLE
KOGITO-286: VSCode editor path issues on Windows

### PR DESCRIPTION
**Pull request by tiagobento**
See more details on JIRA.

### CODE REVIEW

**Comment by domhanak** [comment]
Having issues with my windows virtual so I am unable to verify this at the moment.

**Comment by domhanak** [comment]
@tiagobento FYI: `AppFormerJsActivityLoader` has a line `return loadScript(gwtModuleName + "/" + scriptFilename.get())` Just thought it could be a problem too so mentioning it here.

**Comment by tiagobento** [comment]
@domhanak Thx! But this method loads scripts in the browser so there's no "backslash" issue :)

**Comment by tiagobento** [comment]
@domhanak Are we good to merge?

**Review by ederign — APPROVED** [review]

**Comment by domhanak** [comment]
@tiagobento Sorry I didnt have the means to test it :(

**Pull request merged**
