### PR TITLE
KOGITO-3808: Fix Keyboard Shortcuts modal title on VS Code dark theme

### PR DESCRIPTION
**Pull request by ljmotta**
## Task
https://issues.redhat.com/browse/KOGITO-3808

### CODE REVIEW

**Comment by tiagobento** [comment]
@tomasdavidorg We keep seeing this error show up on our FDB build.. did you check what's going on there?

**Comment by tiagobento** [comment]
@ljmotta Nice work! Did you check whether this fix increases our bundle size?

**Comment by ljmotta** [comment]
> @ljmotta Nice work! Did you check whether this fix increases our bundle size?

I hadn't check. The bundle got 14kb bigger, I'll try to keep it small.

**Comment by ljmotta** [comment]
@tiagobento  I've managed to remove the bundle size increase :grin:

**Review by tiagobento — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
> @tomasdavidorg We keep seeing this error show up on our FDB build.. did you check what's going on there?

Hi @tiagobento I tried to check but I was not able to reproduce it. The screenshot show GitHub error 404 but the link should be correct. :-/ 

screenshot_after_BpmnTest

Online editor tests passed, so the problem is only in chrome extension tests.

**Review by tomasdavidorg — APPROVED** [review]

**Pull request merged**
