### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by caponetto**
### JIRA
https://issues.redhat.com/browse/RHPAM-3546

**Note**: https://github.com/kiegroup/kogito-tooling/pull/315 can be closed after merging this PR.

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by domhanak** [comment]
@caponetto Could you please re-trigger the builds? I see VSCode tests failed, but I can't reproduce locally, so I would like to check if this is some network issue.

**Comment by caponetto** [comment]
@domhanak apparently, https://vscode-update.azurewebsites.net/latest/linux-x64/stable is out of reach but I'll re-trigger the builds.

**Comment by domhanak** [comment]
@caponetto Ahh, yea. Forgot to check that url. :facepalm: 

 Let me check if it is something that can be fixed, but this PR should be ok to merge from VSCode pov.

**Review by domhanak — APPROVED** [review]
VSCode failures are related to inaccessible URL.

**Comment by caponetto** [comment]
@domhanak I think they've changed the URL from https://vscode-update.azurewebsites.net/ to https://update.code.visualstudio.com/. 
Do you know where does this URL come from? Maybe we need to upgrade another package as well.

**Comment by caponetto** [comment]
Found it: https://github.com/redhat-developer/vscode-extension-tester/commit/7949e411062a1da2630abd0c0f249c988128e72b

**Comment by caponetto** [comment]
@domhanak our VS Code integration tests are passing again after upgrading `vscode-extension-tester` (see https://github.com/kiegroup/kogito-tooling/pull/461/commits/24e90f7a478c7ffcd34d62d45e300da80c31b0de). :)

@tiagobento feel free to merge this PR.

**Comment by domhanak** [comment]
@caponetto Thanks! I got on it this morning, indeed upgrading to 4.0.2 is the solution. Lovely!

**Pull request merged**
