### PR TITLE
KOGITO-7331, KOGITO-7332 : Missing data when the serverless workflow definition is unmarshalled, Editor adds non-required attribute to serverless workflow definition

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin can you review this PR?

### CODE REVIEW

**Comment by romartin** [comment]
thanks @inodeman , will take a look asap. BTW could you use some title for this PR that describes better the scope for this change? Just because this text will result on the commit message once merging, so will stay there for looong time... :)
If applies, also let's change the JIRA ticket's title and/or scope.
thx

**Comment by tiagobento** [comment]
@inodeman Is this PR still WIP?

**Comment by inodeman** [comment]
Hi @tiagobento build failed for some reason, re-checking it and then will refire build

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
Hey @domhanak 
Here is a quick fix. Can you please do a quck review on this, once possible?
Thanks in advance!

**Comment by romartin** [comment]
Please @inodeman also make sure that the JIRA's properly describe the fix/es in this PR, otherwise let's reduce the scope and move whatever is missing to another ticket. Thanks!

**Comment by inodeman** [comment]
Hi @romartin I added a comment on Jira to mention that the transition part will not be fixed on this ticket, let me know if ok this way.

**Comment by romartin** [comment]
Hey @domhanak Missing QE review here please, thanks!

**Review by domhanak — APPROVED** [review]

**Comment by domhanak** [comment]
@romartin @tiagobento please merge

**Pull request merged**
