### PR TITLE
Update Stunner / BPMN / SWF Editor README's.

### PR DESCRIPTION
**Pull request by romartin**
Just an update for the developer docs for Stunner, BPMN and SWF Editors. I have significantly simplified the docs to make those more friendly and easy to get started, also updated some texts and links.

### CODE REVIEW

**Comment by romartin** [comment]
Can you please  @hasys quickly review this? Thanks in advance!

**Review by hasys — APPROVED** [review]
Looks good to me, thank you @romartin

**Review by domhanak — APPROVED** [review]
LGTM, maybe we could ask someone from doc to review in terms of language/phrasing so that is aligns with best-practices more.

**Comment by romartin** [comment]
@domhanak @ederign is anyone from docs able to help us on writing tech docs or readme's? Is it still Heena? WDYT?

**Review by yesamer — APPROVED** [review]

**Comment by romartin** [comment]
Merging for now, I need this for exposing to the community asap.

**Pull request merged**
