### PR TITLE
kie-issues#1017: `@kie-tools/dmn-marshaller` not respecting `xsd:sequence` declaration order when building XML from JSON

### LINKED ISSUE #1017: `@kie-tools/dmn-marshaller` not respecting `xsd:sequence` declaration order when building XML from JSON
The DMN generated by the editor has a wrong order of tags, so it fails server-side validation. e.g.

```xml
<?xml version="1.0" encoding="UTF-8" ?>
<definitions xmlns="https://www.omg.org/spec/DMN/20230324/MODEL/"
             xmlns:dmndi="https://www.omg.org/spec/DMN/20230324/DMNDI/"
             xmlns:dc="http://www.omg.org/spec/DMN/20180521/DC/"
             xmlns:di="http://www.omg.org/spec/DMN/20180521/DI/"
             xmlns:kie="https://kie.org/dmn/extensions/1.0"
             expressionLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/"
             namespace="https://kie.org/dmn/_2EB804A4-F189-4760-B5EE-958E8A9B0698"
             id="_37767BAF-637D-4335-8B04-C49751F65C8B"
             name="DMN_B927F160-91C2-4323-9D93-2786F1515F93">
    <itemDefinition id="_F93DAF7C-EB5C-4B55-8AF7-93F8930FC1D7" name="tNumbers" isCollection="true" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">
        <typeRef>number</typeRef>
    </itemDefinition>
    <itemDefinition id="_4C0B617F-B4B4-470F-8D25-352B776CD471" name="Insert a name" isCollection="false" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">
        <typeRef>Any</typeRef>
    </itemDefinition>
  <decision name="listreplacenumbers" id="_C45AC76B-980D-4704-8A2D-F5F39C139A27">
    <variable name="listreplacenumbers" id="_65D489B8-1B51-46AB-BD8D-AB6584F9984F" typeRef="tNumbers" />
    <literalExpression id="_B11FC270-1577-48C0-BE1F-76C87937E921" label="listreplacenumbers" typeRef="tNumbers">
      <text>list replace ( [2, 4, 7, 8], 3, 6)</text>
    </literalExpression>
  </decision>
  <dmndi:DMNDI>
    <dmndi:DMNDiagram id="_232368C2-CEDD-4012-9663-4534E8E377A6" name="Default DRD" useAlternativeInputDataShape="false">
<!--      <dmndi:DMNShape id="_90912CA8-C0FA-4C44-9253-AF12E4F81EBA" dmnElementRef="_C45AC76B-980D-4704-8A2D-F5F39C139A27" isCollapsed="false" isListedInputData="false">-->
<!--        <dc:Bounds x="300" y="240" width="160" height="80" />-->
<!--      </dmndi:DMNShape>-->
      <di:extension>
        <kie:ComponentsWidthsExtension>
          <kie:ComponentWidths dmnElementRef="_B11FC270-1577-48C0-BE1F-76C87937E921">
            <kie:width>190</kie:width>
          </kie:ComponentWidths>
        </kie:ComponentsWidthsExtension>
      </di:extension>
        <dmndi:DMNShape id="_90912CA8-C0FA-4C44-9253-AF12E4F81EBA" dmnElementRef="_C45AC76B-980D-4704-8A2D-F5F39C139A27" isCollapsed="false" isListedInputData="false">
            <dc:Bounds x="300" y="240" width="160" height="80" />
        </dmndi:DMNShape>
    </dmndi:DMNDiagram>
  </dmndi:DMNDI>
<!--  <itemDefinition id="_F93DAF7C-EB5C-4B55-8AF7-93F8930FC1D7" name="tNumbers" isCollection="true" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">-->
<!--    <typeRef>number</typeRef>-->
<!--  </itemDefinition>-->
<!--  <itemDefinition id="_4C0B617F-B4B4-470F-8D25-352B776CD471" name="Insert a name" isCollection="false" typeLanguage="https://www.omg.org/spec/DMN/20230324/FEEL/">-->
<!--    <typeRef>Any</typeRef>-->
<!--  </itemDefinition>-->
</definitions>
```
(commented tags: originally created by editor, wrong place)

[XSD](https://github.com/apache/incubator-kie-drools/blob/4004fe9bf745c5eae18223cd1d3a42d8efd4566e/kie-dmn/kie-dmn-validation/src/main/resources/org/kie/dmn/validation/org/omg/spec/DMN/20230324/DMN15.xsd) excerpt: the sequence definition dictate the order of the elements

```xml
<xsd:complexType name="tDefinitions">
		<xsd:complexContent>
			<xsd:extension base="tNamedElement">
				<xsd:sequence>
					<xsd:element ref="import" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="itemDefinition" type="tItemDefinition" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="drgElement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="artifact" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element name="elementCollection" type="tElementCollection" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="businessContextElement" minOccurs="0" maxOccurs="unbounded"/>
					<xsd:element ref="dmndi:DMNDI" minOccurs="0" maxOccurs="1"/>
				</xsd:sequence>
```

### PR DESCRIPTION
**Pull request by tiagobento**
Closes https://github.com/apache/incubator-kie-issues/issues/1017

The solution consisted of:
1. Changing the order in which the properties are read from the XSD. Inherited properties go first.
2. Traversing the Meta mapping together with the JSON object tree, being aware of current prop type.
3. Iterating through JSON object props in the order declared in the Meta mapping.

I also renamed some types and variables.

### CODE REVIEW

**Comment by gitgabrio** [comment]
HI @tiagobento thanks for PR.
IMO, the root problem is the usage of a completely custom-made marshaller (IIUC the code).
Such approach never works in real use case, simple reason is that xsd are big, they keep changing, and keep the code in sync with changes requires a lot of time and is error prone.
Even if this modificaiont fix the current problem, it is just one, and probably there are multiple ones that are never been discovered only because not tested.
The very fact that we found multiple bugs in two hours, testing only five extremely simple models, and none of them is 1.5 specific, should be a clear demonstration of that.
I may see this as temporary solution, but I think a different approach is needed here.
Anyway, this is not my area, and I have not your knowledge, so the final choice is yours.

Last note: one of the reason all those bugs (and who knows how many other) has been uncovered until now is that for testing purpose the tooling used hand-made models that were driven by the knowledge of the creators, and clearly lack lot of features. Our codebase is stuffed of "real" models, made by DMN experts, and those are much more representative.

**Comment by yesamer** [comment]
@tiagobento Thank you for your quick reaction to fix that issue.

@gitgabrio The solution of having our custom xml <--> json marshaller was largely discussed and agreed upon with the tooling team. I agree with you that reinventing the wheel should always be avoided, but in this case.. we didn't have a wheel! 
It can be hard to believe, but there's no reliable, well-maintained xml <--> json marshaller in npm libraries. @pefernan spent a lot of time analyzing and assessing all the available solutions, and no one fits our needs. Hard to believe but that is. I checked that by myself and I confirm that.  [jsonx](https://github.com/highsource/jsonix) you mentioned would be a good candidate... but the project is dead, sadly because the [project's maintainer is dead](https://github.com/highsource/jsonix/issues/255).
Regarding the quality and reliability of the solution, we tested it with a very representative DMN files, and the results were very promising from the beginning. The new DMN editor is based on that marshaller, and I believe that everyone working on that can confirm the reliability of the marshaller.
The new scesim editor is based on that marshaller as well, and I can confirm its reliability. I found just a bug that Tiago immediately fixed.

**Comment by gitgabrio** [comment]
@yesamer 
Thanks for the explanation! Yes, it is surprising! Being that the situation, can't say anything more....
@tiagobento Pls ignore my comment 🏳️

**Review by yesamer — APPROVED** [review]
Tested it. It works. Thank you @tiagobento

**Pull request merged**
