### PR TITLE
KOGITO-7125: QE serverless logic - examples verification - Iteration 1

### PR DESCRIPTION
**Pull request by domhanak**
Iteration number one of examples. Iteration zero was #1097 

Current issues:
https://issues.redhat.com/browse/KOGITO-7591
https://issues.redhat.com/browse/KOGITO-7608
https://issues.redhat.com/browse/KOGITO-7599
https://issues.redhat.com/browse/KOGITO-7594
https://issues.redhat.com/browse/KOGITO-7609

_More to be added - you can see some examples are not loading_

To run build the the `serverless-workflow-diagram-editor` and then navigate to `sw-editor/sw-editor-kogito-app` and run `mvn verify`

### CODE REVIEW

**Comment by domhanak** [comment]
@Josephblt @romartin 
```
[ERROR]   SWEditorSeleniumIT.testCustomerCreditCheckExample:161->testExample:178->waitCanvasPanel:203 » Timeout
[ERROR]   SWEditorSeleniumIT.testJobMonitoringExample:166->testExample:178->waitCanvasPanel:203 » Timeout
[ERROR]   SWEditorSeleniumIT.testSendCloudEventOnProvisionExample:171->testExample:178->waitCanvasPanel:203 » Timeout
```
These tests just show the error page.

**Comment by domhanak** [comment]
Removed the `-DskipITs` flag so now we should see failures here in the PR @Josephblt 
Also added more examples

**Comment by domhanak** [comment]
Adding more examples.
Since my last commit the status is as follows:
ERRORS: (wont load the editor at all)
```
[ERROR] Errors: 
[ERROR]   SWEditorSeleniumIT.testBookLendingExample:231->testExample:253->waitCanvasPanel:278 » Timeout
[ERROR]   SWEditorSeleniumIT.testCustomerCreditCheckExample:166->testExample:253->waitCanvasPanel:278 » Timeout
[ERROR]   SWEditorSeleniumIT.testJobMonitoringExample:171->testExample:253->waitCanvasPanel:278 » Timeout
[ERROR]   SWEditorSeleniumIT.testNotifyCustomerWorkflowExample:241->testExample:253->waitCanvasPanel:278 » Timeout
[ERROR]   SWEditorSeleniumIT.testSendCloudEventOnProvisionExample:176->testExample:253->waitCanvasPanel:278 » Timeout
```

FAILURES:
```
[ERROR]   SWEditorSeleniumIT.testApplicantRequestDecisionExample:181->testExample:256 JSON documents are different:
Different keys found in node "states[0].dataConditions[0]", extra: "states[0].dataConditions[0].end", expected: <{"condition":"${ .applicants | .age >= 18 }","transition":"StartApplication"}> but was: <{"condition":"${ .applicants | .age >= 18 }","end":false,"transition":"StartApplication"}>
Different keys found in node "states[0].dataConditions[1]", extra: "states[0].dataConditions[1].end", expected: <{"condition":"${ .applicants | .age < 18 }","transition":"RejectApplication"}> but was: <{"condition":"${ .applicants | .age < 18 }","end":false,"transition":"RejectApplication"}>
Different keys found in node "states[0].defaultCondition", extra: "states[0].defaultCondition.end", expected: <{"transition":"RejectApplication"}> but was: <{"end":false,"transition":"RejectApplication"}>

[ERROR]   SWEditorSeleniumIT.testCarVitalsCheckExample:226->testExample:256 JSON documents are different:
Different keys found in node "states[0]", extra: "states[0].end", expected: <{"name":"WhenCarIsOn","onEvents":[{"eventRefs":[CarTurnedOnEvent]}],"transition":"DoCarVitalChecks","type":"event"}> but was: <{"end":false,"name":"WhenCarIsOn","onEvents":[{"eventRefs":[CarTurnedOnEvent]}],"transition":"DoCarVitalChecks","type":"event"}>
Different keys found in node "states[1]", extra: "states[1].end", expected: <{"actions":[{"sleep":{"after":"PT1S"},"subFlowRef":"vitalscheck"}],"name":"DoCarVitalChecks","transition":"CheckContinueVitalChecks","type":"operation"}> but was: <{"actions":[{"sleep":{"after":"PT1S"},"subFlowRef":"vitalscheck"}],"end":false,"name":"DoCarVitalChecks","transition":"CheckContinueVitalChecks","type":"operation"}>
Different keys found in node "states[2].defaultCondition", extra: "states[2].defaultCondition.end", expected: <{"transition":"DoCarVitalChecks"}> but was: <{"end":false,"transition":"DoCarVitalChecks"}>

[ERROR]   SWEditorSeleniumIT.testCheckInboxPeriodicallyExample:201->testExample:256 JSON documents are different:
Different value found in node "start", expected: <{"stateName":"CheckInbox","schedule":{"cron":"0 0/15 * * * ?"}}> but was: <"CheckInbox">.
Different keys found in node "states[0]", extra: "states[0].end", expected: <{"actionMode":"sequential","actions":[{"functionRef":"checkInboxFunction"}],"name":"CheckInbox","transition":"SendTextForHighPriority","type":"operation"}> but was: <{"actionMode":"sequential","actions":[{"functionRef":"checkInboxFunction"}],"end":false,"name":"CheckInbox","transition":"SendTextForHighPriority","type":"operation"}>

[ERROR]   SWEditorSeleniumIT.testEventBasedServiceInvocation:206->testExample:256 JSON documents are different:
Different value found in node "states[0].actions[0]", expected: <{"name":"MakeAppointmentAction","eventRef":{"produceEventRef":"MakeVetAppointment","data":"${ .patientInfo }","consumeEventRef":"VetAppointmentInfo"},"actionDataFilter":{"results":"${ .appointmentInfo }"}}> but was: <null>.

[ERROR]   SWEditorSeleniumIT.testFillGlassOfWaterExample:236->testExample:256 JSON documents are different:
Different keys found in node "states[0].dataConditions[0]", extra: "states[0].dataConditions[0].end", expected: <{"condition":"${ .counts.current < .counts.max }","name":"Need to fill more","transition":"Add Water"}> but was: <{"condition":"${ .counts.current < .counts.max }","end":false,"name":"Need to fill more","transition":"Add Water"}>
Different keys found in node "states[1]", extra: "states[1].end", expected: <{"actions":[{"actionDataFilter":{"toStateData":".counts.current"},"functionRef":"Increment Current Count Function"}],"name":"Add Water","transition":"Check if full","type":"operation"}> but was: <{"actions":[{"actionDataFilter":{"toStateData":".counts.current"},"functionRef":"Increment Current Count Function"}],"end":false,"name":"Add Water","transition":"Check if full","type":"operation"}>

[ERROR]   SWEditorSeleniumIT.testHandleCarAuctionBidExample:196->testExample:256 JSON documents are different:
Different value found in node "start", expected: <{"stateName":"StoreCarAuctionBid","schedule":"R/PT2H"}> but was: <"StoreCarAuctionBid">.

[ERROR]   SWEditorSeleniumIT.testProcessTransactionsExample:246->testExample:256 JSON documents are different:
Different keys found in node "", extra: "start", expected: <{"autoRetries":true,"constants":{"largetxamount":5000},"functions":[{"name":"Banking Service - Larger Tx","operation":"banking.yaml#largerTransation","type":"asyncapi"}, {"name":"Banking Service - Smaller T","operation":"banking.yaml#smallerTransation","type":"asyncapi"}],"id":"customerbankingtransactions","name":"Customer Banking Transactions Workflow","specVersion":"0.8","states":[{"actions":[{"condition":"${ .tx >= $CONST.largetxamount }","functionRef":"Banking Service - Larger Tx","name":"Process Larger Transaction"}, {"condition":"${ .tx < $CONST.largetxamount }","functionRef":"Banking Service - Smaller Tx","name":"Process Smaller Transaction"}],"end":true,"inputCollection":"${ .customer.transactions }","iterationParam":"${ .tx }","name":"ProcessTransactions","type":"foreach"}],"version":"1.0"}> but was: 
<{"autoRetries":true,"constants":{"largetxamount":5000},"functions":[{"name":"Banking Service - Larger Tx","operation":"banking.yaml#largerTransation","type":"asyncapi"}, {"name":"Banking Service - Smaller T","operation":"banking.yaml#smallerTransation","type":"asyncapi"}],"id":"customerbankingtransactions","name":"Customer Banking Transactions Workflow","specVersion":"0.8","start":"","states":[{"actions":[{"condition":"${ .tx >= $CONST.largetxamount }","functionRef":"Banking Service - Larger Tx","name":"Process Larger Transaction"}, {"condition":"${ .tx < $CONST.largetxamount }","functionRef":"Banking Service - Smaller Tx","name":"Process Smaller Transaction"}],"end":true,"inputCollection":"${ .customer.transactions }","iterationParam":"${ .tx }","name":"ProcessTransactions","type":"foreach"}],"version":"1.0"}>

[ERROR]   SWEditorSeleniumIT.testProvisionOrdersExample:161->testExample:256 JSON documents are different:
Different keys found in node "states[0]", extra: "states[0].end", expected: <{"actionMode":"sequential","actions":[{"functionRef":{"arguments":{"order":"${ .order }"},"refName":"provisionOrderFunction"}}],"name":"ProvisionOrder","onErrors":[{"errorRef":"Missing order id","transition":"MissingId"}, {"errorRef":"Missing order item","transition":"MissingItem"}, {"errorRef":"Missing order quantity","transition":"MissingQuantity"}],"stateDataFilter":{"output":"${ .exceptions }"},"transition":"ApplyOrder","type":"operation"}> but was: <{"actionMode":"sequential","actions":[{"functionRef":{"arguments":{"order":"${ .order }"},"refName":"provisionOrderFunction"}}],"end":false,"name":"ProvisionOrder","onErrors":[{"end":false,"errorRef":"Missing order id","transition":"MissingId"}, {"end":false,"errorRef":"Missing order item","transition":"MissingItem"}, {"end":false,"errorRef":"Missing order quantity","transition":"MissingQuantity"}],"stateDataFilter":{"output":"${ .exceptions }"},"transition":"ApplyOrder","type":"operation"}>
Different keys found in node "states[0].onErrors[0]", extra: "states[0].onErrors[0].end", expected: <{"errorRef":"Missing order id","transition":"MissingId"}> but was: <{"end":false,"errorRef":"Missing order id","transition":"MissingId"}>
Different keys found in node "states[0].onErrors[1]", extra: "states[0].onErrors[1].end", expected: <{"errorRef":"Missing order item","transition":"MissingItem"}> but was: <{"end":false,"errorRef":"Missing order item","transition":"MissingItem"}>
Different keys found in node "states[0].onErrors[2]", extra: "states[0].onErrors[2].end", expected: <{"errorRef":"Missing order quantity","transition":"MissingQuantity"}> but was: <{"end":false,"errorRef":"Missing order quantity","transition":"MissingQuantity"}>

[ERROR]   SWEditorSeleniumIT.testPurchaseOrderDeadlineExample:216->testExample:256 JSON documents are different:
Different keys found in node "states[0]", extra: "states[0].end", expected: <{"name":"StartNewOrder","onEvents":[{"actions":[{"functionRef":{"refName":"LogNewOrderCreated"}}],"eventRefs":[OrderCreatedEvent]}],"transition":{"nextState":"WaitForOrderConfirmation"},"type":"event"}> but was: <{"end":false,"name":"StartNewOrder","onEvents":[{"actions":[{"functionRef":{"refName":"LogNewOrderCreated"}}],"eventRefs":[OrderCreatedEvent]}],"transition":"WaitForOrderConfirmation","type":"event"}>
Different value found in node "states[0].transition", expected: <{"nextState":"WaitForOrderConfirmation"}> but was: <"WaitForOrderConfirmation">.
Different keys found in node "states[1]", extra: "states[1].end", expected: <{"name":"WaitForOrderConfirmation","onEvents":[{"actions":[{"functionRef":{"refName":"LogOrderConfirmed"}}],"eventRefs":[OrderConfirmedEvent]}],"transition":{"nextState":"WaitOrderShipped"},"type":"event"}> but was: <{"end":false,"name":"WaitForOrderConfirmation","onEvents":[{"actions":[{"functionRef":{"refName":"LogOrderConfirmed"}}],"eventRefs":[OrderConfirmedEvent]}],"transition":"WaitOrderShipped","type":"event"}>
Different value found in node "states[1].transition", expected: <{"nextState":"WaitOrderShipped"}> but was: <"WaitOrderShipped">.
```

**Comment by romartin** [comment]
Hey @domhanak 

Did you finally reported the issue for the failed test case? As far as I remember from our last call, it was a single one failing. Also @Josephblt will look into that. Any updates here guys? Thx in adv.

**Comment by domhanak** [comment]
@romartin Issues are reported in the first comment, each represents a set of failures in the tests.

**Comment by domhanak** [comment]
Rebased on main.

**Comment by tiagobento** [comment]
@domhanak This is labeled as "DO NOT MERGE", is it still the case?

**Review by romartin — APPROVED** [review]
Hey @domhanak 
Thanks for this, it's nice having those integration tests! Great work

As discussed, we are providing PRs for the failed test cases, in order to fix this PR as well. So once merged, please feel free to move forward. :+1: 

Thanks!

**Comment by domhanak** [comment]
@romartin @tiagobento Feel free to merge this, I will enable them once the PR are in. OR we can enable them in the PR that fixes these. Currently these tests are skipped.

**Comment by romartin** [comment]
thanks @domhanak !

@tiagobento for me it's fine to merge, but there is only my approval. Do you want to take a look or can I feel free to merge?

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
