### PR TITLE
KOGITO-9310: Bump `vscode-extension-tester` version to 5.7.1

### PR DESCRIPTION
**Pull request by zdrapela**
Jira: https://issues.redhat.com/browse/KOGITO-9310

### CODE REVIEW

**Review by yesamer — APPROVED** [review]

**Review by domhanak — APPROVED** [review]
Thanks!

@zdrapela @LuboTerifaj would the unification of this dependency to a singular package/place work? Just thinking, the general idea is to have one single place to set this if possible. Lmk off-chat please.

**Comment by tiagobento** [comment]
@domhanak No.. it doesn't work like that.

**Comment by domhanak** [comment]
@tiagobento I understand that part, it is more about reviewing the integration tests to not need the dependency, making everything provided thought the `vscode-extension-common-test-helpers` package.

@zdrapela could you please also update it there? - https://github.com/kiegroup/kie-tools/blob/main/packages/vscode-extension-common-test-helpers/package.json

**Review by domhanak — CHANGES_REQUESTED** [review]
https://github.com/kiegroup/kie-tools/blob/main/packages/vscode-extension-common-test-helpers/package.json should also be updated.

**Comment by zdrapela** [comment]
@domhanak I took a look and couldn't find a way to have the dependency unified. It looks like you must have the dependencies listed in `package.json` of the package that uses it and linking it from `vscode-extension-common-test-helpers` does not work. You can take a look at what I tried here https://github.com/zdrapela/kie-tools/commits/KOGITO-9310_bump-extester-5.7.0_dep.

Anyway, I use a script for updating the versions ([`ncu`](https://www.npmjs.com/package/npm-check-updates) helps a lot) and verifying the changes locally, so it is easy to update it anyway.

As 5.7.1 was just released, I raised the version in this PR.

**Review by domhanak — APPROVED** [review]

**Review by caponetto — APPROVED** [review]

**Pull request merged**
