### PR TITLE
KOGITO-5428: Introduce DMN Runner cypress test

### PR DESCRIPTION
**Pull request by jomarko**

### CODE REVIEW

**Comment by domhanak** [comment]
@tiagobento In the logs of `CI :: Monorepo / monorepo-pr-ci (ubuntu-latest) (pull_request)` I can see we are building packages like `kie-editors-standalone`, `desktop` and more. I thought we should be building only packages that area affected by these changes. Is there a bug in the behavior or is this because there is a changes in `build-env` package? Thanks for clarification in advance!

**Review by domhanak — CHANGES_REQUESTED** [review]
Looks good to me, we can merge once the test is passing. Currently there is an issue, also visible on CI now.
```
 1) DMN Runner Test
       Test DMN Runner on DMN sample:
     AssertionError: Timed out retrying after 10000ms: expected '<div.pf-c-description-list__text>' to be 'visible'

This element `<div.pf-c-description-list__text>` is not visible because its content is being clipped by one of its parent elements, which has a CSS property of overflow: `hidden`, `scroll` or `auto`
```

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me when it is green 🟢.

**Comment by jomarko** [comment]
@domhanak, thank you for the review, I have updated the assertion in last commit, lets see what our CI automation results are.

@tomasdavidorg thank you for the review too.

**Review by domhanak — APPROVED** [review]
Locally it passes for me. Thanks @jomarko for new test! Great work

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
