### PR TITLE
[incubator-kie-issues#1534] Remove less.jar from errai-ui

### LINKED ISSUE #1534: Remove Maven and Gradle wrapper from source
Context on IPMC vote email: https://lists.apache.org/thread/oz1xfz48jwlw05sdy0wvtnrhn27jc72h

### PR DESCRIPTION
**Pull request by mcruzdev**
Closes https://github.com/apache/incubator-kie-issues/issues/1534

### CODE REVIEW

**Review by jomarko — APPROVED** [review]
Thank you for this contribution @mcruzdev . As the removed file is in test resources and the build is green, I believe it is safe to approve even without manual check.

**Comment by yesamer** [comment]
@jomarko Please notice that the build didn't start for this PR

**Comment by jomarko** [comment]
@yesamer ok, thank you for spottting, so, can we start it manually?

**Comment by yesamer** [comment]
@jomarko Yes

**Comment by mcruzdev** [comment]
> Thank you for this contribution @mcruzdev . As the removed file is in test resources and the build is green, I believe it is safe to approve even without manual check.

I found by reference using the jar, but there is no.

**Comment by jomarko** [comment]
@mcruzdev thank you, still we need to run build to be 100%sure the changes are fine. @yesamer I am not able to start the build manually, so if you are able to do it, please help.

@mcruzdev for example here you can see, the number of checks that should be started is higher https://github.com/apache/incubator-kie-tools/pull/2658

I guess it is related to the thing, you are not member of the github apache organization and that is why jobs were not started probably.

**Review by yesamer — APPROVED** [review]
Tested locally, everything is ok. Thank you @mcruzdev

**Comment by mcruzdev** [comment]
Thank you @yesamer and @jomarko!

**Comment by tiagobento** [comment]
Not sure why the `CI :: Build` jobs are not running...  We need to wait for them to be sure.

**Comment by mcruzdev** [comment]
I will to try close and reopen

**Comment by tiagobento** [comment]
Thanks @mcruzdev. `CI :: Build` jobs are running.

**Comment by mcruzdev** [comment]
I think it happened because I opened as draft, maybe. https://github.com/apache/incubator-kie-tools/blob/5ebd85c351864ab86fb16714b34b5e996b3e7829/.github/workflows/ci_build.yml#L39

**Review by jomarko — APPROVED** [review]

**Comment by mcruzdev** [comment]
I started a reserach here to solve the vscode-extension-tester issue, I think that it was solved 🎉

**Comment by mcruzdev** [comment]
@porcelli I removed this one from the test 😟, but the pipeline is ok! I will pay attention for next.

**Pull request merged**
