### PR TITLE
KOGITO-8197: SWF Editor - States example export is broken

### PR DESCRIPTION
**Pull request by hasys**
Hello @romartin, @LuboTerifaj,

there is the fix for the issue. Issue was in Compensation Transition Unmarshaller.

After my changes I took the source file and the generated one and executed `diff` command on it. As result now there are some parameters in different order, but otherwise they are now identical.

Thank you!

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by LuboTerifaj** [comment]
Hello @hasys , there are missing steps to reproduce the issue in [KOGITO-8197](https://issues.redhat.com/browse/KOGITO-8197). Could you please have a look at it? Thanks!

**Comment by hasys** [comment]
Hello @LuboTerifaj, added, thank you!

**Comment by LuboTerifaj** [comment]
Hello @hasys , I am still awaiting the jira clarification. See my [comment](https://issues.redhat.com/browse/KOGITO-8197?focusedId=21989938&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21989938). Thanks!

**Comment by hasys** [comment]
Hi @LuboTerifaj, simplified as much as I can. Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj, I found another way to test the PR see Steps To Reproduce. Thank you!

**Comment by hasys** [comment]
Hi @LuboTerifaj, I found another way to test the PR see Steps To Reproduce. Thank you!

**Comment by LuboTerifaj** [comment]
Hello @hasys ,

there is no issue with testing itself, but what to actually test. It is not clear from the description as well as from the steps to reproduce what is actually going to be fixed. Furthermore, there is also missing the original information in the jira now.

Let's clarify it on the call and get the jira to the proper state.

Thank you!

**Review by LuboTerifaj — APPROVED** [review]
Hello @hasys ,

I have found two issues regarding export feature:

- [KOGITO-8921](https://issues.redhat.com/browse/KOGITO-8921) _The json file downloaded from webapp does not contain empty characters_
- [KOGITO-8922](https://issues.redhat.com/browse/KOGITO-8922) _The json file downloaded from webapp has always the same name_

Those issues are present also on main, so I created separate tickets for them.

The PR fixes the issue with wrong json file generation.

Thank you!

**Pull request merged**
