### PR TITLE
[NO-ISSUE] Adding some new dmn examples

### PR DESCRIPTION
**Pull request by LightGuard**
Adding some standalone dmn examples that can be used in either the web app or any of the standalone editors.

### CODE REVIEW

**Comment by ljmotta** [comment]
@LightGuard Thanks for the PR. After #2726 we place the standalone example in the `examples/dmn-editor-standalone-on-webapp/static/models`. Them please update the `index.ts` of the designed type of example, as we have the `readOnly` (for read only examples), `stateControl` (for examples with the `undo/redo` buttons) and `withIncludedModels` (for dms that include other dms).

**Comment by LightGuard** [comment]
I don't see anything in the index.ts that needs to be updated. I don't think we want to change which file is automatically loaded. Am I missing something?

**Comment by ljmotta** [comment]
@LightGuard The `dmn-editor-standalone-on-webapp/src` has 3 folders: `readOnly`, `stateControl`, and `withIncludedModels`. Each one of them has an `index.ts` file that loads the respective DMNs. I don't know the purpose of these PR DMNs, but if they are DMNs that don't have included models, I'd put them in the `stateControl` category. At the end of the `src/stateControl/index.ts` file you will have an `initFileLoader` method with the DMNs that will be loaded, add the new DMNs there if that is the case. You will need to tweak the `index.html` to add the buttons for the new DMNs.

After your changes, please give it a try. The steps for building and starting are in the example README.

**Comment by tiagobento** [comment]
This example's purpose is to showcase the DMN Editor Standalone API/usage. Having more models without showcasing features specific to the DMN Editor Standalone only adds noise/clutter to the example itself. We don't have a place for showcasing DMN features yet, but in any case, this example is not it.

**Comment by LightGuard** [comment]
> @LightGuard The `dmn-editor-standalone-on-webapp/src` has 3 folders: `readOnly`, `stateControl`, and `withIncludedModels`. Each one of them has an `index.ts` file that loads the respective DMNs. I don't know the purpose of these PR DMNs, but if they are DMNs that don't have included models, I'd put them in the `stateControl` category. At the end of the `src/stateControl/index.ts` file you will have an `initFileLoader` method with the DMNs that will be loaded, add the new DMNs there if that is the case. You will need to tweak the `index.html` to add the buttons for the new DMNs.
> 
> After your changes, please give it a try. The steps for building and starting are in the example README.

Ah, got it. I was looking at the main index.ts file in src. That makes sense. Thanks!

**Comment by LightGuard** [comment]
> This example's purpose is to showcase the DMN Editor Standalone API/usage. Having more models without showcasing features specific to the DMN Editor Standalone only adds noise/clutter to the example itself. We don't have a place for showcasing DMN features yet, but in any case, this example is not it.

Are you saying, this isn't where these examples should go?

**Comment by ljmotta** [comment]
@tiagobento It makes sense.

@LightGuard Yes, it's not the correct place, and I incorrectly point it out to you. We don't have a place to put DMN files. It would be necessary to create a new example application. The only place I could think of is the `dmn-editor` Storybook's. We have the `useCases` section there.

**Pull request closed without merging**
