### PR TITLE
KOGITO-8636: Update selenium to version 4.8.0

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Signed-off-by: Tomas David <tdavid@redhat.com>

https://issues.redhat.com/browse/KOGITO-8636

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Comment by tomasdavidorg** [comment]
There is some issue with running the tests. I am investigating it.

**Comment by tomasdavidorg** [comment]
I tried to investigate and debug the issue but I was not able to fix it. With the jest/ts-jest 26, the selenium tests throw:
```
ENOENT: no such file or directory, open 'node:events'

      at Runtime.readFile (../../node_modules/.pnpm/jest-runtime@26.6.3/node_modules/jest-runtime/build/index.js:1987:21)
      at Object.<anonymous> (../../node_modules/.pnpm/selenium-webdriver@4.8.0/node_modules/selenium-webdriver/bidi/index.js:18:26)
```
Upgrading the jest/ts-jest to higher version 27/28/29 will fix the issue but the upgrade requires many changes in most of the packages.

@paulovmr @tiagobento have you seen any similar issue? Do we have any plan to update jest/ts-jest packages? I am thinking if I should invest some time to the upgrade.

**Comment by paulovmr** [comment]
@tomasdavidorg No, I didn't see this issue. Looks to me that jest 26 is much older then the selenium 4.8.0, so might just be a matter of compatibility between them based on what you said. Since the tests work in the newer version of jest, I guess the solution would be to make the jest upgrade as well if you can.

**Comment by tomasdavidorg** [comment]
Closing this PR as it requires the jest upgrade.

**Pull request closed without merging**
