### PR TITLE
KOGITO-9504: SWF Editor - In edit mode, Empty diagram page is shown if properties are edited

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin, could you review this PR?

JIRAs covered in this PR:
**JIRA**: [KOGITO-9504](https://issues.redhat.com/browse/KOGITO-9504)
**JIRA**: [KOGITO-9509](https://issues.redhat.com/browse/KOGITO-9509)
**JIRA**: [KOGITO-9510](https://issues.redhat.com/browse/KOGITO-9510)
**JIRA**: [KOGITO-9511](https://issues.redhat.com/browse/KOGITO-9511)

Thanks!

### CODE REVIEW

**Comment by romartin** [comment]
Hey @handreyrc 

Thanks for this work! I have been testing the UI and I it works good!

On the other hand, I think we have to reconsider the interaction between text and diagram editors, before moving forward and spending more time on fixes. I mention this because it looks every time a user do some action on the diagram editor, both text and diagram editors are completely reloading, so the user experience is not yet so perfect.For example, the user notices about reloadings, and the time spent there, also it is noticeable that the autolayout applies once reloading only, so new shapes appear on top of others for a little while.

Anyway no worries, the work is great, and all fixes are still relevant, but we only have to see how to avoid reloading the whole editors. Let's talk this off-line once you're back.

thx!

**Comment by caponetto** [comment]
Hi @handreyrc,
I understand these changes are seen only on VS Code, not all channels.
If that's the case, could you please improve the PR title to be specific for VS Code?

**Comment by handreyrc** [comment]
Hey @romartin, @caponetto, @LuboTerifaj,

As @romartin mentioned above we still have some points to discuss about the multiplying architecture integration and how it should behave so I removed the [KOGITO-9399](https://issues.redhat.com/browse/KOGITO-9399) from the scope of this PR. 
However, we still have important fixes in this PR so we can still move forward with those.

@caponetto, this PR is not touching tooling side/ VsCode anymore, we will do it in separate PR. 

The PR is up-to- date, we are good for review again!

Thanks guys!

**Review by LuboTerifaj — APPROVED** [review]
Hello @handreyrc ,

I made only limited testing on the bug fixes and features since there is still no proper implementation of the Text and Diagram editor integration. Using the edit mode, you end up in invalid Text editor or Diagram editor state very easily.

I covered all happy path scenarios for the referenced jiras by this PR and I didn't find any issues.

Thanks!

**Review by romartin — APPROVED** [review]
Great stuff, thanks @handreyrc !

**Pull request merged**
