### PR TITLE
KOGITO-6830: Remove `kie-soup-bom` dependency from the `stunner-editors` package

### PR DESCRIPTION
**Pull request by yesamer**
This PR scope is to completely remove all 7.x kie dependencies from `stunner-editors` root pom.
Currently, only `kie-soup` assets are imported. To remove it, the following changes have been applied:

- `PortablePreconditions.checkNotNull()` has been replaced with native Java `Objects.requireNonNull()`. If there are multiple checks in the class, a method was added which covers all the points.
- `PortablePreconditions.checkNotEmpty()` similar approach used above.
- `Maps.Builder` has been replaced mostly with `Stream.of(..)..collect(Collectors.toMap(..))` .  
- `Sets.Builder` has been replaced mostly with `Stream.of(..)..collect(Collectors.toSet(..))` 
- `Lists.Builder` has been replaced mostly with `Stream.of(..)..collect(Collectors.toList(..))` 
- An util class `CronExpression` has been copied from `kie.soup`
- 2 DTOs have been copied: `ModelField` and `FieldAccessorsAndMutators`. These are required in scesim, in DMO (rules) management. Please note, DMO (Rules) scesim are not currently working in Kogito stream, it is only a mocked version useful  in case of a future implementation.

I removed some code smells  and removed unused classes too

### CODE REVIEW

**Comment by yesamer** [comment]
@tiagobento @romartin @danielzhe @jomarko Can you please review it? :)

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@danielzhe @romartin @jomarko Hi guys! Please do prioritize this PR as Handrey is waiting on this one so he can open a very important PR for the new Serverless Workflow Diagram Editor. We want to reuse what Yeser did here (which is great, btw!) on the new stream of development for Stunner inside the new Serverless Workflow Diagram Editor.

**Comment by jomarko** [comment]
@yesamer just a question, the logs says where sonar report is available, however me, accessing that url, I do not see analysis of your PR. Is the sonar report available for you?
Screenshot from 2022-03-17 07-39-09

**Comment by yesamer** [comment]
@jomarko I confirm you, I don't see this PR (and last PRs) reports there.

**Comment by yesamer** [comment]
@jomarko Probably we need to move `<id>sonarcloud-analysis-pull-request</id>` profile from `kie-parent` to `stunner-editor` to enable it

**Comment by jomarko** [comment]
@yesamer I tend to think that that will not help. That profile is used in 7.x kiegroup repositories.

For kie-tools, the sonar is started in jenkins file. The binding of github PR and results on sonarcloud can be seen in jenkinsfile
```
stage('Analyze KIE Tools - Stunner Editors by SonarCloud') {
            when {
                expression { isNormalPRCheck() && isSonarCloudEnabled() }
            }
            steps {
                script {
                    if (isSonarCloudEnabled()) {
                        getMavenCommand('kie-tools/packages/stunner-editors')
                                .withOptions(['-e', '-nsu', "-pl '!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-runtime,!kie-wb-common-dmn/kie-wb-common-dmn-webapp-kogito-testing,!lienzo-webapp'"])
                                .withProperty('sonar.projectKey', 'org.kie.kogito:kogito-tooling')
                                .withProperty('sonar.organization', 'kiegroup')
                                .withProperty('sonar.host.url', 'https://sonarcloud.io')
                                .withProperty('sonar.login', env['SONARCLOUD_TOKEN'])
                                .run('validate org.sonarsource.scanner.maven:sonar-maven-plugin:sonar')
                    }
                }
            }
        }

**Comment by yesamer** [comment]
@jomarko Ok, I thought the cause was related to my previous PR (KOGITO-6841) because I noticed before it PRs were correctly evaluated

**Comment by jomarko** [comment]
@yesamer what is the `sonarcloud-analysis-pull-request` activation, is it by default or by some property, profile name?

**Comment by yesamer** [comment]
@jomarko It's a maven profile. https://github.com/kiegroup/kie-tools/pull/893
Adding it now works, please check the PR I linked

**Review by jomarko — APPROVED** [review]
Approving. just a question about the `kie-wb-common-forms` module. Is that needed? In VS Code, there I do not see an option to generate forms for a BPMN process.

If not needed for sure can be handled in separate jira.

**Review by romartin — APPROVED** [review]
Thanks @yesamer , looks good to me!

**Review by danielzhe — APPROVED** [review]

**Pull request merged**
