### PR TITLE
KOGITO-8907: [SWF Editor] Highlight selected node after setContent in VS Code extension

### PR DESCRIPTION
**Pull request by paulovmr**
https://user-images.githubusercontent.com/832830/227270633-549cef24-186c-4643-a58b-7fdfc7ec4296.mp4

### CODE REVIEW

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
THanks @paulovmr !

@handreyrc can you please take a look and test this in your local branch! Thx in advance!

**Comment by LuboTerifaj** [comment]
Hi @paulovmr , 

I am awaiting the steps to reproduce in jira. See my [comment](https://issues.redhat.com/browse/KOGITO-8907?focusedId=21989803&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21989803).

I will start my review once it is defined.

Thank you!

**Comment by paulovmr** [comment]
Hi @LuboTerifaj , I added the steps in the Jira. They can be seen working on the video at the description of this PR as well.

**Review by handreyrc — APPROVED** [review]
Hey @paulovmr, 

Great job preventing the selection promise to be triggered while the content is not ready yet!
I don't see any issues and it works fine on top of the PR [KOGITO-7999](https://github.com/kiegroup/kie-tools/pull/1366) .

Thanks a lot for your work here!

**Review by LuboTerifaj — COMMENTED** [review]
Hello @paulovmr ,

would it be possible to add some tests?

Other than that, it looks good to me.

Thank you!

**Comment by paulovmr** [comment]
@LuboTerifaj Sure, I've added some tests.

**Review by LuboTerifaj — APPROVED** [review]
Thanks @paulovmr . It looks good to me.

**Pull request merged**
