### PR TITLE
KOGITO-7109: [DMN Designer] New Boxed Expression editor - Copy & paste values with newline

### PR DESCRIPTION
**Pull request by fantonangeli**
Fixes: https://issues.redhat.com/browse/KOGITO-7109

kogito-7109

### CODE REVIEW

**Comment by fantonangeli** [comment]
I see the CodeQL messages about the 2 regexes used to parse the copied values and I will try to fix them.

**Review by ljmotta — APPROVED** [review]
@fantonangeli Thanks for this PR, the code looks really good!

**Review by yesamer — APPROVED** [review]
@fantonangeli Thank you!

**Comment by fantonangeli** [comment]
Jenkins retest this please

**Review by vpellegrino — APPROVED** [review]
I found this interesting PR and I just wanted to give you great feedback!
The code looks clean and the change is consistent.

Great job @fantonangeli 
Thank you!

**Comment by fantonangeli** [comment]
@vpellegrino Thank you for your review, much appreciated!

**Review by jomarko — APPROVED** [review]
Thank you for the changes @fantonangeli . The new lines seems to work fine.

I would like to remind one old issue that is very similar to the KOGITO-7109. The problem is also with empty cells in the copied area. See https://issues.redhat.com/browse/KOGITO-6438 and the latest steps to reproduce I wrote down today.

**Pull request merged**
