### PR TITLE
KOGITO-7450: Eye button on Dashbuilder editor overlaps keyboard short…

### PR DESCRIPTION
**Pull request by jesuino**
Also includes minor fixes

### CODE REVIEW

**Review by ederign — APPROVED** [review]

**Review by caponetto — APPROVED** [review]
LGTM

**Comment by tomasdavidorg** [comment]
Should't be the button background also transparent as in case of the shortcuts button?
Screenshot from 2022-07-13 13-38-46

If I click on the shorcuts button it is also quite visible:

Screenshot from 2022-07-13 13-54-16

Screenshot from 2022-07-13 13-38-57

**Comment by ederign** [comment]
@jesuino  +1 for Tomas comment. Good catch.

**Comment by jesuino** [comment]
thank you so much for your review, @tomasdavidorg  - I addressed it on my last commit

**Review by paulovmr — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]
Thanks for the changes @jesuino. Looks good to me now. 🙂

**Pull request merged**
