### PR TITLE
kie-issues#43: Update logic for headers group indexes computing

### LINKED ISSUE #43: DMN Editor: Incorect DT Output headers
We have incorect decision table header if the decision table is nested in other expression. See the attachment.
table with duplied header's row

### PR DESCRIPTION
**Pull request by jomarko**
Closes kiegroup/kie-issues/issues/43

Before
Screenshot from 2022-12-02 11-28-48

After
Screenshot from 2022-12-02 11-25-52

### CODE REVIEW

**Comment by jomarko** [comment]
Verification checklist:

- [x] DMN Decision Node, List
- [x] DMN Decision Node, L. Expression
- [x] DMN Decision Node, Relation
- [x] DMN Decision Node, Context, Context
- [x] DMN Decision node, Decision table
- [x] DMN Decision Node, Context Entry, Decision table
- [x] DMN Decision Node, Context Result row, Decision table
- [x] DMN Decision Node, Function, Decision table
- [x] DMN BKM Node, Function, Decision Table
- [x] Sandbox, DMN Runner
- [x] VS Code Scesim, Simple Given, Simple Expect
- [x] VS Code Scesim, Grouped Given, Groupedd Expect

**Comment by jomarko** [comment]
@yesamer FYI, I did some good progress, from UI perspective. Now checking if the created models are fine for runtime execution.

**Comment by yesamer** [comment]
@jomarko Great, I'm building this in my local right now.

**Comment by jomarko** [comment]
Model execution check
Screenshot from 2022-12-16 14-05-08

**Review by yesamer — APPROVED** [review]
@jomarko Thank you!

**Pull request merged**
