### PR TITLE
KOGITO-6956: Fix css selection to bring back 'See as diagram' button

### PR DESCRIPTION
**Pull request by caponetto**
Due to some changes in GitHub style, `a` is not an immediate child of `file-info` class anymore.

**Note**: I also updated the `chromedriver` dependency, otherwise, we would still have broken tests.

### CODE REVIEW

**Comment by yesamer** [comment]
@caponetto well done! Thank you!

**Comment by yesamer** [comment]
@caponetto Sorry for closing it, my bad

**Review by yesamer — APPROVED** [review]

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me. Tested locally. Thanks @caponetto 🙂

**Review by jomarko — APPROVED** [review]

**Comment by caponetto** [comment]
Since this PR fixes the issue with "See as diagram" button and also chrome extension tests, let's merge this one and work on the `kie-editors-standalone` test errors in a separated PR. What do you guys think? @yesamer @jomarko @tomasdavidorg

**Comment by jomarko** [comment]
@caponetto fine for me

**Comment by yesamer** [comment]
@caponetto  I agree

**Pull request merged**
