### PR TITLE
NO-ISSUE: Skip `BpmnPrTest` and `DmnPrTest` on Chrome Extension E2E tests

### LINKED ISSUE #2326: Chrome extension: Remove BpmnPrTest and DmnPrTest e2e tests
[BpmnPrTest](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/BpmnPrTest.ts) and [DmnPrTest](https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnPrTest.ts) uses opened PRs from the separated repositor. These PRs will be closed and the tests will start failing if they are not removed. 

Test PR references:
- https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnPrTest.ts#L36
- https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/BpmnPrTest.ts#L36

Testing PRs and repository:
- https://github.com/tomasdavidorg/chrome-extension-pr-test/pull/2
- https://github.com/tomasdavidorg/chrome-extension-pr-test/pull/3
- https://github.com/tomasdavidorg/chrome-extension-pr-test

### PR DESCRIPTION
**Pull request by tomasdavidorg**
Fixes #2326.

@jomarko Could you please take a look? 
The tests contains links to the separated repository.
- https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/DmnPrTest.ts#L36
- https://github.com/apache/incubator-kie-tools/blob/main/packages/chrome-extension-pack-kogito-kie-editors/e2e-tests/tests/BpmnPrTest.ts#L36

I will close the referenced PRs and delete the repository soon:
- https://github.com/tomasdavidorg/chrome-extension-pr-test/pull/2
- https://github.com/tomasdavidorg/chrome-extension-pr-test/pull/3
- https://github.com/tomasdavidorg/chrome-extension-pr-test

To avoid test failures the tests needs to be skipped/removed or the testing PRs needs to be recreated somewhere.

### CODE REVIEW

**Comment by tiagobento** [comment]
@tomasdavidorg Thanks for addressing this. May I ask you to SKIP the tests instead, and point to the issue you created? We'll need to recreate the infrastructure for those tests, and I'm afraid removing them might make us not do it.

**Review by jomarko — COMMENTED** [review]
@tomasdavidorg hi, thank you for opening this PR and topic of maintaining these tests. I think I have no strong opinion how to proceed, however solution by @tiagobento (skip the tests and link with kie-issue) sounds as good to me. However, it may require a change of the existing kie-issue from remove tests to sth. like refactor tests?

**Comment by tomasdavidorg** [comment]
Thanks @tiagobento @jomarko. I changed the PR to skip the tests and I opened https://github.com/apache/incubator-kie-tools/issues/2335.

**Review by jomarko — APPROVED** [review]
Thank you @tomasdavidorg

**Pull request merged**
