### PR TITLE
KOGITO-7230: Upgrade dependencies with reported vulnerabilities 

### PR DESCRIPTION
**Pull request by domhanak**
I changed following dependencies:
`com.fasterxml.jackson` -> 2.13.3
`com.google.code.gson` -> 2.8.6
`org.wildfly.core` -> 18.1.1

Performed basic sanity check on the webapp, looked good. Let me know @romartin

### CODE REVIEW

**Comment by yesamer** [comment]
@domhanak Can you please update the same dependencies in `stunner-editor/errai-bom`? Thx u!

**Comment by domhanak** [comment]
@yesamer I prefer doing it in separate PR for `stunner-editors` because I did not test anything on that side. Just in case.

**Review by yesamer — APPROVED** [review]
Thx u @domhanak

**Comment by yesamer** [comment]
jenkins retest this please

**Review by romartin — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
