### PR TITLE
KOGITO-6181 : Stunner-based editors are loosing focus when asked for the SVG

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin @LuboTerifaj this is the new PR. Old one was https://github.com/kiegroup/kogito-editors-java/pull/158 can you review?

### CODE REVIEW

**Review by LuboTerifaj — COMMENTED** [review]
Hello @inodeman ,

are there any updates since my last [comment](https://github.com/kiegroup/kogito-editors-java/pull/158#issuecomment-1008956669)?

Once the issue is fixed I will test the changes again.

Thank you!

**Comment by tiagobento** [comment]
@inodeman To re-trigger the CI, please push an empty commit. If you found a flaky test, please skip it on this PR and add it to this epic https://issues.redhat.com/browse/KOGITO-6643

**Comment by inodeman** [comment]
Will do @tiagobento thanks

**Comment by inodeman** [comment]
Hi @LuboTerifaj about last comment, I mentioned I did not touch code relating to the toolbar, so that behavious should be the same as in main branch, let me know

**Comment by inodeman** [comment]
Build can be found here. https://drive.google.com/drive/folders/1G5UfG5aHqBHFX1RRYHErgnVNER9Felrw?usp=sharing

**Comment by inodeman** [comment]
Hi @LuboTerifaj just reproduced the issue you mentioned, let me fix it.

**Comment by inodeman** [comment]
Hi @romartin @LuboTerifaj builds can be found here. Issue remaining was fixed. https://drive.google.com/drive/folders/1G5UfG5aHqBHFX1RRYHErgnVNER9Felrw?usp=sharing

**Comment by tiagobento** [comment]
@inodeman Our CI had some problems earlier today, can you please rebase this PR?

**Comment by inodeman** [comment]
Hi @tiagobento rebased now.

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
What's missing for this to be merged?

**Comment by romartin** [comment]
@LuboTerifaj please remember this review, I think is ready to review again, thanks!!

**Comment by romartin** [comment]
@LuboTerifaj please friendly reminde again :) Thanks!

**Review by LuboTerifaj — CHANGES_REQUESTED** [review]
Hello @inodeman , @romartin ,

unfortunately the issue I mentioned in the [comment](https://github.com/kiegroup/kogito-editors-java/pull/158#pullrequestreview-844921602) is still not fixed:

- When you are scrolling the canvas and the node is selected, the toolbox is moving as well.
See the video:
https://user-images.githubusercontent.com/12122769/153449683-25ab93ea-9bf7-42df-912f-2a9a53bed9a5.mp4

Thanks!

**Comment by inodeman** [comment]
Hi @LuboTerifaj sorry seems I uploaded wrong build, uploading it again.

**Comment by inodeman** [comment]
Hi @LuboTerifaj @romartin sorry, the issue had been fixed but there was a scenario where it found a null pointer, the issue has now been fixed and I tested it several times. Build can be found here. https://drive.google.com/drive/folders/1G5UfG5aHqBHFX1RRYHErgnVNER9Felrw?usp=sharing

**Comment by romartin** [comment]
@LuboTerifaj please friendly reminder about htis review thx

**Review by LuboTerifaj — APPROVED** [review]
Hello @inodeman , thank you for the fix. It looks good to me now.

**Review by romartin — APPROVED** [review]

**Pull request merged**
