### PR TITLE
KOGITO-1387: Loading animation doesn't work on Safari

### PR DESCRIPTION
**Pull request by ljmotta**
## Task
https://issues.redhat.com/browse/KOGITO-1387

## Description
Updating the Patternfly version should fix the Safari bug.

### CODE REVIEW

**Comment by manstis** [comment]
@kelvah ... saves us a job :-)

**Comment by tiagobento** [comment]
@ljmotta Looks like that didn't fix the loading spinner on Safari yet :/

**Comment by ljmotta** [comment]
@tiagobento I'm still doing some adjustments on the webpack and making some more tests.

**Comment by manstis** [comment]
Hi @ljmotta what's the status of this PR?

We (me and @kelvah) would very much like to see the PF upgrade (in this PR) make it into `master` soon.

We're about to work on some aspects of our new editor that would benefit from the "warning" [Form Control validation](https://www.patternfly.org/2020.15/components/form-control).

**Comment by ljmotta** [comment]
Hi @manstis  , I'm going to shortly start working again on this PR. It was paused for a while, and I'm sorry about that.

**Comment by tiagobento** [comment]
Closed as it doesn't fix the issue. A new PR will be open once a fix is available.

**Pull request closed without merging**
