### PR TITLE
kie-issues#1163: incubator-kie-tools missing header files 

### LINKED ISSUE #1163: incubator-kie-tools missing header files
Following files has been listed by the RAT tool. Still under the investigation if all of them require license, but some are clearly needed like Java files.

https://gist.github.com/porcelli/69467dc36462fa4a42339e697d50fd59

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/apache/incubator-kie-issues/issues/1163

### CODE REVIEW

**Review by porcelli — APPROVED** [review]

**Review by ljmotta — APPROVED** [review]

**Comment by yesamer** [comment]
@porcelli @LightGuard DISCLAIMER added.

**Review by Josephblt — APPROVED** [review]

**Review by porcelli — APPROVED** [review]

**Comment by Josephblt** [comment]
Hello @yesamer. I used a bash script (check_header.sh) to check the headers using the kie-tools-rad-report file.

[check_header.sh](https://gist.github.com/Josephblt/873fd9c9b904e4a3a2a6d37ffa1ad91a)
[kie-tools-rad-report.txt](https://gist.github.com/Josephblt/5fb6299509219fd2a01c97ac03372fc7)

To use the script:
Paste the file check_header.sh to kie-tools directory
Paste the file kie-tools-rad-report.txt to kie-tools directory
Run check_headers script ($./{kie-tools directory}/./check_header.sh.


Here is the list of files without headers I found:
[results.txt](https://gist.github.com/Josephblt/2980d4ddf084a1f10102452e9e3fcfdb)
Although it is possible that some of the files could be ignored, there are lots of .java files that are likely to be problematic.

**Review by Josephblt — CHANGES_REQUESTED** [review]
Hello @yesamer. I used a bash script (check_header.sh) to check the headers using the kie-tools-rad-report file.

[check_header.sh](https://gist.github.com/Josephblt/873fd9c9b904e4a3a2a6d37ffa1ad91a)
[kie-tools-rad-report.txt](https://gist.github.com/Josephblt/5fb6299509219fd2a01c97ac03372fc7)

To use the script:
Paste the file check_header.sh to kie-tools directory
Paste the file kie-tools-rad-report.txt to kie-tools directory
Run check_headers script ($./{kie-tools directory}/./check_header.sh.

Here is the list of files without headers I found:
[results.txt](https://gist.github.com/Josephblt/2980d4ddf084a1f10102452e9e3fcfdb)
Although it is possible that some of the files could be ignored, there are lots of .java files that are likely to be problematic.

**Review by Josephblt — COMMENTED** [review]
Hello @yesamer. I used a bash script (check_header.sh) to check the headers using the kie-tools-rad-report file.

[check_header.sh](https://gist.github.com/Josephblt/873fd9c9b904e4a3a2a6d37ffa1ad91a)
[kie-tools-rad-report.txt](https://gist.github.com/Josephblt/5fb6299509219fd2a01c97ac03372fc7)

To use the script:
Paste the file check_header.sh to kie-tools directory
Paste the file kie-tools-rad-report.txt to kie-tools directory
Run check_headers script ($./{kie-tools directory}/./check_header.sh.

Here is the list of files without headers I found:
[results.txt](https://gist.github.com/Josephblt/2980d4ddf084a1f10102452e9e3fcfdb)
Although it is possible that some of the files could be ignored, there are lots of .java files that are likely to be problematic.

**Review by Josephblt — APPROVED** [review]
Hello @yesamer. I used a bash script (check_header.sh) to check the headers using the kie-tools-rad-report file.

[check_header.sh](https://gist.github.com/Josephblt/873fd9c9b904e4a3a2a6d37ffa1ad91a)
[kie-tools-rad-report.txt](https://gist.github.com/Josephblt/5fb6299509219fd2a01c97ac03372fc7)

To use the script:
Paste the file check_header.sh to kie-tools directory
Paste the file kie-tools-rad-report.txt to kie-tools directory
Run check_headers script ($./{kie-tools directory}/./check_header.sh.

Here is the list of files without headers I found:
[results.txt](https://gist.github.com/Josephblt/2980d4ddf084a1f10102452e9e3fcfdb)
Although it is possible that some of the files could be ignored, there are lots of .java files that are likely to be problematic.

**Review by LightGuard — APPROVED** [review]

**Comment by yesamer** [comment]
Thank you @Josephblt for checking!!
I intentionally ignored some java files because:
- In dashbuilder, a set of java files are used to test a code generation feature, and adding the headers leads to some tests failures
- Some java class file are a copy from other libraries. In such a case I don't know how to handle that

In any case, I'll double check again

**Pull request merged**
