### PR TITLE
KOGITO-9153: Auto complete YaRD - adds a new row with correct item count for dtable

### PR DESCRIPTION
**Pull request by Rikkola**
https://issues.redhat.com/browse/KOGITO-9153

We should merge https://github.com/kiegroup/kie-tools/pull/1488 first.

complete

### CODE REVIEW

**Comment by Rikkola** [comment]
Well I did not win the best gif of the week award, but there it is ;)

**Comment by caponetto** [comment]
@Rikkola As you can see in the CI runs, there are some issues raised by ESLint. Can you please fix them?

**Comment by caponetto** [comment]
@Rikkola can you please rebase this PR with main?

**Comment by caponetto** [comment]
@Rikkola can you please rebase this PR with main?

**Comment by Rikkola** [comment]
Rebase done. Let's see how it passes CI. Worked for me locally.

**Comment by Rikkola** [comment]
Still needs some work. It did not update the new module names correctly.

**Comment by Rikkola** [comment]
@caponetto ok ready for feedback

**Comment by Rikkola** [comment]
This PR needs to swap to `json-yaml-language-service`

**Pull request closed without merging**
