### PR TITLE
KOGITO-3665: Integrate with "Properties" panel

### PR DESCRIPTION
**Pull request by vpellegrino**
integration_w_properties_panel

- Design doc describing what is covered: https://docs.google.com/document/d/1nRsIm7S6x53156-deWsiWBaWvDQcuq_PnAW6GEc8nVo/edit?usp=sharing
- Note that cell selection will be managed by https://issues.redhat.com/browse/KOGITO-3655 and https://issues.redhat.com/browse/KOGITO-6608
- While reviewing https://github.com/kiegroup/kie-tools/pull/825, it comes to my mind that maybe also keyboard navigation should trigger the Properties panel, WDYT @jomarko @yesamer @fantonangeli? If yes, we should manage it after https://github.com/kiegroup/kie-tools/pull/825 (and navigation on the header cells) get finished.

### CODE REVIEW

**Comment by yesamer** [comment]
> * While reviewing [KOGITO-3655: Implement cells keyboard navigation and editing #825](https://github.com/kiegroup/kie-tools/pull/825), it comes to my mind that maybe also keyboard navigation should trigger the Properties panel, WDYT @jomarko @yesamer @fantonangeli? If yes, we should manage it after [KOGITO-3655: Implement cells keyboard navigation and editing #825](https://github.com/kiegroup/kie-tools/pull/825) (and navigation on the header cells) get finished.

Good point, totally agree with you!

**Comment by jomarko** [comment]
+1 https://github.com/kiegroup/kie-tools/pull/852#issuecomment-1041208494

**Comment by fantonangeli** [comment]
Good point! I agree that we should manage it at least after https://github.com/kiegroup/kie-tools/pull/825
The call from the keyboard navigation should be triggered from the TableBody component in a "centralized" way that it's already prepared in the code. Because of that, I think it's not needed to wait for the header cell navigation PR. 

BTW I'm refining the PR on that side and I should finish that today.

**Comment by vpellegrino** [comment]
@yesamer @fantonangeli @jomarko I just rebased this branch, feel free to review. Thanks :1st_place_medal:

**Comment by vpellegrino** [comment]
@jomarko after rebasing, we have for `CI :: Monorepo / monorepo-pr-ci (ubuntu-latest) (pull_request)` one single failing test (`DMNExpressionEditor.ts`):
image

Any suggestion?

**Comment by jomarko** [comment]
@vpellegrino I found this during manual check

- switch to new boxed expression editor, this error was in browser log, is that known issue or related to changes in this PR? [1]
- I opened sample DMN, selected some input column header cell, changed the column data type in properties panel
  - in old editor no re-render
  - in new editor it causes complete rerender
- after finished the step above I switched back to odl editor, that became much slower in responding clicking cells

About the failing test, I will try to have a look on it in the meantime. possibly open an fix against your PR.

[1]
Screenshot from 2022-02-21 12-34-14

**Comment by vpellegrino** [comment]
@jomarko the error in the screenshot is well known and it causes nothing to the user. FYI, it is caused by Patternfly's `Menu` (popover-based components) which are not reactively canceling async subscriptions when a component that is using them (in this case `TableHandlerMenu`) removes them from the DOM.

**Comment by vpellegrino** [comment]
@jomarko thanks I merged your proposal to fix that flaky test. Let's see the build result.

**Comment by vpellegrino** [comment]
@jomarko about the second point on https://github.com/kiegroup/kie-tools/pull/852#issuecomment-1046786594 I'm not sure that the issue on the `old` editor + its latency have been introduced by this PR. Have you already checked such behavior on the `main` branch, please?

**Comment by jomarko** [comment]
@vpellegrino I checked the main now. There I do not see the slowdown. I did:
- switch to beta
- edit cells, as data so header
- switch to stable
- select different cells

The issue is using main I can not edit especially header cells by properties panel

**Review by yesamer — APPROVED** [review]
LGTM @vpellegrino

**Review by jomarko — APPROVED** [review]
@vpellegrino thank you. I prepared cypress test separately https://github.com/kiegroup/kie-tools/pull/870

**Review by fantonangeli — APPROVED** [review]
Awesome!

**Comment by vpellegrino** [comment]
FYI, regarding https://github.com/kiegroup/kie-tools/pull/852#issuecomment-1041208494 I traced https://issues.redhat.com/browse/KOGITO-6827
@yesamer when you're ready feel free to merge this PR, thanks

**Pull request merged**
