### PR TITLE
kie-issues#685: DMN Editor: Import Java Classes button is not enabled

### LINKED ISSUE #685: DMN Editor: Import Java Classes button is not enabled
Since the 0.32.0 version of our extension, the "Import Java Classes" button doesn't work anymore.  Downgrading to 0.31.0 solves the issue. 

It seems there's some API change introduced in the last JDT.LS version, according to the logs:

```
org.eclipse.core.runtime.CoreException: Plug-in vscode-java-code-completion-extension-plugin-core was unable to load class org.kogito.core.internal.DelegateHandler.
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.throwException(RegistryStrategyOSGI.java:212)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:198)
	at org.eclipse.core.internal.registry.ExtensionRegistry.createExecutableExtension(ExtensionRegistry.java:920)
	at org.eclipse.core.internal.registry.ConfigurationElement.createExecutableExtension(ConfigurationElement.java:246)
	at org.eclipse.core.internal.registry.ConfigurationElementHandle.createExecutableExtension(ConfigurationElementHandle.java:63)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$DelegateCommandHandlerDescriptor.getDelegateCommandHandler(WorkspaceExecuteCommandHandler.java:114)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:223)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
	at org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:220)
	at org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$4(JDTLanguageServer.java:616)
	at org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:87)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.kogito.core.internal.DelegateHandler cannot be found by vscode-java-code-completion-extension-plugin-core_0.32.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:541)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:536)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:416)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:168)
	at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.loadClass(EquinoxBundle.java:622)
	at org.eclipse.core.internal.registry.osgi.RegistryStrategyOSGI.createExecutableExtension(RegistryStrategyOSGI.java:196)
	... 16 more
```
In addition, the error message is stale (the annotation is no longer required)

Screenshot 2023-11-08 at 17 41 17

### PR DESCRIPTION
**Pull request by yesamer**
Closes: https://github.com/apache/incubator-kie-issues/issues/685

- In the `build.properties` file, the `source` key was incidentally changed [here](https://github.com/kiegroup/kie-tools/pull/1920) to `ource`. That was the reason for the issue
- Removed any reference to the old Annotation previously mandatory to enable the feature.
- Updated JDT.LS to 1.29
- Updated freemarker
- Removed generated Java Autocompletion jar in BPMN Editor: not used here, it doesn't make sense to add it.

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by yesamer** [comment]
@tiagobento @Josephblt I don't understand why is failing here:

`.../kie-sandbox-extended-services-image build:dev: cp: cannot stat '../extended-services-java/dist/extended-services-java': No such file or directory`

It fails in my local too. Can you please doublecheck?

**Comment by Josephblt** [comment]
Hello @yesamer. I'm not home today. I'll check it tomorrow. As soon as I have something I'll get back to you.

**Comment by Josephblt** [comment]
Hello @yesamer. Here is the fix for the failing builds in your PR.
https://github.com/kiegroup/kie-tools/pull/2050
As soon as it gets merged, I'll let you know and you can rerun the builds.

**Comment by yesamer** [comment]
> Hello @yesamer. Here is the fix for the failing builds in your PR. #2050 As soon as it gets merged, I'll let you know and you can rerun the builds.

Thank you @Josephblt

**Pull request merged**
