### PR TITLE
KOGITO-3152: [DMN Designer] PMML support - function parameters generation

### PR DESCRIPTION
**Pull request by yesamer**
Only PMML Field models with usageType = "active" or null should be considered.

**JIRA**: [KOGITO-3152](https://issues.redhat.com/browse/KOGITO-3152)

**Referenced Pull Requests**:
https://github.com/kiegroup/appformer/pull/1041
https://github.com/kiegroup/kie-wb-common/pull/3410
https://github.com/kiegroup/kogito-tooling/pull/266

### CODE REVIEW

**Review by jstastny-cz — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]
@yesamer Approving, but if you could reassess the need of tests, it would be great. Ideally, we should try and not merge PRs without tests. If there's already test cases covering this, please ignore my comment :)

**Comment by yesamer** [comment]
@tiagobento thank you, you're right, my apologies for missing tests on my last PRs on this repo. I created a ticket to provide them https://issues.redhat.com/browse/KOGITO-3354 and, in addition, my commitment to provide tests in my future PRs :)

**Review by karreiro — APPROVED** [review]
Thank you, @yesamer!

**Comment by yesamer** [comment]
@kiegroup/gatekeepers Can you please merge it?

**Pull request merged**
