### PR TITLE
 KOGITO-204: Update docks locators 

### PR DESCRIPTION
**Pull request by jomarko**
KOGITO-204 Update docks locators
    
Due to changes introduced in [1] and [2] the docks locators needs to be updated
[1] - https://github.com/kiegroup/kie-wb-common/pull/3333
[2] - https://github.com/kiegroup/appformer/pull/987

### CODE REVIEW

**Comment by tiagobento** [comment]
@jomarko Since you're updating the Editors too, I believe we should only consider the FDB results for this PR, right? cc @jstastny-cz

**Comment by jomarko** [comment]
@tiagobento yes, that is why this is a Draft state, not sure what is the moment the added integration tests will reflect my changes in the editor.

**Comment by tiagobento** [comment]
@jomarko We're now working with fixed versions for the Editors, so IT tests won't pass until we upgrade the version. That's why FDB should be considered. However, after releasing that, the IT tests that are failing on this PR will continue failing until we upgrade the version of the Editors. That's a challenging topic about our environment, so we are working on ways to overcome that.

**Comment by jomarko** [comment]
@tiagobento yes, I understand, I keep this as a draft until the situation is more clear. https://issues.redhat.com/browse/KOGITO-4130

**Comment by jomarko** [comment]
Jenkins please retest this

**Comment by jomarko** [comment]
Replaced by #382

**Pull request closed without merging**
