### PR TITLE
KOGITO-4666: Converge the CSS to avoid conflicts between PF3 and PF4

### PR DESCRIPTION
**Pull request by caponetto**
@tiagobento @manstis can you guys take a look?

@manstis 
With these changes, I believe the only code that you'll need in your `style.scss` is:
```css
.pf-c-button.pf-m-secondary {
  color: var(--pf-global--primary-color--100);
}

.pf-c-button.pf-m-primary {
  color: var(--pf-global--Color--light-100);
  background-color: var(--pf-global--primary-color--100);
}
```

### CODE REVIEW

**Comment by tiagobento** [comment]
LGTM!

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
@tomasdavidorg Can you please take a look?

**Review by tomasdavidorg — APPROVED** [review]

**Review by manstis — APPROVED** [review]
Works well. 

Thank-you @caponetto.

**Comment by caponetto** [comment]
We decided to remove the switch between themes for the shortcuts panel. 
Now it is kept "light" regardless the VS Code theme.

The behavior for the loading screen is kept, though.
Could you guys take another look? I just pushed a new commit.
Thanks!

**Comment by manstis** [comment]
@caponetto LGTM (with the most recent [commit](https://github.com/kiegroup/kogito-tooling/pull/443/commits/109a2f4284798bdfbef343dc4e7193d6a601ac48)).

**Review by tomasdavidorg — APPROVED** [review]
Looks good to me.

**Pull request merged**
