### PR TITLE
KOGITO-5933: Enable the new Boxed Expression Editor in all Kogito channels

### PR DESCRIPTION
**Pull request by vpellegrino**
**PR dependent on**: https://github.com/kiegroup/kogito-tooling/pull/634, https://github.com/kiegroup/kogito-editors-java/pull/118
Loading **`dmn-loader.js/.css** in the DMN editor

### CODE REVIEW

**Comment by tiagobento** [comment]
@vpellegrino Thanks for the PR!

This PR won't be green until we update the Editors version. Please merge the PR on `kogito-editors-java` first, then release a new version and update this PR with the new version.

**Comment by jomarko** [comment]
Jenkins please retest this

**Review by jomarko — COMMENTED** [review]
As part of https://github.com/kiegroup/kogito-editors-java/pull/120 review, @danielzhe provided me a vsix, that should contain changes of #631, see [comment](https://github.com/kiegroup/kogito-editors-java/pull/120#issuecomment-934013253)

During work with new expression editor, I found this blocking scenario.

- Open a DMN file
- Add a decision node, open its expression editor, turn on new editor, set its root expression as a Context, then the first context entry as a Decision Table
- Add another decision node, set its root expression again as a Context, then the first context entry as a Function
- Return the the expression editor of the first added Decision node

The expression will be not rendered correctly
Screenshot from 2021-10-05 13-47-37

**Comment by vpellegrino** [comment]
> As part of [kiegroup/kogito-editors-java#120](https://github.com/kiegroup/kogito-editors-java/pull/120) review, @danielzhe provided me a vsix, that should contain changes of #631, see [comment](https://github.com/kiegroup/kogito-editors-java/pull/120#issuecomment-934013253)
> 
> During work with new expression editor, I found this blocking scenario.
> 
> * Open a DMN file
> * Add a decision node, open its expression editor, turn on new editor, set its root expression as a Context, then the first context entry as a Decision Table
> * Add another decision node, set its root expression again as a Context, then the first context entry as a Function
> * Return the the expression editor of the first added Decision node
> 
> The expression will be not rendered correctly !

@jomarko the issue you are talking about it seems to not be reproducible with [plugin](https://drive.google.com/file/d/1aZxAeqv7oMwRCKvQklrWpSVFfMwKWYmI/view?usp=sharing) produced on `KOGITO-5933` branch:
switch_from_context_to_another

**Comment by jomarko** [comment]
@vpellegrino ok, thank you, so it seems it is related to @danielzhe changes on kiegroup/kogito-editors-java#120 and we are fine here in #631

**Comment by tiagobento** [comment]
@jomarko Is there any Jenkins job that runs here? If you want to re-trigger the GitHub Actions workflows, the author of the PR can push an empty commit.

**Comment by vpellegrino** [comment]
> @jomarko Is there any Jenkins job that runs here? If you want to re-trigger the GitHub Actions workflows, the author of the PR can push an empty commit.

@tiagobento I am waiting for the editors' version merge (https://github.com/kiegroup/kogito-tooling/pull/634), in order to rebase this PR and run all checks

**Comment by vpellegrino** [comment]
> As part of [kiegroup/kogito-editors-java#120](https://github.com/kiegroup/kogito-editors-java/pull/120) review, @danielzhe provided me a vsix, that should contain changes of #631, see [comment](https://github.com/kiegroup/kogito-editors-java/pull/120#issuecomment-934013253)
> 
> During work with new expression editor, I found this blocking scenario.
> 
> * Open a DMN file
> * Add a decision node, open its expression editor, turn on new editor, set its root expression as a Context, then the first context entry as a Decision Table
> * Add another decision node, set its root expression again as a Context, then the first context entry as a Function
> * Return the the expression editor of the first added Decision node
> 
> The expression will be not rendered correctly ![Screenshot from 2021-10-05 13-47-37]

@jomarko I have an update about this issue.
Even if it was not reproducible on the branch `KOGITO-5933` (on `kogito-editors-java`), after updating to the latest commits (`main` branch`), I am able to reproduce it.
image
So, my guess is that this issue has been introduced after "copy/paste support" or after "column width updated too many times fix".
How do you propose to proceed? In the meantime, let me check which of these two commits has introduced the issue.

**Comment by vpellegrino** [comment]
@jomarko by reverting the commit **KOGITO-5909: [DMN Designer] New Boxed Expression editor - DMN Expression column width is updated too many times in some scenarios** (ab897150cbfaa5212492e984c54ad15c5dc86c59) the issue is not present anymore.
Please let me know how do we want to proceed:
1) Revert that commit and reopen the ticket
2) Keep that commit, but open a ticket to fix all currently broken scenarios (like the decision table nested in the context table).
3) ...?

Independently from that decision, which will affect only the `kogito-editors-java` repository, I think this PR can be reviewed and eventually merged (cc @tiagobento @yesamer).

**Review by yesamer — APPROVED** [review]
@vpellegrino Thank you, it works for me.

**Comment by tiagobento** [comment]
@vpellegrino CI is still breaking, seems like some tests are failing on the Standalone Editors. Can you please take a look?

**Comment by vpellegrino** [comment]
> @vpellegrino CI is still breaking, seems like some tests are failing on the Standalone Editors. Can you please take a look?

It seems that also in #634 the same CI was broken (https://github.com/kiegroup/kogito-tooling/runs/3803739871).
@tiagobento can you please let me know if it is a CI issue or something related to this PR?
I can see in the logs few 404 errors.

**Comment by tiagobento** [comment]
@vpellegrino The errors are different. If you want to confirm, please push an empty commit to re-run the CI.

However, it seems like there's an issue there, though, as the tests breaking are only related to DMN.

**Comment by jomarko** [comment]
@vpellegrino thank you for your investigation. I can confirm the KOGITO-5909 revert fixed the scenario of parallel editing two boxed expressions, so I opened a revert PR https://github.com/kiegroup/kogito-editors-java/pull/132 and reopened the jira https://issues.redhat.com/browse/KOGITO-5909

Regarding the test failures in `kie-editors-standalone`. I can not confirm your findings. On my machine, the `main` branch pass in green. Then fetching your PR I get same errors as mentioned above by you and Tiago.


@jstastny-cz this PR introduces new boxed expression editor, that is written as a react app here https://github.com/kiegroup/kogito-editors-java/tree/main/kogito-editors-js/packages/boxed-expression-component

Is it possible that the issue is we need simply locad new js and css files into https://github.com/kiegroup/kogito-tooling/blob/main/packages/kie-editors-standalone/resources/dmn/index.html ?

**Comment by jstastny-cz** [comment]
@vpellegrino if addition of boxed editors poses new requirements on how the kie-editors-standalone should be used, we should promote the changes also into `packages/kie-editors-standalone/it-tests/` where there's a React app for tests themselves (See `webpack.config.js`, `src`, etc).
This might be a result of changes to kie-bc-editors, which affect kie-editors-standalone in some way - we might either need to bundle sth more into kie-editors-standalone package, or configure the testing app somehow (but that would require also proper documentation for users).

**Comment by jstastny-cz** [comment]
For investigation you can use `yarn start:it` from within `kie-editors-standalone` to start the testing app.

**Comment by jstastny-cz** [comment]
you'll see following:
Screenshot from 2021-10-07 11-43-39

Seems really like sth is broken along the way.

**Comment by jomarko** [comment]
@vpellegrino as mentioned earlier, I went trough all kogito channels and tried two scenarios
- open empty expression, turn on new editor, model expression, turn on old editor
- open existing expression, turn on new editor, model expression, turn on old editor

The results are:
- kie-editors-standalone: I am blocked blocked with verification due to above comments
- desktop: was not able to turn on new editor for existing expression, I used the sample diagram we provide directly on landing page
- online-editor: was not able to turn on new editor for existing expression, I used the sample diagram we provide directly on landing page
- chrome extension: needs to be read-only, currently when new editor is turned on, it is editable [1]
- vscode: ok

[1]
Screenshot from 2021-10-07 13-46-35

**Comment by vpellegrino** [comment]
@jomarko thanks for your checks:

- kie-editors-standalone: currently checking it. That project is totally new to me. So I need to understand which are the issues and how to solve them.
- desktop / online-editor: need help to reproduce/debug issues. I don't know these projects, so I need all steps to boot them.
- chrome extension: read-only was not yet planned for the `boxed-expression-editor`. Could you please open a JIRA for it?

**Comment by vpellegrino** [comment]
@jstastny-cz Thanks for explaining a bit the context of that app/tests to me. 
I am at the point you reported in the screenshot, but unable to understand which points I am missing.
@tiagobento, please, do you have any hints? Who is the SME on `kie-bc-editors` / `kie-editors-standalone`?

**Comment by jomarko** [comment]
@vpellegrino thank you
- I reported a separate issue for chrome-extension read only mode https://issues.redhat.com/browse/KOGITO-6074
- to build and run online-editor or desktop I use this:

```
kogito-tooling$ yarn
kogito-tooling$ yarn build:dev
kogito-tooling/packages/online-editor$ yarn start
kogito-tooling/packages/desktop$ yarn start
```

**Comment by vpellegrino** [comment]
I included the commit (editors' version upgrade) from https://github.com/kiegroup/kogito-tooling/pull/641.
Now, all checks are successful, except for `windows-latest` for Github's action internal server error:
image
image

When you are available, @jomarko, @jstastny-cz the PR is ready to be re-checked. Thanks for your help.

**Comment by jstastny-cz** [comment]
Cool, the standalone editors loads fine now. Thanks @vpellegrino for fixing that :-)

@jomarko should I review the functionality there or do you plan to do that?

**Review by tiagobento — APPROVED** [review]

**Comment by tiagobento** [comment]
Thanks @vpellegrino!! Great work. Good to merge when QE approves.

**Comment by jomarko** [comment]
@jstastny-cz re - https://github.com/kiegroup/kogito-tooling/pull/631#issuecomment-942178175

I will take  a look. Do not worry.

**Comment by jomarko** [comment]
### 01 online-editor, desktop, kie-editors-standalone, open decision table
Unable to open a specific decision table using new editor
https://issues.redhat.com/browse/KOGITO-6097

**Comment by jomarko** [comment]
### 02 online-editor, data type of the expressions
I tried to model using new expression editor. I changed also the data type of the expression, the problem is when I turn back to stable expression editor, the data type is lost, is this an issue we track in https://issues.redhat.com/browse/KOGITO-4588 or is it a separate issue please?

**Comment by jomarko** [comment]
### 03 online editor, edit mode indicator

I spotted missing cursor when started edit mode using pressing enter.
https://issues.redhat.com/browse/KOGITO-6098

**Comment by jomarko** [comment]
### 04 online editor, java function expression
User should not be able to change method and class entries. Reported as low priority/severity,
https://issues.redhat.com/browse/KOGITO-6100

**Comment by jomarko** [comment]
### 05 desktop, styling
The seems be some styles conflict after new boxed expression editor is used
https://issues.redhat.com/browse/KOGITO-6102

**Comment by jomarko** [comment]
### 06 kie-editors-standalone, readonly mode
Same as for chrome extension https://issues.redhat.com/browse/KOGITO-6074

**Comment by jomarko** [comment]
### 07 all channels, DRD support
I was not able to activate the new boxed expression editor for the diagram with DRDs
https://issues.redhat.com/browse/KOGITO-6103

**Comment by jomarko** [comment]
### 08 all channels, initial width

After swithing to new expression editor, all existing expressions are like bellow, will be this part of https://issues.redhat.com/browse/KOGITO-5909 or should I report a separate issue?

Screenshot from 2021-10-14 14-34-53

**Review by jomarko — COMMENTED** [review]
@vpellegrino thank you for this big step forward.

I put 8 comments and basically I could approve as all my findings should be addressed separately. However 2 of 8 comments I am not sure if we already have proper jira for them or we need another. Once this is clarified I will approve the PR.

@jstastny-cz should I mark you somehow special in jiras I reported and are standalone editors related? 

I prepared sanity checks https://github.com/kiegroup/kogito-tooling/pull/643 for:
- vs code
- standalone editors
- online editor

already, probably also chrome extension should follow. what do you think?

**Comment by jstastny-cz** [comment]
@jomarko feel free to set me as tester if it makes sense :-) or a watcher if someone else takes it as tester.

**Comment by vpellegrino** [comment]
> ### 08 all channels, initial width
> After swithing to new expression editor, all existing expressions are like bellow, will be this part of https://issues.redhat.com/browse/KOGITO-5909 or should I report a separate issue?
> 
> Screenshot from 2021-10-14 14-34-53

I am ok with opening a new JIRA issue. However, we should decide how the editor should behave.
Currently, when switching from `legacy` to `new` editor, for the table columns, we are keeping the same width of the `legacy` editor: https://github.com/kiegroup/kogito-editors-java/blob/60cb829075af787ad7dca22dbf100419d2587d96/kie-wb-common-dmn/kie-wb-common-dmn-client/src/main/java/org/kie/workbench/common/dmn/client/editors/expressions/jsinterop/util/ExpressionPropsFiller.java#L66
What do you suggest?

**Comment by vpellegrino** [comment]
> ### 02 online-editor, data type of the expressions
> I tried to model using new expression editor. I changed also the data type of the expression, the problem is when I turn back to stable expression editor, the data type is lost, is this an issue we track in https://issues.redhat.com/browse/KOGITO-4588 or is it a separate issue please?

If the issue is present **only** when a _custom_ data type is set, then KOGITO-4588 will cover it, otherwise a new JIRA should be reported.

**Review by jomarko — APPROVED** [review]
@vpellegrino thank you for your answers.

- I updated KOGITO-5909 jira so we address also a column width after switching from old to new one
- I was not able, fortunately, to reproduce an issue with lost data type anymore.

Thank you for this amazing new feature.

**Comment by yesamer** [comment]
@ederign @tiagobento Can we have a merge here? :)

**Pull request merged**
