### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by manstis**
I needed these additional libraries installed on Ubuntu 20.04.

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]

**Comment by yesamer** [comment]
@manstis @tiagobento  I would mention `epel` repository is required to install them
//cc @kelvah

**Comment by manstis** [comment]
@yesamer Eh? I didn't need any additional repositories to install them.

**Comment by yesamer** [comment]
@manstis It was necessary for me and for @kelvah. Are you using Fedora or RHEL?
(https://kie.zulipchat.com/#narrow/stream/232680-tooling/topic/extended-services.20deps)

**Comment by manstis** [comment]
@yesamer I use Ubuntu.

**Comment by yesamer** [comment]
@manstis Bingo, that's the reason. In RHEL is required to install that repo first.

**Comment by manstis** [comment]
@yesamer @kelvah @tiagobento Updated.

**Comment by tiagobento** [comment]
@manstis Thanks Michael for these instructions. I think our formatter is complaining about something on the changes you made. Can you please run `yarn format` on the repository root? This should fix the problem on the CI.

**Review by yesamer — APPROVED** [review]

**Comment by manstis** [comment]
@tiagobento Greeeeeeeeen!

**Pull request merged**
