### PR TITLE
kie-issues#2679: [SonataFlow] SonataFlow Management Console on KIE Tools daily dev job

### PR DESCRIPTION
**Pull request by fantonangeli**
**Closes** https://github.com/apache/incubator-kie-tools/issues/2679

:exclamation: Please do not merge until the repository is created. See [INFRA-26213](https://issues.apache.org/jira/browse/INFRA-26213) :exclamation: 

**Description:**
After the repo is created on dockerhub we need to update the KIE Tools daily dev job and add the image env vars and the the docker push command for SonataFlow Management Console.
See: https://github.com/apache/incubator-kie-tools/blob/main/.ci/jenkins/Jenkinsfile.daily-dev-publish
Discussion: apache/incubator-kie-kogito-docs#674 (comment)

@rodrigonull are there any other places which I need to update?

### CODE REVIEW

**Review by rodrigonull — APPROVED** [review]
Thank you @fantonangeli. 

For the daily dev job that should be everything we need.

For future releases we are going to need to create a new release job for this new image, similar to [this](https://github.com/apache/incubator-kie-tools/blob/main/.ci/jenkins/release-jobs/Jenkinsfile.dev-deployment-base-image) one:

**Review by ricardozanini — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Comment by ricardozanini** [comment]
@tiagobento we should not have merged this PR since we don't have the dockerhub repo yet.

**Comment by tiagobento** [comment]
Sorry, I overlooked the DO NOT MERGE label. Will revert this.

**Comment by tiagobento** [comment]
Revert PR: https://github.com/apache/incubator-kie-tools/pull/2690

**Pull request merged**
