### PR TITLE
KOGITO-1349: Dev Tools - Update Patternfly to current version

### PR DESCRIPTION
**Pull request by ljmotta**
## Task
https://issues.redhat.com/browse/KOGITO-1349

## Checks
https://docs.google.com/spreadsheets/d/1VFhPrxj-qr8-JY9L0kSBAq0nL1aUkpmNyGvgDJ0iPmE/edit#gid=0

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]
Suspiciously smooth!! 😝 

Glad it worked so well, nice job putting together a spreadsheet with the checks you made. Approving because the code looks ok and the build is green. @ederign Please only merge it once all checks are "ok" on the spreadsheet.

**Comment by ljmotta** [comment]
I got suspicious too!! a version update can cause a lot of trouble but everything went well.
I've already done all the checks on the spreadsheet, everything looks OK. If any other check is necessary, let me know :blush:

**Comment by ederign** [comment]
Use: https://github.com/kiegroup/kie-wb-common/pull/3296

**Review by srambach — APPROVED** [review]
I can't find any visual differences. bitmoji

**Comment by jomarko** [comment]
Manual/visual check of components to confirm their basic functionality is not broken.
- [x] desktop
- [ ] hub
- [x] online editor (Firefox, Chrome)

**Review by jomarko — COMMENTED** [review]
Screenshot from 2020-05-15 10-05-48

@ljmotta thank you for PR. I am done with review. I found only one minor issue that hub can not be resized. Is it known/expected behavior?

**Comment by tiagobento** [comment]
@jomarko Hi! The Hub app was designed not to be resized. do you mind opening a JIRA for this issue you found? I think we just might remove the kebab menu, since there's no "Update" feature yet.

**Review by jomarko — APPROVED** [review]
Found issue reported https://issues.redhat.com/browse/KOGITO-2203

**Review by ederign — APPROVED** [review]

**Pull request merged**
