### PR TITLE
KOGITO-7898: Upgrade KIE Sandbox Runtime

### PR DESCRIPTION
**Pull request by yesamer**
https://issues.redhat.com/browse/KOGITO-7898

This PR scope is to update the `kogito` version, mainly for 2 reasons.
- Introducing the new features introduced in the DMN Engine in the last few months;
- Resolving bugs and securities issues;

@domhanak @caponetto can you please review it?

### CODE REVIEW

**Review by caponetto — APPROVED** [review]
LGTM, thanks @yesamer!

Can you please share what are the new features introduced in the new version?
Thus, tests can be more focused on them.

Also, keep in mind that, the DMN Dev Sandbox is still on version `1.12.0-Final` ([reference](https://github.com/kiegroup/kie-tools/blob/main/packages/root-env/env/index.js#L55)), which offers a similar experience with the form. Given some memory issues in the past, I would test a full deployment when updating this one, just to make sure the OpenShift Sandbox can run it properly.

**Comment by yesamer** [comment]
@caponetto I don't have a full list of the introduced changes, the most important one is the introduction of new [DMN 1.4 features](https://docs.kogito.kie.org/latest/html_single/#_runtime_support_for_dmn_specification_v1_4). As an example of the new introduced feature in 1.4, I can mention: https://docs.jboss.org/kogito/release/latest/html_single/#_context_functions (which the one required in the ticket)
If updating to kogito `1.28.0` is too risky, we can consider updating to version `1.16.0` to satisfy the minimum requirement of this task. Otherwise, I think it's not bad having the latest version here.

I agree with you, we need to test this update together with the newly introduced features, for that, I ask your and @domhanak support

**Review by tiagobento — CHANGES_REQUESTED** [review]
Please keep in mind that this issue was already mapped in https://issues.redhat.com/browse/KOGITO-7898.

Also, we can't upgrade JIT Executor alone. The tooling platform depends on the Runtimes in more than one front:
1. JIT Executor for DMN Runner
2. Quarkus platform version for DMN Dev Sandbox
3. Can't remember if we have any other place declaring this dependency. Need to search for the version number and see what you find, or search for PRs that did a similar upgrade in the past.

@yesamer Please take my comment into account, we should avoid scattering the Runtimes versions we have on Tools.

**Comment by tiagobento** [comment]
@yesamer Also, please keep the Jira number and description on the PR aligned with what's in Jira. Either rename the PR or the Jira.

**Comment by yesamer** [comment]
Tests are failing, most probably because of an API \ Logic change.
Examples of differences:
Expected: `DMNType{ https://github.com/kiegroup/drools/kie-dmn/_A4BCA8B8-CF08-433F-93B2-A2598F19ECFF : OutputSet1 }`
Actual: `https://github.com/kiegroup/drools/kie-dmn/_A4BCA8B8-CF08-433F-93B2-A2598F19ECFF : InputSetTraffic Violation }`

**Comment by domhanak** [comment]
@yesamer I do not have bandwidth to look at this in  the near future.

**Comment by yesamer** [comment]
Closing - Wrong branch management.

**Pull request closed without merging**
