### PR TITLE
KOGITO-9051: Decreasing SWF classes/modules

### PR DESCRIPTION
**Pull request by treblereel**
* errai dom primitivies
 * kie-wb-common-stunner-widgets
 * kie-wb-common-ui
 * uberfire-widgets-commons
 * uberfire-commons-editor-api
 * uberfire-wires-core-grids
 * uberfire-layout-editor-client
 * uberfire-layout-editor-api
 * errai-validation
 * removed @Property and so on
 * errai-databinder
 * gwtbootstrap deps
 
 JIRA: https://issues.redhat.com/browse/KOGITO-9051

### CODE REVIEW

**Comment by treblereel** [comment]
@romartin Let's check, I didn't remove something useful :)

**Comment by romartin** [comment]
thanks @treblereel for this work .looks great!

I will proceed with some smoketesting on this. Also assigned it to @LuboTerifaj for testing.

As far as I understand this is just a clean-up of dead code / dependencies, but no logic really being changed, correct? So we just have to do some smoketesting on the app again I guess.

Thanks!

**Comment by treblereel** [comment]
> thanks @treblereel for this work .looks great!
> 
> I will proceed with some smoketesting on this. Also assigned it to @LuboTerifaj for testing.
> 
> As far as I understand this is just a clean-up of dead code / dependencies, but no logic really being changed, correct? So we just have to do some smoketesting on the app again I guess.
> 
> Thanks!

@romartin  Yeap, there are no business logic changes. Mostly dead code elimination and refactoring

**Comment by romartin** [comment]
Hey @treblereel 

The vscode extension bundle for SWF has been decreased from 10.3Mb to 9Mb, so **1.3Mb less**. This is great! 

Although I am wondering how much we can still drop in order to keep reducing the size of the bundle. Do you know if Is there any other dead code or unnecessary dependencies we can still remove, as a second iteration of this work, WDYT?

**Comment by romartin** [comment]
Hey @treblereel 

I have just tested the UI, everything works except **one issue found**, I think it should be related to this PR because I just tested the main branch (HEAD), and it works. The issue is:

Once clicking on the _Preview_ icon, the preview window (popup) does not appear, see screenshot, where button has been clicked but nothing happens:

preview-icon

Instead, it should be showing the following popup (screenshot taken from main HEAD):
Screenshot from 2023-05-22 15-43-18

**Comment by treblereel** [comment]
> Hey @treblereel
> 
> I have just tested the UI, everything works except **one issue found**, I think it should be related to this PR because I just tested the main branch (HEAD), and it works. The issue is:
> 
> Once clicking on the _Preview_ icon, the preview window (popup) does not appear, see screenshot, where button has been clicked but nothing happens:
> 
Thank you, yeah, I missed it, restored

**Comment by romartin** [comment]
ok thanks @treblereel ,so ready for review again?

**Comment by treblereel** [comment]
@romartin yeap

**Comment by romartin** [comment]
Hey @treblereel 

When you are back from the leave, please consider rebasing this and letting us know is ready for review. I am really wondering to apply this :)

Thanks!

**Comment by treblereel** [comment]
@romartin @LuboTerifaj rebased, ready for the review

**Review by romartin — APPROVED** [review]
Hey @treblereel 

Issue fixed, thanks! All good for me!

@LuboTerifaj  your turn please :)

**Review by LuboTerifaj — APPROVED** [review]
Hello @treblereel , I didn't find any issues. Thank you!

**Comment by ederign** [comment]
Great work guys! /cc @mdproctor ^

**Pull request merged**
