### PR TITLE
kie-issues#518: PMML Editor development mode is partially broken

### LINKED ISSUE #518: PMML Editor development mode is partially broken
Pmml editor development is usually like:
- pnpm bootstrap
- pnpm -f pmml-editor… build:dev
- pnpm -f pmml-editor start

The problem appears once user executes last step and access the editor in browser, the attached error screen appears. Once the screen is closed, editor can be used, however expected state is no error screen appears.

Screenshot 2023-08-22 140523

ERROR in /home/jomarko/github/kie-tools/packages/pmml-editor/dev-webapp/index.tsx

18:26-37

[tsl] ERROR in /home/jomarko/github/kie-tools/packages/pmml-editor/dev-webapp/index.tsx(18,27)

      TS7016: Could not find a declaration file for module 'react-dom'. '/home/jomarko/github/kie-tools/node_modules/.pnpm/react-dom@17.0.2_react@17.0.2/node_modules/react-dom/index.js' implicitly has an 'any' type.

  If the 'react-dom' package actually exposes this module, consider sending a pull request to amend 'https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-dom'

ts-loader-default_1efb66a47af87b8e

webpack 5.70.0 compiled with 1 error in 13186 ms

### PR DESCRIPTION
**Pull request by yesamer**
Closes https://github.com/kiegroup/kie-issues/issues/518

Adding `"@types/react-dom"` as a dependency fixes the issue.

### CODE REVIEW

**Comment by tiagobento** [comment]
That's weird :o

I mean, why does this work? Andn why do we have `@types/*` dependencies on the `dependencies` list instead of `devDependencies`?

**Comment by yesamer** [comment]
IDK :)

**Comment by tiagobento** [comment]
It would be good to understand this, because this is not the way things should be... `devDependencies` are included in `node_modules` the same as `dependencies`...

**Comment by yesamer** [comment]
> It would be good to understand this, because this is not the way things should be... `devDependencies` are included in `node_modules` the same as `dependencies`...

"@types/react-dom" was missing in both dependency / dev-dependency.
Moved it to the devDependency list, together with all defined `@types/*` previously defined.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
