### PR TITLE
KOGITO-1668: Fix drag and drop CSS and upload button validation

### PR DESCRIPTION
**Pull request by ljmotta**
## Task
https://issues.redhat.com/browse/KOGITO-1668

## Demo
CSS flick
css-flick

css-fix

Warning message
button-warning

button-warning-fix

### CODE REVIEW

**Review by tiagobento — APPROVED** [review]
Nice PR @ljmotta! Thank you! Directly manipulating the DOM inside React components is usually not a good idea, thanks for removing that!

**Review by ederign — APPROVED** [review]

**Comment by srambach** [comment]
This implementation looks fine to me for this design. My only comment is that we should probably make a future task to design another mechanism to show the error message to the user. This one doesn't get announced to a screenreader, and is transient. Both of these are a11y problems. There is now a file upload PF component that we investigate using in the future. https://www.patternfly.org/v4/documentation/react/components/fileupload#text-file-with-restrictions

**Review by srambach — APPROVED** [review]

**Comment by ljmotta** [comment]
@srambach Thanks for the review! This PR was a just minor fix to the current style, we already created a JIRA to solve the a11y issue (https://issues.redhat.com/browse/KOGITO-1517). About the component update, we can look into it after the PF update (https://issues.redhat.com/browse/KOGITO-1349).

**Review by ederign — APPROVED** [review]

**Review by jomarko — APPROVED** [review]
Seems working fine to me, thank you

**Pull request merged**
