### PR TITLE
kie-issues#1033: Fix sonataflow-quarkus-devui-extension to adapt it to the Quarkus 3.8 Dev UI

### LINKED ISSUE #1033: Fix `sonataflow-quarkus-devui-extension` to adapt it to the Quarkus 3.8 Dev UI

### PR DESCRIPTION
**Pull request by paulovmr**
Closes https://github.com/apache/incubator-kie-issues/issues/1033

### CODE REVIEW

**Comment by tiagobento** [comment]
@paulovmr Do we really have to wait? I mean, even with those changes, the Dev UI is still compatible with Quarkus 3.2, no?

**Comment by paulovmr** [comment]
@tiagobento no, actually I tested with a example running on Quarkus 3.2 and it is working. I edited my restriction comment.

**Comment by pefernan** [comment]
guys, let me review tomorrow. I don't see much problem but I'd like to give it a test.

**Review by pefernan — APPROVED** [review]
@paulovmr great!

my only "but" is about adding the `-extension` suffix to the artifactId, this isn't matching  the new artifacts naming, but if this has been agreed I'm ok..

**Comment by paulovmr** [comment]
@pefernan I added the route you mentioned to me now. I will take a look at the naming of the other extensions and send a separate PR if necessary to rename it.

**Comment by pefernan** [comment]
@paulovmr https://docs.google.com/spreadsheets/d/1IN9bH2rCxbV7dcehItqwELfTNaGrXKFT8Ppj6a5Jeb4/edit?usp=drivesdk

**Pull request merged**
