### PR TITLE
kie-issues#1034: Copy `kogito-serverless-operator` to `kie-tools`

### LINKED ISSUE #1034: Copy `kogito-serverless-operator` to `kie-tools`
Create a new package `packages/sonataflow-operator` on `kie-tools`, hosting the relevant parts of https://github.com/apache/incubator-kie-kogito-serverless-operator so that `kn-plugin-workflow` can depend on it, instead of pointing to https://github.com/kiegroup/kogito-serverless-operator.

This task is only to move it and integrate it with the build, no changes to `packages/kn-plugin-workflow` need to be done as part of this task.

### LINKED ISSUE #1035: Adapt `packages/kn-plugin-workflow` on `kie-tools` to point to `packages/sonataflow-images` and `packages/sonataflow-operator`
With 

- #1001; and
- #1034 

done, change `packages/kn-plugin-workflow` to point to the new packages instead of https://github.com/kiegroup/kogito-serverless-operator, https://github.com/apache/incubator-kie-kogito-images, and https://github.com/apache/incubator-kie-kogito-serverless-operator.

Optionally we can rename `packages/kn-plugin-workflow` to `packages/kn-plugin-sonataflow`.

### PR DESCRIPTION
**Pull request by thiagoelg**
Closes https://github.com/apache/incubator-kie-issues/issues/1034
Closes https://github.com/apache/incubator-kie-issues/issues/1035

Changes made from the original repo:

- development version changed from 999.0.0-snapshot to 0.0.0 on all files

- Makefile:
  - e2e scripts added to perform e2e tests in a single command
  - fmt script called after generate
  - VERSION changed from 999.0.0-snapshot to 0.0.0 by default
  - BUILDER changed from podman to docker
  - added test-workflowproj and test-container-builder to test script
  - build now calls generate-all instead of generate
  
  See the diff here https://gist.github.com/thiagoelg/16b3d44bab0312521ef63015f6cad9d4

- hack/bump-version.sh
  - replaced snapshot logic to 0.0.0
  - [fixed script for removed image.yaml](https://ci-builds.apache.org/job/KIE/job/kogito/job/main/job/other/job/kogito-serverless-operator.weekly-deploy/lastBuild/console)
  - fixed and added new find/sed to replace image names and versions
  
  See the diff here https://gist.github.com/thiagoelg/17c047c176f93eb107d70fc40a7e01f3

### CODE REVIEW

**Comment by tiagobento** [comment]
@ricardozanini We had to do some modifications to the `hack/bump-version.sh` script, as it was out of date due to some recent changes that were introduced... Please check if those are ok.

There are two files, though, that aren't being updated and we're not sure how to proceed. Those files are:
1. ~config/manager/manager.yaml~ (EDIT: Wrong path)
1. images/manager.yaml
2. images/bundle.yaml

---

To test the script, you can clone the repo and run `pnpm bootstrap -F kogito-serverless-operator && pnpm update-version-to 1.2.3 -F kogito-serverless-operator`. This will execute the `install` script of on `packages/kogito-serverless-operator/package.json`, which calls `hack/bump-version.sh`.

**Comment by tiagobento** [comment]
@ricardozanini Note that if you're on macOS, the `sed` version that comes installed with it is pretty old, so you need to install an updated version of `sed` for it to work properly.

We're using the Nix.dev configuration, so it works fine because it already installs `sed` 4.9, but for people using `sed` that comes with macOS, this will error out. Same happens in our CI. Are you developing on a macOS? If so, what did you do to work around this problem? I wonder if we should use another command to do this treatment...

**Comment by ricardozanini** [comment]
@tiagobento I'm currently on PTO, I can't try anything locally since I don't have access to my work notebook atm.

I'm aware that sed won't work properly on MacOS, I have an alternative version installed that works fine following the bash implementation.

Regarding the changes, these files you mention are auto-generated by the `make generate-all` command we run after the bump script, so it's expected to revert/change anything from sed. Everything inside `config` is auto-generated by the `kustomization` files.

What's the matter with the YAML, can you describe?

**Comment by tiagobento** [comment]
@ricardozanini Ok! Thanks for the reply.

We'll think about the `sed` problem so we don't cause too much inconvenience for people working on `kie-tools`...

As for the other problem, in both YAMLs, the `version` property still has whatever we declare as in `OperatorVersion` at `version/version.go`. We're not sure if those should be updated or not, but we assume they should, as `999.0.0-snapshot` doesn't seem something we want mentioned on the release.

We can alter the `hack/bump-version.sh` script without a problem. We understand what it does and are comfortable updating it, we just need confirmation that those `version` properties in both files should indeed be updates with whatever version we pass to `hack/bump-version.sh`. In the case of the next release, `10.0.0`.

**Comment by ricardozanini** [comment]
@tiagobento if the script is not updating the version.go file, it should. Can you please paste the excerpt of the resulting YAML files here so I can see them from my phone? Thanks!

**Comment by tiagobento** [comment]
@ricardozanini version.go is fine. The problem is the YAMLs... I'll send them here in a bit.

**Comment by thiagoelg** [comment]
<table>
<tr><td>images/manager.yaml
<tr><td>

```yaml
- name: operator-builder
  version: 0.0.0
  from: "golang:1.21.6"
  description: Builder Image for the Operator

  args:
    - name: SOURCE_DATE_EPOCH
      value:

  modules:
    repositories:
      - path: modules
    install:
      - name: org.apache.kie.sonataflow.goModDownload
      - name: org.apache.kie.sonataflow.operatorBuilder

- name: sonataflow-operator
  version: 0.0.0
  from: "registry.access.redhat.com/ubi9/ubi-micro:9.3-9"
  description: Runtime Image for the Operator

  args:
    - name: SOURCE_DATE_EPOCH
      value:

  labels:
    - name: maintainer
      value: dev@kie.apache.org

  artifacts:
    - path: /workspace/manager
      image: operator-builder
      dest: /usr/local/bin
      name: manager

  run:
    workdir: /usr/local/bin
    user: "65532:65532"
    entrypoint:
      - manager
```

<tr><td>images/bundle.yaml
<tr><td>

```yaml
schema_version: 1
name: "sonataflow-operator-bundle"
description: "SonataFlow Operator Bundle"
version: 0.0.0
from: "scratch"

labels:
  - name: maintainer
    value: dev@kie.apache.org
  - name: io.k8s.description
    value: Operator Bundle for deploying OpenShift Serverless Logic Operator
  - name: io.k8s.display-name
    value: SonataFlow Operator Bundle
  - name: io.openshift.tags
    value: sonataflow,serverless,workflow,operator
  - name: operators.operatorframework.io.bundle.mediatype.v1
    value: registry+v1
  - name: operators.operatorframework.io.bundle.manifests.v1
    value: manifests/
  - name: operators.operatorframework.io.bundle.metadata.v1
    value: metadata/
  - name: operators.operatorframework.io.bundle.package.v1
    value: sonataflow-operator
  - name: operators.operatorframework.io.bundle.channels.v1
    value: "alpha"
  - name: operators.operatorframework.io.bundle.channel.default.v1
    value: alpha
  - name: operators.operatorframework.io.metrics.mediatype.v1
    value: metrics+v1
  - name: operators.operatorframework.io.metrics.builder
    value: operator-sdk-v1.25.0
  - name: operators.operatorframework.io.metrics.project_layout
    value: go.kubebuilder.io/v3
  - name: operators.operatorframework.io.test.config.v1
    value: tests/scorecard/
  - name: operators.operatorframework.io.test.mediatype.v1
    value: scorecard+v1
  - name: com.redhat.delivery.operator.bundle
    value: "true"
  - name: com.redhat.openshift.versions
    value: v4.10

modules:
  repositories:
    - path: modules
  install:
    - name: org.apache.kie.sonataflow.bundle

```
</table>

Both of these files have a `version` property that is not being updated by the bump-version script, should they?

**Comment by tiagobento** [comment]
Note that 0.0.0 is the development version on `kie-tools`. Analogous to `999.0.0-snapshot`.

**Comment by ricardozanini** [comment]
@tiagobento @thiagoelg many thanks, yes they should. It will define the `:0.0.0` in the final tag. It's a minor since we can ensure the tag in the CI.

But it would be nice to update it. The script won't update because we newly introduced this feature. I think the makefile "build" which calls cekit will override this value, but let's also bump it.

**Comment by tiagobento** [comment]
I'm working on adapting the CI to the new operator package... I'm testing it in my fork and will push the changes here once I get a green build.

**Review by tiagobento — APPROVED** [review]

**Comment by domhanak** [comment]
@jakubschwan if you have time to check some baselines, let me know. I am currently struggling with local environment setup :D

**Review by porcelli — APPROVED** [review]
great job.. quite an effort as this PR shows that was not only move files, but not only adapt internal dependencies but also have to change the CI to accommodate larger builds (nice partitioning strategy!)

**Review by domhanak — COMMENTED** [review]
looks good

**Pull request merged**
