### PR TITLE
[DO NOT MERGE] yaml marshaller ci debug

### PR DESCRIPTION
**Pull request by fantonangeli**
This PR is only to debug the CI as the CI in my fork fails on different tests.  
My fork's PR: https://github.com/fantonangeli/kie-tools/pull/8

### CODE REVIEW

**Comment by fantonangeli** [comment]
Hi @romartin and @treblereel 
I managed to save some screenshots from the CI for the failing tests.
You can download the `Linux__integration-tests-artifacts ` package from the GH Action.

**Serverless workflow editor - Diagram navigation tests**
When the test tries to click on the `nodeIds[2]`  from the `diagramNavigation_8.png`, VSCode seems to close and we have a completely new environment `diagramNavigation_9.png`.
Maybe the number of `nodeIds` has changed?
https://github.com/fantonangeli/kie-tools/blob/d45b21c95ba368ad16ca94bddd5dc3200433c111/packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-diagram-navigation.test.ts#L79
diagramNavigation_8



**Serverless workflow editor - Basic operations tests**
"Opens, edits and saves the *.sw.json file"  is also related to the number of nodeIds, expected 6 and received 7 (openAndSave_1.png).
https://github.com/fantonangeli/kie-tools/blob/d45b21c95ba368ad16ca94bddd5dc3200433c111/packages/vscode-extension-serverless-workflow-editor/it-tests/serverless-workflow-editor-extension-basic-operations.test.ts#L82
openAndSave_1



"Renames *.sw.json file while editor is open": the test crashes
`openFileFromSidebar` expect the editor to have only 2 editor groups, but for some reason at line 142 all the files get closed. (openFileFromSidebar_hello-world-renamed.sw.json_05.png)
https://github.com/fantonangeli/kie-tools/blob/d45b21c95ba368ad16ca94bddd5dc3200433c111/packages/vscode-extension-serverless-workflow-editor/it-tests/helpers/VSCodeTestHelper.ts#L148
openFileFromSidebar_hello-world-renamed sw json_05

**Comment by romartin** [comment]
hey @fantonangeli , thanks for the head up!!! 
Recently @handreyrc and @paulovmr have been looking into a similar topic, so wondering if you @handreyrc can please take a look at this? 
thx in adance!

**Comment by handreyrc** [comment]
Hey @romartin,

Sure, I'm checking it!

**Comment by tiagobento** [comment]
@fantonangeli Interesting that the CI is failing in your fork... What could be the problem? 🧐 @caponetto Any ideas?

**Comment by fantonangeli** [comment]
> @fantonangeli Interesting that the CI is failing in your fork... What could be the problem? monocle_face @caponetto Any ideas?

@tiagobento If you refer to the "CI :: Code formatting", this is caused by the fact that I used the GitHub editor, to modify the files, avoiding doing local git fetch, pull, checkouts, push.... as I'm focusing on another task.

By modifying the files with GH you don't run the hooks that are not very important in this specific case because this PR is specific to debug the "CI :: Build/run" on Ubuntu.

**Pull request closed without merging**
