### PR TITLE
Serverless Workflow Editor dev webapp fix

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Review by caponetto — APPROVED** [review]
Thanks, @paulovmr!

**Comment by caponetto** [comment]
cc @jesuino @inodeman

**Comment by domhanak** [comment]
@paulovmr Hi Paulo, thanks for the fix, could you please explain the change?

**Comment by paulovmr** [comment]
@domhanak This allows the editor to open with an undefined channelApi (like in the dev webapp).

**Review by domhanak — APPROVED** [review]

**Pull request merged**
