### PR TITLE
KOGITO-8844: SWF Viewer - Preserve background color of a node in stunner diagram

### PR DESCRIPTION
**Pull request by hasys**
Hello @AjayJagan, @romartin, @LuboTerifaj,

there is the fix for preserving background.

Some key points: 

@AjayJagan: there is specifics to be aware of: 
* Only NONE state's background can be preserved (didn't preserved state between changed states before this PR)
* HIGHLIGHT state shouldn't change background and should reuse NONE background colour (was always white before this PR)
* If shape is not in NONE state, it's color won't be preserved. So before coloring the state should be moved to state NONE.

Example:
```javascript
canvas.applyState('uuid', 'none')
canvas.getWiresShape('uuid').setBackgroundColor('green')
canvas.draw()
```

@LuboTerifaj I added Integration tests, it is imitate real user interactions very good.

@romartin I removed Animation (which was with animation time 0 so didn't work anyway but executed part of the code in separate thread and complicated a lot state preservation), simplified a bit the code structure around the StateHandler and removed all code were it is easy to say: it is not used anymore.

### CODE REVIEW

**Review by AjayJagan — APPROVED** [review]
I tested the PR .. and it satisfies my requirement. Thanks Kirill for this great work 🎉

**Review by romartin — APPROVED** [review]

**Comment by romartin** [comment]
@LuboTerifaj Please missing QE review now. This fix is quite urgent, could you please consider its priorization? Thanks in advance!

**Review by LuboTerifaj — APPROVED** [review]
It looks good to me. Thanks!

**Comment by hasys** [comment]
Hello @kiegroup/gatekeepers PR is ready for merge.

Thank you!

**Pull request merged**
