### PR TITLE
KOGITO-6067 : Tasks in BPMN and specifically BR Node do not allow type to be Collection with a generic

### PR DESCRIPTION
**Pull request by inodeman**
Hi @romartin @domhanak brought the changes from old PR. https://github.com/kiegroup/kogito-editors-java/pull/143 Will let you know when ready for review.

### CODE REVIEW

**Comment by inodeman** [comment]
BPMN Vsix can be found here. https://drive.google.com/drive/folders/16Juogl24yEIN1kHsBON2TKxqokHCJfZn?usp=sharing

**Comment by inodeman** [comment]
Hi @domhanak @romartin PR ready for review :-)

**Comment by romartin** [comment]
@domhanak please this PR has been ported from kogito-editors-java and needs review again. Look at the close one, I think there is nothing else missing, just last check - https://github.com/kiegroup/kogito-editors-java/pull/143
Thanks!

**Review by domhanak — APPROVED** [review]
Rechecked the scenarios from last PR, and did not see any issues this time. 
LGTM

**Comment by inodeman** [comment]
Great, thanks @domhanak

**Review by romartin — APPROVED** [review]
Looks good, thanks @inodeman !

**Pull request merged**
