### PR TITLE
KOGITO-8280: preserve JSON properties that aren't defined as target for marshalling

### PR DESCRIPTION
**Pull request by treblereel**
@romartin possible fix

### CODE REVIEW

**Comment by romartin** [comment]
@handreyrc can you please review this? Thx in advance!

**Comment by handreyrc** [comment]
Hi @treblereel @romartin,

I tested the changes and It works, however, I have some concerns about having a post-deserialiser/serializer to merge the parsed object retrieved from the marshallers with the "original" content. 

- The merge process does not take into account the declaration order of properties. After reloading the JSON, undefined properties are forced to the bottom resulting in a different JSON even if no changes are made. It may be an inconvenience for the user otherwise somehow we may have to deal with it before presenting the reloaded JSON to the user again.
- Lets suppose that in the future, for some reason, we have some implementation that removes or replaces some specific property. These properties would come back to the final JSON after the merging process? 

IMO we should consider dealing with the undefined properties in the parse process itself instead of using a post processing approach. This way the workflow object is always the latest, no need to merge properties.

WDYT?

**Comment by treblereel** [comment]
> Hi @treblereel @romartin,
> 
> I tested the changes and It works, however, I have some concerns about having a post-deserialiser/serializer to merge the parsed object retrieved from the marshallers with the "original" content.
> 
> * The merge process does not take into account the declaration order of properties. After reloading the JSON, undefined properties are forced to the bottom resulting in a different JSON even if no changes are made. It may be an inconvenience for the user otherwise somehow we may have to deal with it before presenting the reloaded JSON to the user again.
> * Lets suppose that in the future, for some reason, we have some implementation that removes or replaces some specific property. These properties would come back to the final JSON after the merging process?
> 
> IMO we should consider dealing with the undefined properties in the parse process itself instead of using a post processing approach. This way the workflow object is always the latest, no need to merge properties.
> 
> WDYT?

Thanks for your review, i have never saw such requirement, but if it's exist, we should definitely file an issue.

**Comment by handreyrc** [comment]
Hey @treblereel,

I undertand your point. Anyway we can do those improvements in a new JIRA.
So I'm approving this PR.

Thanks for your work here!

**Review by handreyrc — APPROVED** [review]
Approved!!

Thanks

**Comment by treblereel** [comment]
> Approved!!
> 
> Thanks

From my point of view, each property must be defined in the corresponding definition, but as I understand, specs arent finished yet.

**Review by romartin — APPROVED** [review]
Approving, although reported a new JIRA for tracking the missing issues: 

https://issues.redhat.com/browse/KOGITO-8299

Thanks!

**Pull request merged**
