### PR TITLE
KOGITO-6506: Support transformation in External Data Sets

### PR DESCRIPTION
**Pull request by jesuino**
This adds support for JSONAta expressions in External DataSet.

This is only for Dashbuilder in client mode, the authoring tool will not have this feature.

About JSONAta: https://jsonata.org/

### CODE REVIEW

**Comment by jesuino** [comment]
Hello @sthundat !

Could you please review this PR?

The idea is make it possible to use any JSON with Dashbuilder, here's the simplest example:

https://jesuino.github.io/dashbuilder-client/?import=https%3A%2F%2Fgist.githubusercontent.com%2Fjesuino%2F0eb26e956f88636a53b98d7598d5c5ac%2Fraw%2F6adec61342dc9ea881ae0232091c9b093aef922e%2FTransformExample.yml#editor=true&preview=true


To try it you can:

* Build dashbuilder-runtime-client
* Open the file `target/dashbuilder-runtime-client/index.html` in browser
* In Developer Console, run the following code:


```
var content = {"datasets":[{"uuid":"pop","expression":"$.[name, age]","content":"[{\"name\": \"John\",\"age\": 35},{\"name\": \"Mary\",\"age\": 32}]"}],"layoutTemplates":[{"rows":[{"layoutColumns":[{"layoutComponents":[{"settings":{"type":"TABLE","dataSetLookup":{"dataSetUuid":"pop"}}}]}]}]}]};
window.postMessage(JSON.stringify(content), null)
```

image

Thanks!

**Comment by tiagobento** [comment]
Jenkins please retest this

**Comment by tiagobento** [comment]
@jomarko Is there a way for us to re-trigger the Sonar checks?

**Comment by yesamer** [comment]
jenkins retest this please

**Comment by jomarko** [comment]
Sonar will not give us results for now for touched files. Currently just `stunner-editors` package is assumed.

**Review by tiagobento — APPROVED** [review]

**Pull request merged**
