### PR TITLE
KOGITO-6830: Remove kie-soup-bom dependency from the stunner-editors package (Additional dependencies clean-up)

### PR DESCRIPTION
**Pull request by jomarko**
Additional cleanup for #891

### CODE REVIEW

**Comment by yesamer** [comment]
@jomarko Excellent work!

**Comment by jomarko** [comment]
@yesamer ready for a re-review. Build passed. I did sanity check of vsix. Opening existing and creating new assets.

**Review by yesamer — APPROVED** [review]
@jomarko Thank you, I assume you used `maven-dependency-plugin` to retrieve the list of unused dependencies. Fine to me.

**Comment by jomarko** [comment]
@yesamer yes, I did `mvn dependency:analyze` in modules you touched in originally in #891. 

I checked for those that are reported as:
- `unused`
- having `compile` scope

**Pull request merged**
