### PR TITLE
KOGITO-7872: Dashbuilder: Handle Navbar blank space

### PR DESCRIPTION
**Pull request by jesuino**
Actually removing the concept of top bar with Dashbuilder. Instead it will render the page navigation in a Tiles mode.

In a near future we could let users decide what kind of navigation they want by default.

### CODE REVIEW

**Review by paulovmr — APPROVED** [review]

**Review by tiagobento — APPROVED** [review]

**Comment by barboras7** [comment]
Hi @jesuino,
I can take a look at the PR but we have a QE face to face meeting until the end of the week. Would next Monday/Tuesday be okay?

**Comment by jesuino** [comment]
@barboras7 sounds fine to me, thanks!

**Review by ederign — APPROVED** [review]

**Comment by barboras7** [comment]
Hi @jesuino,

I checked the code and it looks good. Anyway, I also wanted to build dashbuilder to see the UI. Has something changed since I was working on this? 
I am getting many errors and I am not able to build the `dashbuilder` package. I tried both Java 11 and Java 17, using `mvn -U clean install -DskipTests`

Thanks

**Comment by jesuino** [comment]
Hello @barboras7 !

The easiest way to try Dashbuilder editor is by running on top level folder the following commands:

```
pnpm bootstrap -F dashbuilder-editor...
pnpm -F dashbuilder-editor... build:prod
```

Then go into `packages/dashbuilder-editor` and run `pnpm start` and you should open the dashbuilder editor at `http://localhost:9007/`

Another faster way is by building dashbuilder only in packages/dashbuilder using maven: `mvn clean install`, then go to `dashbuilder-runtime-parent/dashbuilder-runtime-client/target/dashbuilder-runtime-client` and use a web server such as `python -m http.server` and open `localhost:8000` to open dashbuilder and send content using Javascript from the console, for example:

```
window.postMessage(`
pages:
    - rows:
        - columns:
            - components:
                - html: "Hello World"
    - rows:
        - columns:
            - components:
                - html: "Hello World!"
    

`, null)
```

Thanks!

**Review by barboras7 — APPROVED** [review]
I'm sorry for the delay, I've had some issues building the PR. Everything looks good, thanks :partying_face: And thanks for your assistance @jesuino :slightly_smiling_face:

**Comment by jesuino** [comment]
Thank you so much, @barboras7

**Pull request merged**
