### PR TITLE
KOGITO-7052: [SWF Editor] Migrate SWF Diagram Editor from Errai/GWT to Crysknife/J2CL

### PR DESCRIPTION
**Pull request by treblereel**

### CODE REVIEW

**Comment by treblereel** [comment]
JIRA: https://issues.redhat.com/browse/KOGITO-7052

**Comment by tiagobento** [comment]
@treblereel Amazing! Didn't look at the code yet, but from the numbers of lines removed vs added I can tell this is promising :)

Can you please make this PR non-draft so the CI can run?

**Comment by tiagobento** [comment]
@treblereel Also, it would be good to solve the conflicts in the easiest way possible, so that the CI can run as well.

**Comment by treblereel** [comment]
> @treblereel Also, it would be good to solve the conflicts in the easiest way possible, so that the CI can run as well.

@tiagobento in progress

**Comment by treblereel** [comment]
retest this please

**Comment by treblereel** [comment]
windows build failed because of https://github.com/crysknife-io/crysknife/issues/93

**Comment by tiagobento** [comment]
@treblereel Nice! Looks like that's the only issue left before a green CI.

**Review by domhanak — CHANGES_REQUESTED** [review]
Gonna review when there are green CI checks. I can only see one now.

**Comment by domhanak** [comment]
Any updates?

**Comment by treblereel** [comment]
> Any updates?

Right now, any activities are postponed because JSON/YAML tasks have more priority. To be honest, I don't think I'll do anything here within this month

**Comment by romartin** [comment]
Closing as outdated

**Comment by ederign** [comment]
Closing due to inactivity. If you need it, feel free to reopen it.

**Pull request closed without merging**
