### PR TITLE
KOGITO-6981: SWF Editor - Viewer Look&Feel

### PR DESCRIPTION
**Pull request by handreyrc**
Hey @romartin,

Could you please review this PR?

**JIRA**: [KOGITO-6981](https://issues.redhat.com/browse/KOGITO-6981)
**JIRA**: [KOGITO-6767](https://issues.redhat.com/browse/KOGITO-6767)

Thanks!

### CODE REVIEW

**Review by romartin — APPROVED** [review]
Thanks @handreyrc , it looks good to me!! good job :+1:

**Comment by romartin** [comment]
Hey @domhanak ,

You're the tester for the ticket. You want to take a look too?

Thansk!

**Comment by handreyrc** [comment]
Hey @romartin  @domhanak,

I updated the callback state icon to the latest version sent by UX and fixed right magin for long names without spaces.

Thanks!

**Comment by domhanak** [comment]
oh sorry did not notice this - will finish today/tomorrow!

**Review by domhanak — CHANGES_REQUESTED** [review]
I noticed some malformed stuff, here is what I tested:

- Background: grey, no grid :heavy_check_mark: 
- Shapes stylings (shapes, icons, connectors, text wrapping not overlapping) :red_circle: 
- Layout. Use preffered TOP-BOTTOM, main flow at LEFT, subflows expanded to RIGHT, no space saving (QE: here it looks ok, but I am not sure I tested properly)
- Do not merge line paths (lines must not overlap) :heavy_check_mark: 
-  No need for icons in the connectors, are styles are already defining each type properly (QE: not sure what to test)
-  State style management: Hover & Selected :heavy_check_mark: 
- Use some bg alpha for Start / End :heavy_check_mark: 
- Text should not overlap icons (in states) :red_circle: 


See the pictures for malformed texts:
Screenshot from 2022-05-09 10-09-45
Screenshot from 2022-05-09 10-08-44
Screenshot from 2022-05-09 10-08-19

**Comment by handreyrc** [comment]
Hey @domhanak, @romartin 

In regards with the issue with the text alignment. 
If you reload the page and open any diagram for the very first time it works, however, if you reopen the same diagram or any other diagram without reloading the page it breaks. 
It seems we have bug related to the Fonthandler when the text alignment is set to "LEFT". It loses/doesn't apply the margin setting when you reload the diagram or a load a different one. 

Should we open a new JIRA for this issue?
WDYT @romartin?

Thanks!

**Comment by romartin** [comment]
Hey @domhanak @handreyrc 

Thanks, good catch on the issue about text wrapping. I just reported this:

https://issues.redhat.com/browse/KOGITO-7132

Let's address this before releasing, but let's try not blocking this PR for now. Are you agree on this?

Thanks in advance!

**Review by domhanak — APPROVED** [review]
I see, thanks. LGTM

**Pull request merged**
